<?php
require_once dirname(__DIR__) . '/includes/functions.php';
employeePortalGuard();$user=currentUser();$pdo=getDB();$employee=employeeForCurrentUser($pdo,$user);if(!$employee){siteHeader('My Leave','login');echo '<div class="alert alert-warning">No employee profile is linked to your email.</div>';siteFooter();exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){try{$stmt=$pdo->prepare('INSERT INTO '.table('leave_requests').' (employee_id,leave_type,start_date,end_date,reason,status) VALUES (?,?,?,?,?,"pending")');$stmt->execute([(int)$employee['id'],trim((string)$_POST['leave_type']),trim((string)$_POST['start_date']),trim((string)$_POST['end_date']),trim((string)$_POST['reason'])]);ensureEmployeeLeaveBalance($pdo,(int)$employee['id'],trim((string)$_POST['leave_type']),(int)date('Y',strtotime($_POST['start_date'])));flash('success','Leave request submitted.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect(SITE_URL.'/employee/leave.php');}
$rows=$pdo->prepare('SELECT * FROM '.table('leave_requests').' WHERE employee_id=? ORDER BY created_at DESC');$rows->execute([(int)$employee['id']]);$rows=$rows->fetchAll();
$balances=$pdo->prepare('SELECT * FROM '.table('employee_leave_balances').' WHERE employee_id=? ORDER BY year_no DESC,leave_type');$balances->execute([(int)$employee['id']]);$balances=$balances->fetchAll();
siteHeader('My Leave','login');
?>
<h1 class="mb-4">My Leave</h1><div class="row g-4"><div class="col-lg-5"><form method="post" class="form-card"><h2 class="h4">Request Leave</h2><select class="form-select mb-3" name="leave_type"><option>Annual Leave</option><option>Sick Leave</option><option>Emergency Leave</option><option>Unpaid Leave</option></select><input class="form-control mb-3" type="date" name="start_date" required><input class="form-control mb-3" type="date" name="end_date" required><textarea class="form-control mb-3" name="reason" rows="4" placeholder="Reason"></textarea><button class="btn btn-brand">Submit Request</button></form><div class="table-card table-responsive mt-4"><h2 class="h5">Balances</h2><table class="table"><thead><tr><th>Type</th><th>Year</th><th>Remaining</th></tr></thead><tbody><?php foreach($balances as $b): ?><tr><td><?php echo esc($b['leave_type']); ?></td><td><?php echo (int)$b['year_no']; ?></td><td><strong><?php echo number_format((float)$b['remaining_days'],2); ?></strong></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-lg-7"><div class="table-card table-responsive"><h2 class="h5">Requests</h2><table class="table"><thead><tr><th>Type</th><th>Dates</th><th>Status</th><th>Decision</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?php echo esc($r['leave_type']); ?></td><td><?php echo esc($r['start_date'].' → '.$r['end_date']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td><td><?php echo esc($r['decision_notes']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php siteFooter(); ?>