<?php
require_once dirname(__DIR__) . '/includes/functions.php';
websitePermissionGuard('b2b_quote_request');
$pdo=getDB();$products=$pdo->query('SELECT id,sku,name,price,stock FROM '.table('products').' WHERE active=1 ORDER BY name LIMIT 200')->fetchAll();$done=null;$selected=(int)($_GET['product_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{$items=[];foreach(($_POST['items']??[]) as $pid=>$qty){$qty=(float)$qty;if($qty<=0)continue;$s=$pdo->prepare('SELECT id,sku,name,price FROM '.table('products').' WHERE id=?');$s->execute([(int)$pid]);$p=$s->fetch();if($p){$items[]=['product_id'=>$p['id'],'product_name'=>$p['name'],'sku'=>$p['sku'],'quantity'=>$qty,'unit_price'=>$p['price'],'target_price'=>(float)($_POST['target_price'][$pid]??0)];}}if(!$items)throw new RuntimeException('Please select at least one product.');$id=ecom33CreateQuoteRequest($pdo,$_POST,$items);$done='Quote request created. Reference ID: '.$id;}catch(Throwable $e){$done=$e->getMessage();}}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Request Quote</title><?php echo <<<'CSS'
<style>
body{margin:0;background:#f8fafc;color:#0f172a;font-family:Inter,Arial,sans-serif}.wrap{max-width:1180px;margin:auto;padding:24px}.hero{background:linear-gradient(135deg,#0f172a,#1e293b);color:#fff;border-radius:28px;padding:34px;margin-bottom:22px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:22px;padding:18px;box-shadow:0 12px 28px rgba(15,23,42,.06)}.btn{display:inline-block;border:0;border-radius:14px;background:#0f172a;color:#fff;padding:11px 14px;text-decoration:none;cursor:pointer}.btn2{background:#fff;color:#0f172a;border:1px solid #cbd5e1}.input{width:100%;box-sizing:border-box;border:1px solid #cbd5e1;border-radius:14px;padding:11px;margin-bottom:10px}.muted{color:#64748b}.price{font-size:22px;font-weight:800}.table{width:100%;border-collapse:collapse}.table td,.table th{padding:12px;border-bottom:1px solid #e2e8f0;text-align:left}@media(max-width:700px){.wrap{padding:14px}.hero{padding:24px}.grid{grid-template-columns:1fr}.table{font-size:13px}}</style>
CSS; ?></head><body><div class="wrap"><div class="hero"><h1>Request a Quote</h1><p>Send a quote request for workshop equipment, tools, software, bundles or B2B pricing.</p></div><?php if($done): ?><div class="card"><strong><?php echo esc($done); ?></strong></div><?php endif; ?><form method="post"><div class="grid"><div class="card"><h2>Contact</h2><select class="input" name="customer_type"><option>b2b</option><option>b2c</option><option>dealer</option></select><input class="input" name="company_name" placeholder="Company name"><input class="input" name="contact_name" placeholder="Contact name" required><input class="input" name="email" placeholder="Email" required><input class="input" name="phone" placeholder="Phone"><select class="input" name="priority"><option>normal</option><option>high</option><option>urgent</option></select><textarea class="input" name="notes" placeholder="Requirements"></textarea><button class="btn">Submit Quote Request</button></div><div class="card" style="grid-column:span 2"><h2>Products</h2><table class="table"><tr><th>Product</th><th>Price</th><th>Qty</th><th>Target Price</th></tr><?php foreach($products as $p): ?><tr><td><strong><?php echo esc($p['name']); ?></strong><br><span class="muted"><?php echo esc($p['sku']); ?></span></td><td><?php echo money($p['price']); ?></td><td><input class="input" style="max-width:90px" type="number" min="0" step="1" name="items[<?php echo (int)$p['id']; ?>]" value="<?php echo $selected===(int)$p['id']?1:0; ?>"></td><td><input class="input" style="max-width:130px" type="number" step="0.01" name="target_price[<?php echo (int)$p['id']; ?>]"></td></tr><?php endforeach; ?></table></div></div></form></div></body></html>