<?php
require_once dirname(__DIR__) . '/includes/functions.php';
employeePortalGuard();$user=currentUser();$pdo=getDB();
$jobs=$pdo->prepare('SELECT id,job_card_number,customer_name FROM '.table('job_cards').' WHERE technician_user_id=? AND status IN ("diagnosis","in_progress","waiting_parts","completed") ORDER BY created_at DESC');$jobs->execute([$user['id']]);$jobRows=$jobs->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{$hours=max(0,(float)$_POST['hours']);$rate=max(0,(float)setting('default_technician_hourly_cost','35'));$pdo->prepare('INSERT INTO '.table('technician_timesheets').' (technician_user_id,job_card_id,work_date,hours,hourly_cost,cost_amount,is_billable,status,notes) VALUES (?,?,?,?,?,?,1,"draft",?)')->execute([$user['id'],(int)$_POST['job_card_id'],trim($_POST['work_date']??date('Y-m-d')),$hours,$rate,round($hours*$rate,2),trim($_POST['notes']??'')]);flash('success','Timesheet submitted as draft.');}catch(Throwable $e){flash('error',$e->getMessage());}
  redirect(SITE_URL.'/technician/timesheets.php');
}
$stmt=$pdo->prepare('SELECT tt.*,jc.job_card_number FROM '.table('technician_timesheets').' tt LEFT JOIN '.table('job_cards').' jc ON jc.id=tt.job_card_id WHERE tt.technician_user_id=? ORDER BY tt.work_date DESC,tt.id DESC LIMIT 80');$stmt->execute([$user['id']]);$rows=$stmt->fetchAll();
siteHeader('Technician Timesheets','login');
?>
<h1 class="mb-4">Timesheets</h1><div class="row g-4"><div class="col-lg-5"><form method="post" class="form-card"><h2 class="h4">Submit Time</h2><label class="form-label">Job Card</label><select class="form-select mb-3" name="job_card_id" required><?php foreach($jobRows as $j): ?><option value="<?php echo (int)$j['id']; ?>"><?php echo esc($j['job_card_number'].' · '.$j['customer_name']); ?></option><?php endforeach; ?></select><label class="form-label">Work Date</label><input class="form-control mb-3" type="date" name="work_date" value="<?php echo esc(date('Y-m-d')); ?>"><label class="form-label">Hours</label><input class="form-control mb-3" type="number" step="0.25" name="hours" required><label class="form-label">Notes</label><textarea class="form-control mb-3" name="notes" rows="3"></textarea><button class="btn btn-brand">Submit</button></form></div><div class="col-lg-7"><div class="table-card table-responsive"><table class="table"><thead><tr><th>Date</th><th>Job</th><th>Hours</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?php echo esc($r['work_date']); ?></td><td><?php echo esc($r['job_card_number']); ?></td><td><?php echo number_format((float)$r['hours'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php siteFooter(); ?>