<?php
$pageTitle='Advanced Quote Requests';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('advanced_quote_requests');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{$action=(string)($_POST['action']??'status');$table=$action==='bulk_status'?'bulk_order_requests':'quote_requests_2';$id=(int)$_POST['id'];$status=trim((string)$_POST['status']);$pdo->prepare('UPDATE '.table($table).' SET status=? WHERE id=?')->execute([$status,$id]);flash('success','Status updated.');}
  catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'advanced-quote-requests']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/advanced-quote-requests.php');
}
$quotes=$pdo->query('SELECT * FROM '.table('quote_requests_2').' ORDER BY FIELD(status,"new","reviewing","quoted","converted","closed"),created_at DESC LIMIT 200')->fetchAll();
$bulk=$pdo->query('SELECT * FROM '.table('bulk_order_requests').' ORDER BY FIELD(status,"new","reviewing","quoted","converted","closed"),created_at DESC LIMIT 200')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="mb-4"><div class="erp-kicker">Store Enquiries</div><h2 class="h4 mb-1">Quote Requests & Bulk Orders 2.0</h2><p class="text-secondary mb-0">Manage advanced request-quote and bulk-order leads from the storefront.</p></div>
<div class="row g-4"><div class="col-xl-6"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Quote Requests</h2><table class="table align-middle"><thead><tr><th>Request</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody><?php foreach($quotes as $q): ?><tr><td><strong><?php echo esc($q['quote_request_number']); ?></strong><div class="small text-secondary"><?php echo esc($q['created_at'].' · '.$q['source']); ?></div></td><td><?php echo esc($q['company_name']?:$q['contact_name']); ?><div class="small text-secondary"><?php echo esc($q['email'].' · '.$q['phone']); ?></div></td><td><?php echo money($q['estimated_total']); ?></td><td><form method="post" class="d-flex gap-1"><input type="hidden" name="id" value="<?php echo (int)$q['id']; ?>"><select class="form-select form-select-sm" name="status"><option <?php echo $q['status']==='new'?'selected':''; ?>>new</option><option <?php echo $q['status']==='reviewing'?'selected':''; ?>>reviewing</option><option <?php echo $q['status']==='quoted'?'selected':''; ?>>quoted</option><option <?php echo $q['status']==='converted'?'selected':''; ?>>converted</option><option <?php echo $q['status']==='closed'?'selected':''; ?>>closed</option></select><button class="btn btn-sm btn-outline-primary">Save</button></form></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-6"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Bulk Orders</h2><table class="table align-middle"><thead><tr><th>Bulk Request</th><th>Customer</th><th>Subtotal</th><th>Status</th></tr></thead><tbody><?php foreach($bulk as $b): ?><tr><td><strong><?php echo esc($b['bulk_request_number']); ?></strong><div class="small text-secondary"><?php echo esc($b['required_date'].' · '.$b['created_at']); ?></div></td><td><?php echo esc($b['company_name']?:$b['contact_name']); ?><div class="small text-secondary"><?php echo esc($b['email'].' · '.$b['phone']); ?></div></td><td><?php echo money($b['subtotal']); ?></td><td><form method="post" class="d-flex gap-1"><input type="hidden" name="action" value="bulk_status"><input type="hidden" name="id" value="<?php echo (int)$b['id']; ?>"><select class="form-select form-select-sm" name="status"><option <?php echo $b['status']==='new'?'selected':''; ?>>new</option><option <?php echo $b['status']==='reviewing'?'selected':''; ?>>reviewing</option><option <?php echo $b['status']==='quoted'?'selected':''; ?>>quoted</option><option <?php echo $b['status']==='converted'?'selected':''; ?>>converted</option><option <?php echo $b['status']==='closed'?'selected':''; ?>>closed</option></select><button class="btn btn-sm btn-outline-primary">Save</button></form></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>