<?php
$pageTitle='Advanced Reporting';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('advanced_reporting');
$pdo=getDB();
$reportTypes=reportTypeOptions();
$summary=['saved'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('saved_reports').' WHERE active=1')->fetchColumn(),'schedules'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('report_schedules').' WHERE status="active"')->fetchColumn(),'exports'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('report_export_files'))->fetchColumn(),'kpis'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('report_kpis').' WHERE active=1')->fetchColumn()];
$reports=$pdo->query('SELECT r.*,u.email owner_email,(SELECT COUNT(*) FROM '.table('report_runs').' rr WHERE rr.saved_report_id=r.id) run_count FROM '.table('saved_reports').' r LEFT JOIN '.table('users').' u ON u.id=r.owner_user_id ORDER BY r.created_at DESC LIMIT 100')->fetchAll();
$runs=$pdo->query('SELECT rr.*,sr.report_code,sr.report_name,u.email run_by_email FROM '.table('report_runs').' rr LEFT JOIN '.table('saved_reports').' sr ON sr.id=rr.saved_report_id LEFT JOIN '.table('users').' u ON u.id=rr.run_by ORDER BY rr.created_at DESC LIMIT 20')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Reporting Command Center</div><h2 class="h4 mb-1">Advanced Reporting</h2><p class="text-secondary mb-0">Saved reports, KPI monitoring, scheduled report runs, and export governance.</p></div><div class="d-flex gap-2"><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/report-builder.php"><?php echo t('Report Builder', 'منشئ التقارير'); ?></a><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/report-export-center.php"><?php echo t('Export Center', 'مركز التصدير'); ?></a></div></div>
<div class="row g-4 mb-4"><?php foreach($summary as $label=>$value): ?><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker"><?php echo esc(ucwords(str_replace('_',' ',$label))); ?></div><div class="metric-sm"><?php echo (int)$value; ?></div></div></div><?php endforeach; ?></div>
<div class="row g-4"><div class="col-xl-7"><div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Report Catalog</div><h2 class="h5 mb-0">Saved Reports</h2></div></div><table class="table align-middle"><thead><tr><th>Report</th><th>Type</th><th>Visibility</th><th>Runs</th><th>Export</th></tr></thead><tbody><?php foreach($reports as $report): ?><tr><td><strong><?php echo esc($report['report_code']); ?></strong><div class="small text-secondary"><?php echo esc($report['report_name']); ?></div></td><td><?php echo esc($reportTypes[$report['report_type']]??$report['report_type']); ?></td><td><?php echo esc($report['visibility']); ?></td><td><?php echo (int)$report['run_count']; ?></td><td><a class="btn btn-sm btn-outline-success" href="<?php echo esc(ADMIN_URL); ?>/erp/report-export-center.php?export=1&saved_report_id=<?php echo (int)$report['id']; ?>&format=csv">CSV</a></td></tr><?php endforeach; ?><?php if(!$reports): ?><tr><td colspan="5" class="text-secondary">No saved reports yet.</td></tr><?php endif; ?></tbody></table></div></div><div class="col-xl-5"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Recent Runs</h2><table class="table"><tbody><?php foreach($runs as $run): ?><tr><td><strong><?php echo esc($run['report_code']?:'Manual'); ?></strong><div class="small text-secondary"><?php echo esc($run['report_name'].' · '.$run['created_at']); ?></div></td><td><?php echo (int)$run['row_count']; ?> rows</td><td><span class="badge bg-<?php echo esc(statusTone($run['status'])); ?>"><?php echo esc($run['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$runs): ?><tr><td class="text-secondary">No report runs yet.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>