<?php
$pageTitle='AI Assistant';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('ai_assistant');
$pdo=getDB();$user=currentUser();$sessionId=(int)($_GET['session_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{$message=trim((string)($_POST['message']??''));if($message===''){throw new RuntimeException('Please type a message.');}$sessionId=(int)($_POST['session_id']??0);if($sessionId<=0){$number=nextScopedDocumentNumber($pdo,'ai_assistant_session','AIS',operationalScope($pdo));$pdo->prepare('INSERT INTO '.table('ai_assistant_sessions').' (session_number,session_title,user_id,module_context,status) VALUES (?,?,?,?, "open")')->execute([$number,substr($message,0,120),(int)($user['id']??0)?:null,trim((string)($_POST['module_context']??'General'))]);$sessionId=(int)$pdo->lastInsertId();}$pdo->prepare('INSERT INTO '.table('ai_assistant_messages').' (ai_assistant_session_id,sender_type,message_text,intent_key,confidence_score) VALUES (?, "user", ?, "user_prompt", 100)')->execute([$sessionId,$message]);$reply=assistantRuleResponse($pdo,$message);$pdo->prepare('INSERT INTO '.table('ai_assistant_messages').' (ai_assistant_session_id,sender_type,message_text,intent_key,confidence_score,action_json) VALUES (?, "assistant", ?, "rules_based_response", 85, ?)')->execute([$sessionId,$reply,json_encode(['mode'=>setting('ai_assistant_mode','rules_based')])]);flash('success','Assistant response generated.');}catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'ai-assistant']);flash('error',$e->getMessage());}redirect(ADMIN_URL.'/erp/ai-assistant.php?session_id='.$sessionId);
}
$sessions=$pdo->query('SELECT * FROM '.table('ai_assistant_sessions').' ORDER BY created_at DESC LIMIT 50')->fetchAll();$messages=[];if($sessionId){$stmt=$pdo->prepare('SELECT * FROM '.table('ai_assistant_messages').' WHERE ai_assistant_session_id=? ORDER BY created_at,id');$stmt->execute([$sessionId]);$messages=$stmt->fetchAll();}$insights=$pdo->query('SELECT * FROM '.table('ai_insight_cards').' WHERE status="open" ORDER BY FIELD(severity,"high","warning","info"),created_at DESC LIMIT 8')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Rules-Based ERP Intelligence</div><h2 class="h4 mb-1">AI Assistant Command Center</h2><p class="text-secondary mb-0">Ask operational questions about sales, inventory, finance, service jobs, and dispatch.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/predictive-alerts.php"><?php echo t('Predictive Alerts', 'تنبيهات تنبؤية'); ?></a></div>
<div class="row g-4"><div class="col-xl-3"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Sessions</h2><table class="table"><tbody><?php foreach($sessions as $s): ?><tr><td><a href="?session_id=<?php echo (int)$s['id']; ?>"><strong><?php echo esc($s['session_number']); ?></strong></a><div class="small text-secondary"><?php echo esc($s['session_title']); ?></div></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-6"><div class="card-admin p-4 mb-4"><form method="post"><input type="hidden" name="session_id" value="<?php echo (int)$sessionId; ?>"><label class="form-label">Ask the ERP assistant</label><textarea class="form-control mb-2" name="message" rows="3" placeholder="Example: Show me low stock risk, sales performance, open receivables, or delayed jobs"></textarea><input class="form-control mb-3" name="module_context" value="General"><button class="btn btn-brand">Ask Assistant</button></form></div><div class="card-admin p-4"><?php foreach($messages as $msg): ?><div class="mb-3 <?php echo $msg['sender_type']==='assistant'?'border-start border-primary ps-3':''; ?>"><div class="small text-secondary"><?php echo esc($msg['sender_type'].' · '.$msg['created_at']); ?></div><div><?php echo nl2br(esc($msg['message_text'])); ?></div></div><?php endforeach; ?><?php if(!$messages): ?><p class="text-secondary mb-0">No active conversation yet.</p><?php endif; ?></div></div><div class="col-xl-3"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Insight Cards</h2><?php foreach($insights as $card): ?><div class="border rounded-4 p-3 mb-2"><span class="badge bg-<?php echo esc(statusTone($card['severity'])); ?>"><?php echo esc($card['severity']); ?></span><h3 class="h6 mt-2 mb-1"><?php echo esc($card['card_title']); ?></h3><p class="small text-secondary mb-1"><?php echo esc($card['summary']); ?></p><p class="small mb-0"><?php echo esc($card['recommendation']); ?></p></div><?php endforeach; ?></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>