<?php
$pageTitle='Anomaly Detection';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('anomaly_detection');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$action=(string)($_POST['action']??'');if($action==='generate'){$r=generateAnomalyDetections($pdo);flash('success','Generated '.$r['created'].' anomaly records.');}elseif($action==='resolve'){$pdo->prepare('UPDATE '.table('anomaly_detections').' SET status="resolved",resolved_at=NOW() WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Anomaly resolved.');}}catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'anomaly-detection']);flash('error',$e->getMessage());}redirect(ADMIN_URL.'/erp/anomaly-detection.php');}
$rows=$pdo->query('SELECT * FROM '.table('anomaly_detections').' ORDER BY FIELD(status,"open","resolved"),FIELD(severity,"high","medium","low"),created_at DESC LIMIT 250')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Exception Monitoring</div><h2 class="h4 mb-1">Anomaly Detection</h2><p class="text-secondary mb-0">Detect unusual sales, expense, and operational values using simple baseline rules.</p></div><form method="post"><input type="hidden" name="action" value="generate"><button class="btn btn-brand">Run Detection</button></form></div><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Anomaly</th><th>Module</th><th>Baseline</th><th>Observed</th><th>Variance</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?php echo esc($r['anomaly_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['title']); ?></div><p class="small mb-0"><?php echo esc($r['description']); ?></p></td><td><?php echo esc($r['module']); ?><div><span class="badge bg-<?php echo esc(statusTone($r['severity'])); ?>"><?php echo esc($r['severity']); ?></span></div></td><td><?php echo number_format((float)$r['baseline_value'],2); ?></td><td><?php echo number_format((float)$r['observed_value'],2); ?></td><td><?php echo number_format((float)$r['variance_value'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td><td><?php if($r['status']==='open'): ?><form method="post"><input type="hidden" name="action" value="resolve"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn btn-sm btn-outline-success">Resolve</button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="7" class="text-secondary">No anomalies yet. Run detection.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>