<?php
$pageTitle='API Usage Limits';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('api_usage_limits');
$pdo=getDB();$keys=$pdo->query('SELECT * FROM '.table('api_keys').' ORDER BY key_name')->fetchAll();$companies=$pdo->query('SELECT id,company_code,company_name FROM '.table('companies').' ORDER BY company_name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{createApiUsageLimit($pdo,(int)($_POST['api_key_id']??0)?:null,(int)($_POST['company_id']??0)?:null,trim((string)$_POST['scope_key']),max(1,(int)$_POST['request_limit']),trim((string)$_POST['limit_window']));flash('success','API usage limit created.');}
  catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'api-usage-limits']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/api-usage-limits.php');
}
$limits=$pdo->query('SELECT l.*,ak.key_name,c.company_name FROM '.table('api_usage_limits').' l LEFT JOIN '.table('api_keys').' ak ON ak.id=l.api_key_id LEFT JOIN '.table('companies').' c ON c.id=l.company_id ORDER BY l.created_at DESC LIMIT 200')->fetchAll();
$counters=$pdo->query('SELECT uc.*,ak.key_name,c.company_name FROM '.table('api_usage_counters').' uc LEFT JOIN '.table('api_keys').' ak ON ak.id=uc.api_key_id LEFT JOIN '.table('companies').' c ON c.id=uc.company_id ORDER BY uc.counter_date DESC,uc.request_count DESC LIMIT 200')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">API Throttling Foundation</div><h2 class="h4 mb-1">API Usage Limits</h2><p class="text-secondary mb-0">Define key/company scope limits and review request counters.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Create Limit</h2><select class="form-select mb-2" name="api_key_id"><option value="">Any API key</option><?php foreach($keys as $k): ?><option value="<?php echo (int)$k['id']; ?>"><?php echo esc($k['key_name'].' · '.$k['key_prefix']); ?></option><?php endforeach; ?></select><select class="form-select mb-2" name="company_id"><option value="">Any company</option><?php foreach($companies as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo esc($c['company_code'].' · '.$c['company_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="scope_key" value="read:products"><select class="form-select mb-2" name="limit_window"><option>daily</option><option>hourly</option><option>monthly</option></select><input class="form-control mb-3" type="number" name="request_limit" value="<?php echo esc(setting('api_default_daily_limit','1000')); ?>"><button class="btn btn-brand w-100">Create Limit</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Limits</h2><table class="table"><thead><tr><th>Limit</th><th>Key / Company</th><th>Scope</th><th>Limit</th></tr></thead><tbody><?php foreach($limits as $l): ?><tr><td><strong><?php echo esc($l['limit_number']); ?></strong></td><td><?php echo esc(($l['key_name']?:'Any key').' · '.($l['company_name']?:'Any company')); ?></td><td><?php echo esc($l['scope_key']); ?></td><td><?php echo (int)$l['request_limit'].' / '.esc($l['limit_window']); ?></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Counters</h2><table class="table"><thead><tr><th>Date</th><th>Key</th><th>Scope</th><th>Requests</th></tr></thead><tbody><?php foreach($counters as $c): ?><tr><td><?php echo esc($c['counter_date']); ?></td><td><?php echo esc($c['key_name']); ?></td><td><?php echo esc($c['scope_key']); ?></td><td><?php echo (int)$c['request_count']; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>