<?php
$pageTitle='API Endpoint Catalog';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('api_endpoint_catalog');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'endpoint');
    if($action==='install'){$created=installApiEndpointCatalog($pdo);$scopes=installApiScopePolicies($pdo);flash('success','Endpoint defaults: '.$created.', scopes: '.$scopes);}
    elseif($action==='scope'){$pdo->prepare('INSERT INTO '.table('api_scope_policies').' (scope_key,scope_name,module,access_level,description,status) VALUES (?,?,?,?,?,"active") ON DUPLICATE KEY UPDATE scope_name=VALUES(scope_name),module=VALUES(module),access_level=VALUES(access_level),description=VALUES(description)')->execute([trim((string)$_POST['scope_key']),trim((string)$_POST['scope_name']),trim((string)$_POST['module']),trim((string)$_POST['access_level']),trim((string)$_POST['description'])]);flash('success','Scope policy saved.');}
    else{$code=trim((string)$_POST['endpoint_code']);if($code===''){$code=nextScopedDocumentNumber($pdo,'api_endpoint',setting('api_endpoint_prefix','APIEND'),operationalScope($pdo));}$pdo->prepare('INSERT INTO '.table('api_endpoint_catalog').' (endpoint_code,endpoint_name,http_method,route_path,module,required_scope,description,request_example,response_example,status) VALUES (?,?,?,?,?,?,?,?,?,"active")')->execute([$code,trim((string)$_POST['endpoint_name']),trim((string)$_POST['http_method']),trim((string)$_POST['route_path']),trim((string)$_POST['module']),trim((string)$_POST['required_scope']),trim((string)$_POST['description']),trim((string)$_POST['request_example']),trim((string)$_POST['response_example'])]);flash('success','Endpoint catalog item created.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'api-endpoint-catalog']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/api-endpoint-catalog.php');
}
$endpoints=$pdo->query('SELECT * FROM '.table('api_endpoint_catalog').' ORDER BY module,http_method,route_path LIMIT 250')->fetchAll();
$scopes=$pdo->query('SELECT * FROM '.table('api_scope_policies').' ORDER BY module,scope_key LIMIT 200')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">REST API Governance</div><h2 class="h4 mb-1">API Endpoint Catalog</h2><p class="text-secondary mb-0">Document endpoints, methods, scopes, examples and integration access policy.</p></div><form method="post"><input type="hidden" name="action" value="install"><button class="btn btn-brand">Install Defaults</button></form></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4 mb-4"><h2 class="h5 mb-3">Add Endpoint</h2><input class="form-control mb-2" name="endpoint_code" placeholder="Auto or products_list"><input class="form-control mb-2" name="endpoint_name" placeholder="Endpoint name"><select class="form-select mb-2" name="http_method"><option>GET</option><option>POST</option><option>PUT</option><option>DELETE</option></select><input class="form-control mb-2" name="route_path" placeholder="/api/v1/products.php"><input class="form-control mb-2" name="module" placeholder="Products"><input class="form-control mb-2" name="required_scope" placeholder="read:products"><textarea class="form-control mb-2" name="description" rows="2"></textarea><textarea class="form-control mb-2" name="request_example" rows="2">{}</textarea><textarea class="form-control mb-3" name="response_example" rows="2">{}</textarea><button class="btn btn-outline-primary w-100">Add Endpoint</button></form><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="scope"><h2 class="h5 mb-3">Add Scope</h2><input class="form-control mb-2" name="scope_key" placeholder="read:products"><input class="form-control mb-2" name="scope_name" placeholder="Read Products"><input class="form-control mb-2" name="module" placeholder="Products"><select class="form-select mb-2" name="access_level"><option>read</option><option>write</option><option>admin</option></select><textarea class="form-control mb-3" name="description" rows="2"></textarea><button class="btn btn-brand w-100">Save Scope</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Endpoints</h2><table class="table"><thead><tr><th>Endpoint</th><th>Method</th><th>Route</th><th>Scope</th></tr></thead><tbody><?php foreach($endpoints as $e): ?><tr><td><strong><?php echo esc($e['endpoint_code']); ?></strong><div class="small text-secondary"><?php echo esc($e['endpoint_name'].' · '.$e['module']); ?></div></td><td><?php echo esc($e['http_method']); ?></td><td><code><?php echo esc($e['route_path']); ?></code></td><td><?php echo esc($e['required_scope']); ?></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Scopes</h2><table class="table"><thead><tr><th>Scope</th><th>Module</th><th>Access</th><th>Status</th></tr></thead><tbody><?php foreach($scopes as $s): ?><tr><td><strong><?php echo esc($s['scope_key']); ?></strong><div class="small text-secondary"><?php echo esc($s['scope_name']); ?></div></td><td><?php echo esc($s['module']); ?></td><td><?php echo esc($s['access_level']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($s['status'])); ?>"><?php echo esc($s['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>