<?php
$pageTitle='Attendance';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('attendance');
$pdo=getDB();
$employees=$pdo->query('SELECT * FROM '.table('employees').' WHERE status="active" ORDER BY first_name,last_name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $employeeId=(int)$_POST['employee_id'];$date=trim((string)$_POST['work_date']);$in=trim((string)($_POST['check_in']??''));$out=trim((string)($_POST['check_out']??''));$status=trim((string)($_POST['status']??'present'));
    $regular=max(0,(float)($_POST['regular_hours']??0));$overtime=max(0,(float)($_POST['overtime_hours']??0));
    if($regular<=0 && $in!=='' && $out!==''){$regular=max(0,round((strtotime($out)-strtotime($in))/3600,2));}
    $stmt=$pdo->prepare('INSERT INTO '.table('attendance_records').' (employee_id,work_date,check_in,check_out,regular_hours,overtime_hours,status,notes) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE check_in=VALUES(check_in),check_out=VALUES(check_out),regular_hours=VALUES(regular_hours),overtime_hours=VALUES(overtime_hours),status=VALUES(status),notes=VALUES(notes)');
    $stmt->execute([$employeeId,$date,$in?:null,$out?:null,$regular,$overtime,$status,trim((string)($_POST['notes']??''))]);
    flash('success','Attendance saved.');
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'attendance']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/attendance.php');
}
$from=trim((string)($_GET['from']??date('Y-m-01')));$to=trim((string)($_GET['to']??date('Y-m-t')));
$stmt=$pdo->prepare('SELECT a.*,e.employee_code,e.first_name,e.last_name FROM '.table('attendance_records').' a LEFT JOIN '.table('employees').' e ON e.id=a.employee_id WHERE a.work_date BETWEEN ? AND ? ORDER BY a.work_date DESC,e.first_name LIMIT 300');$stmt->execute([$from,$to]);$rows=$stmt->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Attendance & Overtime</div><h2 class="h4 mb-1">Attendance</h2><p class="text-secondary mb-0">Capture attendance, absence, regular hours, and overtime for payroll calculation.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/payroll-runs.php"><?php echo t('Payroll Runs', 'تشغيل الرواتب'); ?></a></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Record Attendance</h2><label class="form-label">Employee</label><select class="form-select mb-2" name="employee_id" required><?php foreach($employees as $e): ?><option value="<?php echo (int)$e['id']; ?>"><?php echo esc(employeeLabel($e)); ?></option><?php endforeach; ?></select><label class="form-label">Date</label><input class="form-control mb-2" type="date" name="work_date" value="<?php echo esc(date('Y-m-d')); ?>"><div class="row g-2"><div class="col-6"><label class="form-label">Check In</label><input class="form-control" type="time" name="check_in"></div><div class="col-6"><label class="form-label">Check Out</label><input class="form-control" type="time" name="check_out"></div></div><div class="row g-2 mt-1"><div class="col-6"><label class="form-label">Regular Hours</label><input class="form-control" type="number" step="0.01" name="regular_hours" value="8"></div><div class="col-6"><label class="form-label">Overtime</label><input class="form-control" type="number" step="0.01" name="overtime_hours" value="0"></div></div><label class="form-label mt-2">Status</label><select class="form-select mb-2" name="status"><option value="present">Present</option><option value="absent">Absent</option><option value="leave">Leave</option><option value="remote">Remote</option></select><label class="form-label">Notes</label><textarea class="form-control mb-3" name="notes" rows="3"></textarea><button class="btn btn-brand w-100">Save Attendance</button></form></div><div class="col-xl-8"><div class="card-admin p-3 mb-3"><form class="d-flex gap-2 align-items-end"><div><label class="form-label">From</label><input class="form-control" type="date" name="from" value="<?php echo esc($from); ?>"></div><div><label class="form-label">To</label><input class="form-control" type="date" name="to" value="<?php echo esc($to); ?>"></div><button class="btn btn-brand">Filter</button></form></div><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Date</th><th>Employee</th><th>In/Out</th><th>Hours</th><th>Overtime</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?php echo esc($row['work_date']); ?></td><td><strong><?php echo esc($row['employee_code']); ?></strong><div class="small text-secondary"><?php echo esc($row['first_name'].' '.$row['last_name']); ?></div></td><td><?php echo esc(($row['check_in']?:'—').' → '.($row['check_out']?:'—')); ?></td><td><?php echo number_format((float)$row['regular_hours'],2); ?></td><td><?php echo number_format((float)$row['overtime_hours'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($row['status'])); ?>"><?php echo esc($row['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="6" class="text-secondary">No attendance records found.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>