<?php
$pageTitle='BI Dashboard 2.0';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('bi_dashboard_2');
$pdo=getDB();
$metrics=biExecutiveMetrics($pdo);
$alerts=$pdo->query('SELECT e.*,r.rule_number,k.kpi_name FROM '.table('bi_kpi_alert_events').' e LEFT JOIN '.table('bi_kpi_alert_rules').' r ON r.id=e.bi_kpi_alert_rule_id LEFT JOIN '.table('report_kpis').' k ON k.id=r.report_kpi_id ORDER BY e.created_at DESC LIMIT 10')->fetchAll();
$presets=$pdo->query('SELECT * FROM '.table('bi_dashboard_filter_presets').' ORDER BY created_at DESC LIMIT 8')->fetchAll();
$kpis=$pdo->query('SELECT k.*,COALESCE(s.metric_value,0) latest_value,COALESCE(s.status,"new") snapshot_status FROM '.table('report_kpis').' k LEFT JOIN (SELECT ks1.* FROM '.table('kpi_snapshots').' ks1 INNER JOIN (SELECT report_kpi_id,MAX(snapshot_date) snapshot_date FROM '.table('kpi_snapshots').' GROUP BY report_kpi_id) x ON x.report_kpi_id=ks1.report_kpi_id AND x.snapshot_date=ks1.snapshot_date) s ON s.report_kpi_id=k.id WHERE k.active=1 ORDER BY k.sort_order,k.kpi_name LIMIT 20')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Executive Intelligence</div><h2 class="h4 mb-1">BI Dashboard 2.0</h2><p class="text-secondary mb-0">Cross-module KPIs for sales, finance, stock, service, payroll, procurement, and production.</p></div><div class="d-flex gap-2"><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/metric-library.php"><?php echo t('Metric Library', 'مكتبة المؤشرات'); ?></a><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/kpi-alerts.php"><?php echo t('KPI Alerts', 'تنبيهات مؤشرات الأداء'); ?></a></div></div>
<div class="row g-4 mb-4"><?php foreach($metrics as $key=>$value): ?><div class="col-md-3"><div class="card-admin p-4 h-100"><div class="erp-kicker"><?php echo esc(ucwords(str_replace('_',' ',$key))); ?></div><div class="metric-sm"><?php echo str_contains($key,'count')?number_format((float)$value,0):money($value); ?></div></div></div><?php endforeach; ?></div>
<div class="row g-4"><div class="col-xl-7"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">KPI Scorecard</h2><table class="table"><thead><tr><th>KPI</th><th>Group</th><th>Latest</th><th>Target</th><th>Status</th></tr></thead><tbody><?php foreach($kpis as $k): ?><tr><td><strong><?php echo esc($k['kpi_code']); ?></strong><div class="small text-secondary"><?php echo esc($k['kpi_name']); ?></div></td><td><?php echo esc($k['kpi_group']); ?></td><td><?php echo number_format((float)$k['latest_value'],2).' '.esc($k['unit_label']); ?></td><td><?php echo number_format((float)$k['target_value'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($k['snapshot_status'])); ?>"><?php echo esc($k['snapshot_status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-5"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Open KPI Alerts</h2><table class="table"><tbody><?php foreach($alerts as $a): ?><tr><td><strong><?php echo esc($a['rule_number'].' · '.$a['kpi_name']); ?></strong><div class="small text-secondary"><?php echo esc($a['event_message']); ?></div><span class="badge bg-<?php echo esc(statusTone($a['severity'])); ?>"><?php echo esc($a['severity']); ?></span></td></tr><?php endforeach; ?><?php if(!$alerts): ?><tr><td class="text-secondary">No alert events yet.</td></tr><?php endif; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Filter Presets</h2><table class="table"><tbody><?php foreach($presets as $p): ?><tr><td><strong><?php echo esc($p['preset_number']); ?></strong><div class="small text-secondary"><?php echo esc($p['preset_name'].' · '.$p['date_from'].' → '.$p['date_to']); ?></div></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>