<?php
$pageTitle='Bin Locations';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('bin_locations');
$pdo=getDB();
$warehouses=$pdo->query('SELECT w.*,b.branch_name FROM '.table('warehouses').' w LEFT JOIN '.table('branches').' b ON b.id=w.branch_id ORDER BY w.warehouse_name')->fetchAll();
$locations=$pdo->query('SELECT * FROM '.table('warehouse_locations').' ORDER BY location_code')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){try{createWarehouseBin($pdo,(int)$_POST['warehouse_id'],(int)$_POST['location_id'],trim((string)$_POST['bin_code']),trim((string)$_POST['bin_name']),trim((string)$_POST['bin_type']),max(0,(float)$_POST['capacity_qty']));flash('success','Bin created.');}catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'bin-locations']);flash('error',$e->getMessage());}redirect(ADMIN_URL.'/erp/bin-locations.php');}
$bins=$pdo->query('SELECT b.*,w.warehouse_name,l.location_code FROM '.table('warehouse_bins').' b LEFT JOIN '.table('warehouses').' w ON w.id=b.warehouse_id LEFT JOIN '.table('warehouse_locations').' l ON l.id=b.location_id ORDER BY w.warehouse_name,b.bin_code')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Storage Control</div><h2 class="h4 mb-1">Bin Locations</h2><p class="text-secondary mb-0">Create shelf/bin locations under warehouse zones for barcode picking and stock counts.</p></div></div><div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Create Bin</h2><label class="form-label">Warehouse</label><select class="form-select mb-2" name="warehouse_id"><?php foreach($warehouses as $w): ?><option value="<?php echo (int)$w['id']; ?>"><?php echo esc($w['warehouse_name']); ?></option><?php endforeach; ?></select><label class="form-label">Location / Zone</label><select class="form-select mb-2" name="location_id"><option value="0">No location</option><?php foreach($locations as $l): ?><option value="<?php echo (int)$l['id']; ?>"><?php echo esc($l['location_code'].' · '.$l['location_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="bin_code" placeholder="Auto or BIN-A1"><input class="form-control mb-2" name="bin_name" placeholder="Bin name"><select class="form-select mb-2" name="bin_type"><option value="storage">Storage</option><option value="pick_face">Pick Face</option><option value="receiving">Receiving</option><option value="dispatch">Dispatch</option></select><input class="form-control mb-3" type="number" step="0.0001" name="capacity_qty" placeholder="Capacity qty"><button class="btn btn-brand w-100">Create Bin</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Bin</th><th>Warehouse</th><th>Zone</th><th>Type</th><th>Capacity</th><th>Status</th></tr></thead><tbody><?php foreach($bins as $b): ?><tr><td><strong><?php echo esc($b['bin_code']); ?></strong><div class="small text-secondary"><?php echo esc($b['bin_name']); ?></div></td><td><?php echo esc($b['warehouse_name']); ?></td><td><?php echo esc($b['location_code']); ?></td><td><?php echo esc($b['bin_type']); ?></td><td><?php echo number_format((float)$b['capacity_qty'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($b['status'])); ?>"><?php echo esc($b['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>