<?php
$pageTitle='Budget Control';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('budget_control');
$pdo=getDB();$scope=operationalScope($pdo);
$costCenters=$pdo->query('SELECT * FROM '.table('cost_centers').' WHERE status="active" ORDER BY cost_center_code')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $cc=(int)($_POST['cost_center_id']??0);$year=max(2000,(int)($_POST['fiscal_year']??date('Y')));$month=max(0,min(12,(int)($_POST['period_month']??0)));$budget=max(0,(float)($_POST['budget_amount']??0));$committed=max(0,(float)($_POST['committed_amount']??0));
    if($cc<=0){throw new RuntimeException('Select cost center.');}
    $stmt=$pdo->prepare('INSERT INTO '.table('budget_periods').' (company_id,branch_id,cost_center_id,fiscal_year,period_month,budget_amount,committed_amount,actual_amount,variance_amount,status) VALUES (?,?,?,?,?,?,?,?,?,"open") ON DUPLICATE KEY UPDATE budget_amount=VALUES(budget_amount),committed_amount=VALUES(committed_amount),variance_amount=VALUES(variance_amount),status="open"');
    $stmt->execute([(int)$scope['company_id']?:null,(int)$scope['branch_id']?:null,$cc,$year,$month,$budget,$committed,0,round($budget-$committed,2)]);
    updateBudgetActuals($pdo,$cc,$year,$month);
    logActivity($pdo,'Budget','budget_saved','Budget saved for cost center #'.$cc.'.','budget_period',$cc);
    flash('success','Budget saved and actuals recalculated.');
  }catch(Throwable $e){flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/budget-control.php');
}
$rows=$pdo->query('SELECT bp.*,cc.cost_center_code,cc.cost_center_name FROM '.table('budget_periods').' bp LEFT JOIN '.table('cost_centers').' cc ON cc.id=bp.cost_center_id ORDER BY bp.fiscal_year DESC,bp.period_month DESC,cc.cost_center_code ASC LIMIT 300')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Budget Governance</div><h2 class="h4 mb-1">Budget Control</h2><p class="text-secondary mb-0">Set budgets by cost center and period, compare committed and actual costs, and review variance.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/cost-centers.php"><?php echo t('Cost Centers', 'مراكز التكلفة'); ?></a></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5">Budget Period</h2><label class="form-label">Cost Center</label><select class="form-select mb-2" name="cost_center_id" required><?php foreach($costCenters as $cc): ?><option value="<?php echo (int)$cc['id']; ?>"><?php echo esc($cc['cost_center_code'].' · '.$cc['cost_center_name']); ?></option><?php endforeach; ?></select><div class="row g-2"><div class="col-6"><label class="form-label">Year</label><input class="form-control" type="number" name="fiscal_year" value="<?php echo esc(date('Y')); ?>"></div><div class="col-6"><label class="form-label">Month</label><select class="form-select" name="period_month"><option value="0">Annual</option><?php for($m=1;$m<=12;$m++): ?><option value="<?php echo $m; ?>"><?php echo $m; ?></option><?php endfor; ?></select></div><div class="col-6"><label class="form-label">Budget</label><input class="form-control" type="number" step="0.01" name="budget_amount"></div><div class="col-6"><label class="form-label">Committed</label><input class="form-control" type="number" step="0.01" name="committed_amount"></div></div><button class="btn btn-brand w-100 mt-3">Save Budget</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Budget Register</div><h2 class="h5 mb-0">Budget vs Actual</h2></div></div><table class="table align-middle"><thead><tr><th>Cost Center</th><th>Period</th><th>Budget</th><th>Committed</th><th>Actual</th><th>Variance</th><th>Used</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $row): $used=(float)$row['budget_amount']>0?(((float)$row['committed_amount']+(float)$row['actual_amount'])/(float)$row['budget_amount']*100):0; ?><tr><td><strong><?php echo esc($row['cost_center_code']); ?></strong><div class="small text-secondary"><?php echo esc($row['cost_center_name']); ?></div></td><td><?php echo esc($row['fiscal_year'].' / '.($row['period_month']?:'Annual')); ?></td><td><?php echo money($row['budget_amount']); ?></td><td><?php echo money($row['committed_amount']); ?></td><td><?php echo money($row['actual_amount']); ?></td><td class="<?php echo (float)$row['variance_amount']>=0?'money-positive':'money-negative'; ?>"><?php echo money($row['variance_amount']); ?></td><td><?php echo number_format($used,1); ?>%</td><td><span class="badge bg-<?php echo $used>(float)setting('budget_warning_threshold_percent','80')?'warning text-dark':'success'; ?>"><?php echo esc($row['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>