<?php
$pageTitle='Commercial Packaging';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('commercial_packaging');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'package');
    if($action==='install'){p35InstallDefaults($pdo);flash('success','Commercial package defaults installed.');}
    elseif($action==='feature'){p35AddPackageFeature($pdo,(int)$_POST['commercial_package_id'],trim((string)$_POST['feature_group']),trim((string)$_POST['feature_name']),trim((string)$_POST['feature_description']),trim((string)$_POST['included_limit']),(int)$_POST['sort_order']);flash('success','Package feature added.');}
    else{p35CreateCommercialPackage($pdo,trim((string)$_POST['package_name']),trim((string)$_POST['package_type']),trim((string)$_POST['target_customer']),trim((string)$_POST['billing_cycle']),(float)$_POST['base_price'],trim((string)$_POST['currency']),(int)$_POST['implementation_days'],trim((string)$_POST['description']));flash('success','Commercial package created.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'commercial-packaging']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/commercial-packaging.php');
}
$packages=$pdo->query('SELECT * FROM '.table('commercial_packages').' ORDER BY base_price ASC,package_name')->fetchAll();
$features=$pdo->query('SELECT f.*,p.package_name FROM '.table('commercial_package_features').' f LEFT JOIN '.table('commercial_packages').' p ON p.id=f.commercial_package_id ORDER BY p.base_price,f.sort_order LIMIT 300')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Sellable Product Structure</div><h2 class="h4 mb-1">Commercial Packaging</h2><p class="text-secondary mb-0">Define packages, prices, target customer, implementation time and included features.</p></div><form method="post"><button name="action" value="install" class="btn btn-brand">Install Defaults</button></form></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4 mb-4"><h2 class="h5 mb-3">Create Package</h2><input class="form-control mb-2" name="package_name" placeholder="Professional ERP Package"><input class="form-control mb-2" name="package_type" value="license"><input class="form-control mb-2" name="target_customer" placeholder="Growing business"><select class="form-select mb-2" name="billing_cycle"><option>one_time</option><option>monthly</option><option>yearly</option></select><input class="form-control mb-2" type="number" step="0.01" name="base_price" value="7500"><input class="form-control mb-2" name="currency" value="<?php echo esc(setting('commercial_default_currency','AED')); ?>"><input class="form-control mb-2" type="number" name="implementation_days" value="<?php echo esc(setting('commercial_default_implementation_days','7')); ?>"><textarea class="form-control mb-3" name="description" rows="3"></textarea><button class="btn btn-outline-primary w-100">Create Package</button></form><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="feature"><h2 class="h5 mb-3">Add Feature</h2><select class="form-select mb-2" name="commercial_package_id"><?php foreach($packages as $p): ?><option value="<?php echo (int)$p['id']; ?>"><?php echo esc($p['package_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="feature_group" placeholder="ERP"><input class="form-control mb-2" name="feature_name" placeholder="Inventory + Finance"><textarea class="form-control mb-2" name="feature_description" rows="2"></textarea><input class="form-control mb-2" name="included_limit" placeholder="Included"><input class="form-control mb-3" type="number" name="sort_order" value="10"><button class="btn btn-brand w-100">Add Feature</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Packages</h2><table class="table"><thead><tr><th>Package</th><th>Target</th><th>Price</th><th>Implementation</th></tr></thead><tbody><?php foreach($packages as $p): ?><tr><td><strong><?php echo esc($p['package_number']); ?></strong><div class="small text-secondary"><?php echo esc($p['package_name'].' · '.$p['description']); ?></div></td><td><?php echo esc($p['target_customer']); ?></td><td><?php echo esc($p['currency']); ?> <?php echo number_format((float)$p['base_price'],2); ?></td><td><?php echo (int)$p['implementation_days']; ?> days</td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Package Features</h2><table class="table"><tbody><?php foreach($features as $f): ?><tr><td><strong><?php echo esc($f['package_name']); ?></strong><div class="small text-secondary"><?php echo esc($f['feature_group'].' · '.$f['feature_name'].' · '.$f['included_limit']); ?></div></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>