<?php
$pageTitle='Companies';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('org_structure');
$pdo=getDB();
$editId=(int)($_GET['edit']??0);
$edit=null;
if($editId){$stmt=$pdo->prepare('SELECT * FROM '.table('companies').' WHERE id=? LIMIT 1');$stmt->execute([$editId]);$edit=$stmt->fetch()?:null;}
if($_SERVER['REQUEST_METHOD']==='POST'){
  $id=(int)($_POST['id']??0);$code=trim((string)($_POST['company_code']??''));$name=trim((string)($_POST['company_name']??''));
  if($code===''||$name===''){flash('error','Company code and name are required.');redirect(ADMIN_URL.'/erp/companies.php'.($id?'?edit='.$id:''));}
  if($id){
    $stmt=$pdo->prepare('UPDATE '.table('companies').' SET company_code=?,company_name=?,legal_name=?,tax_number=?,email=?,phone=?,currency=?,timezone=?,address=?,status=?,is_default=? WHERE id=?');
    $stmt->execute([$code,$name,trim((string)($_POST['legal_name']??'')),trim((string)($_POST['tax_number']??'')),trim((string)($_POST['email']??'')),trim((string)($_POST['phone']??'')),trim((string)($_POST['currency']??CURRENCY)),trim((string)($_POST['timezone']??TIMEZONE)),trim((string)($_POST['address']??'')),trim((string)($_POST['status']??'active')),!empty($_POST['is_default'])?1:0,$id]);
    logActivity($pdo,'Organization','company_updated','Company '.$code.' updated.','company',$id);flash('success','Company updated.');
  }else{
    $stmt=$pdo->prepare('INSERT INTO '.table('companies').' (company_code,company_name,legal_name,tax_number,email,phone,currency,timezone,address,status,is_default) VALUES (?,?,?,?,?,?,?,?,?,?,?)');
    $stmt->execute([$code,$name,trim((string)($_POST['legal_name']??'')),trim((string)($_POST['tax_number']??'')),trim((string)($_POST['email']??'')),trim((string)($_POST['phone']??'')),trim((string)($_POST['currency']??CURRENCY)),trim((string)($_POST['timezone']??TIMEZONE)),trim((string)($_POST['address']??'')),trim((string)($_POST['status']??'active')),!empty($_POST['is_default'])?1:0]);
    $id=(int)$pdo->lastInsertId();logActivity($pdo,'Organization','company_created','Company '.$code.' created.','company',$id);flash('success','Company created.');
  }
  if(!empty($_POST['is_default'])){$pdo->prepare('UPDATE '.table('companies').' SET is_default=CASE WHEN id=? THEN 1 ELSE 0 END')->execute([$id]);}
  redirect(ADMIN_URL.'/erp/companies.php');
}
$rows=$pdo->query('SELECT c.*,(SELECT COUNT(*) FROM '.table('branches').' b WHERE b.company_id=c.id) branch_count,(SELECT COUNT(*) FROM '.table('warehouses').' w WHERE w.company_id=c.id) warehouse_count FROM '.table('companies').' c ORDER BY c.is_default DESC,c.company_name ASC')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="row g-4">
<div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="id" value="<?php echo (int)($edit['id']??0); ?>"><div class="erp-kicker">Corporate Structure</div><h2 class="h5 mb-3"><?php echo $edit?'Edit Company':'Create Company'; ?></h2><div class="row g-3"><div class="col-md-5"><label class="form-label">Code</label><input class="form-control" name="company_code" value="<?php echo esc($edit['company_code']??''); ?>" required></div><div class="col-md-7"><label class="form-label">Name</label><input class="form-control" name="company_name" value="<?php echo esc($edit['company_name']??''); ?>" required></div><div class="col-12"><label class="form-label">Legal Name</label><input class="form-control" name="legal_name" value="<?php echo esc($edit['legal_name']??''); ?>"></div><div class="col-md-6"><label class="form-label">Tax No.</label><input class="form-control" name="tax_number" value="<?php echo esc($edit['tax_number']??''); ?>"></div><div class="col-md-6"><label class="form-label">Currency</label><input class="form-control" name="currency" value="<?php echo esc($edit['currency']??CURRENCY); ?>"></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" name="email" value="<?php echo esc($edit['email']??''); ?>"></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" name="phone" value="<?php echo esc($edit['phone']??''); ?>"></div><div class="col-12"><label class="form-label">Timezone</label><input class="form-control" name="timezone" value="<?php echo esc($edit['timezone']??TIMEZONE); ?>"></div><div class="col-12"><label class="form-label">Address</label><textarea class="form-control" name="address" rows="2"><?php echo esc($edit['address']??''); ?></textarea></div><div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><option value="active" <?php echo (($edit['status']??'active')==='active')?'selected':''; ?>>Active</option><option value="inactive" <?php echo (($edit['status']??'active')==='inactive')?'selected':''; ?>>Inactive</option></select></div><div class="col-md-6 d-flex align-items-end"><label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_default" value="1" <?php echo !empty($edit['is_default'])?'checked':''; ?>><span class="form-check-label">Default</span></label></div></div><div class="mt-3 d-flex gap-2"><button class="btn btn-brand"><?php echo $edit?'Save':'Create'; ?></button><?php if($edit): ?><a class="btn btn-outline-secondary" href="<?php echo esc(ADMIN_URL); ?>/erp/companies.php">Cancel</a><?php endif; ?></div></form></div>
<div class="col-xl-8"><div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker"><?php echo t('Organization', 'الهيكل التنظيمي'); ?></div><h2 class="h5 mb-0">Companies</h2></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/branches.php"><?php echo t('Branches', 'الفروع'); ?></a><a class="btn btn-outline-dark" href="<?php echo esc(ADMIN_URL); ?>/erp/warehouses.php"><?php echo t('Warehouses', 'المخازن'); ?></a></div></div><table class="table align-middle"><thead><tr><th>Company</th><th>Tax / Currency</th><th>Branches</th><th>Warehouses</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?php echo esc($row['company_code'].' · '.$row['company_name']); ?></strong><div class="small text-secondary"><?php echo esc($row['legal_name']); ?></div></td><td><?php echo esc($row['tax_number']?:'—'); ?><div class="small text-secondary"><?php echo esc($row['currency']); ?></div></td><td><?php echo (int)$row['branch_count']; ?></td><td><?php echo (int)$row['warehouse_count']; ?></td><td><span class="badge bg-<?php echo $row['status']==='active'?'success':'secondary'; ?>"><?php echo esc($row['status']); ?></span><?php if(!empty($row['is_default'])): ?><span class="badge bg-primary">Default</span><?php endif; ?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="?edit=<?php echo (int)$row['id']; ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div></div>
</div>
<?php include dirname(__DIR__).'/footer.php'; ?>