<?php
$pageTitle='Company Consolidated Dashboard';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('reports');
$pdo=getDB();
$scopeOptions=scopeSelectOptions($pdo);
$defaultScope=operationalScope($pdo);
$companyId=(int)($_GET['company_id']??$defaultScope['company_id']);
if($companyId>0 && !scopeAllowed($pdo,$companyId,0,0,false)){flash('error','You do not have access to that company dashboard.');redirect(ADMIN_URL.'/erp/dashboard.php');}
$companyStmt=$pdo->prepare('SELECT * FROM '.table('companies').' WHERE id=? LIMIT 1');$companyStmt->execute([$companyId]);$company=$companyStmt->fetch();
if(!$company){flash('error','Company not found.');redirect(ADMIN_URL.'/erp/dashboard.php');}
$branchCountStmt=$pdo->prepare('SELECT COUNT(*) FROM '.table('branches').' WHERE company_id=?');$branchCountStmt->execute([$companyId]);$branchCount=(int)$branchCountStmt->fetchColumn();
$warehouseCountStmt=$pdo->prepare('SELECT COUNT(*) FROM '.table('warehouses').' WHERE company_id=?');$warehouseCountStmt->execute([$companyId]);$warehouseCount=(int)$warehouseCountStmt->fetchColumn();
$invoiceStmt=$pdo->prepare('SELECT COALESCE(SUM(total),0),COALESCE(SUM(balance_due),0) FROM '.table('invoices').' WHERE company_id=? AND status<>"cancelled"');$invoiceStmt->execute([$companyId]);[$invoiceTotal,$arBalance]=$invoiceStmt->fetch(PDO::FETCH_NUM);
$orderStmt=$pdo->prepare('SELECT COUNT(*),COALESCE(SUM(total),0) FROM '.table('orders').' WHERE company_id=?');$orderStmt->execute([$companyId]);[$orderCount,$orderTotal]=$orderStmt->fetch(PDO::FETCH_NUM);
$poStmt=$pdo->prepare('SELECT COALESCE(SUM(total),0) FROM '.table('purchase_orders').' WHERE company_id=? AND status<>"cancelled"');$poStmt->execute([$companyId]);$poTotal=(float)$poStmt->fetchColumn();
$apStmt=$pdo->prepare('SELECT COALESCE(SUM(balance_due),0) FROM '.table('expenses').' WHERE company_id=?');$apStmt->execute([$companyId]);$apBalance=(float)$apStmt->fetchColumn();
$stockStmt=$pdo->prepare('SELECT COALESCE(SUM(ws.quantity),0),COALESCE(SUM(ws.stock_value),0) FROM '.table('warehouse_stock').' ws WHERE ws.company_id=?');$stockStmt->execute([$companyId]);[$stockUnits,$stockValue]=$stockStmt->fetch(PDO::FETCH_NUM);
$transferStmt=$pdo->prepare('SELECT COUNT(*) FROM '.table('stock_transfers').' WHERE (from_company_id=? OR to_company_id=?) AND status IN ("pending_approval","approved","dispatched")');$transferStmt->execute([$companyId,$companyId]);$openTransfers=(int)$transferStmt->fetchColumn();

$branchStmt=$pdo->prepare('SELECT b.id,b.branch_code,b.branch_name,
COALESCE((SELECT SUM(total) FROM '.table('invoices').' i WHERE i.branch_id=b.id AND i.status<>"cancelled"),0) invoice_total,
COALESCE((SELECT SUM(total) FROM '.table('purchase_orders').' po WHERE po.branch_id=b.id AND po.status<>"cancelled"),0) po_total,
COALESCE((SELECT SUM(ws.quantity) FROM '.table('warehouse_stock').' ws WHERE ws.branch_id=b.id),0) stock_units,
COALESCE((SELECT COUNT(*) FROM '.table('orders').' o WHERE o.branch_id=b.id),0) order_count
FROM '.table('branches').' b WHERE b.company_id=? ORDER BY b.branch_name');
$branchStmt->execute([$companyId]);$branches=$branchStmt->fetchAll();

$recentTransfers=$pdo->prepare('SELECT t.*,fb.branch_name from_branch_name,tb.branch_name to_branch_name FROM '.table('stock_transfers').' t LEFT JOIN '.table('branches').' fb ON fb.id=t.from_branch_id LEFT JOIN '.table('branches').' tb ON tb.id=t.to_branch_id WHERE t.from_company_id=? OR t.to_company_id=? ORDER BY t.created_at DESC,t.id DESC LIMIT 8');
$recentTransfers->execute([$companyId,$companyId]);$transferRows=$recentTransfers->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Consolidated Company Dashboard</div><h2 class="h4 mb-1"><?php echo esc($company['company_name']); ?></h2><p class="text-secondary mb-0">Company-wide operational visibility across branches, warehouses, sales, purchases, and transfers.</p></div><div class="d-flex flex-wrap gap-2 align-items-end"><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/branch-financial-consolidation.php?company_id=<?php echo (int)$companyId; ?>"><?php echo t('Financial Consolidation', 'التجميع المالي'); ?></a><a class="btn btn-outline-dark" href="<?php echo esc(ADMIN_URL); ?>/erp/intercompany-transactions.php"><?php echo t('Intercompany', 'بين الشركات'); ?></a><form class="d-flex gap-2 align-items-end"><div><label class="form-label">Company</label><select class="form-select" name="company_id"><?php foreach($scopeOptions['companies'] as $option): ?><option value="<?php echo (int)$option['id']; ?>" <?php echo (int)$option['id']===$companyId?'selected':''; ?>><?php echo esc($option['company_code'].' · '.$option['company_name']); ?></option><?php endforeach; ?></select></div><button class="btn btn-brand">Load</button></form></div></div>
<div class="row g-4 mb-4"><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker"><?php echo t('Branches', 'الفروع'); ?></div><div class="metric"><?php echo $branchCount; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker"><?php echo t('Warehouses', 'المخازن'); ?></div><div class="metric"><?php echo $warehouseCount; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Website Orders</div><div class="metric"><?php echo (int)$orderCount; ?></div><div class="small text-secondary"><?php echo money($orderTotal); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Open Transfers</div><div class="metric"><?php echo $openTransfers; ?></div></div></div></div>
<div class="row g-4 mb-4"><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Invoice Revenue</div><div class="metric-sm"><?php echo money($invoiceTotal); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">AR Balance</div><div class="metric-sm money-negative"><?php echo money($arBalance); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">PO Value</div><div class="metric-sm"><?php echo money($poTotal); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">AP Balance</div><div class="metric-sm money-negative"><?php echo money($apBalance); ?></div></div></div></div>
<div class="row g-4">
<div class="col-xl-8"><div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Branch Consolidation</div><h2 class="h5 mb-0">Branch Operating Summary</h2></div></div><table class="table align-middle"><thead><tr><th>Branch</th><th>Invoice Revenue</th><th>PO Value</th><th>Orders</th><th>Stock Units</th></tr></thead><tbody><?php foreach($branches as $branch): ?><tr><td><strong><?php echo esc($branch['branch_code'].' · '.$branch['branch_name']); ?></strong></td><td><?php echo money($branch['invoice_total']); ?></td><td><?php echo money($branch['po_total']); ?></td><td><?php echo (int)$branch['order_count']; ?></td><td><?php echo number_format((float)$branch['stock_units'],2); ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="col-xl-4"><div class="card-admin p-4 mb-4"><div class="erp-kicker">Inventory Value</div><div class="metric-sm"><?php echo money($stockValue); ?></div><div class="small text-secondary"><?php echo number_format((float)$stockUnits,2); ?> units across company warehouses.</div></div><div class="table-wrap table-responsive"><h3 class="h5 mb-3">Recent Transfers</h3><table class="table"><tbody><?php foreach($transferRows as $transfer): ?><tr><td><a href="<?php echo esc(ADMIN_URL); ?>/erp/view-stock-transfer.php?id=<?php echo (int)$transfer['id']; ?>"><?php echo esc($transfer['transfer_number']); ?></a><div class="small text-secondary"><?php echo esc(($transfer['from_branch_name']?:'—').' → '.($transfer['to_branch_name']?:'—')); ?></div></td><td class="text-end"><span class="badge bg-<?php echo esc(statusTone($transfer['status'])); ?>"><?php echo esc(str_replace('_',' ',ucwords($transfer['status'],'_'))); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div>
</div>
<?php include dirname(__DIR__).'/footer.php'; ?>