<?php
$pageTitle='Compliance Checklists';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('compliance_checklists');
$pdo=getDB();$user=currentUser();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'checklist');
    if($action==='item'){$pdo->prepare('INSERT INTO '.table('compliance_checklist_items').' (compliance_checklist_id,item_title,item_description,require_evidence,status) VALUES (?,?,?,?, "pending")')->execute([(int)$_POST['checklist_id'],trim((string)$_POST['item_title']),trim((string)$_POST['item_description']),(int)($_POST['require_evidence']??0)]);flash('success','Compliance item added.');}
    elseif($action==='complete'){$pdo->prepare('UPDATE '.table('compliance_checklist_items').' SET status="completed",completed_by=?,completed_at=NOW() WHERE id=?')->execute([(int)($user['id']??0)?:null,(int)$_POST['id']]);flash('success','Compliance item completed.');}
    else{$number=nextScopedDocumentNumber($pdo,'compliance_checklist',setting('compliance_checklist_prefix','COMP'),operationalScope($pdo));$pdo->prepare('INSERT INTO '.table('compliance_checklists').' (checklist_number,checklist_name,compliance_area,status,owner_user_id,due_date,created_by) VALUES (?,?,?,?,?,?,?)')->execute([$number,trim((string)$_POST['checklist_name']),trim((string)$_POST['compliance_area']),'active',(int)($_POST['owner_user_id']??0)?:null,trim((string)$_POST['due_date'])?:null,(int)($user['id']??0)?:null]);flash('success','Compliance checklist created.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'compliance-checklists']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/compliance-checklists.php');
}
$checklists=$pdo->query('SELECT * FROM '.table('compliance_checklists').' ORDER BY created_at DESC LIMIT 100')->fetchAll();
$items=$pdo->query('SELECT i.*,c.checklist_number,c.checklist_name FROM '.table('compliance_checklist_items').' i LEFT JOIN '.table('compliance_checklists').' c ON c.id=i.compliance_checklist_id ORDER BY FIELD(i.status,"pending","completed"),i.created_at DESC LIMIT 250')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Compliance Evidence</div><h2 class="h4 mb-1">Compliance Checklists</h2><p class="text-secondary mb-0">Track internal control checklists, evidence requirements and completion status.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4 mb-4"><h2 class="h5 mb-3">Create Checklist</h2><input class="form-control mb-2" name="checklist_name" placeholder="Monthly access review"><input class="form-control mb-2" name="compliance_area" placeholder="Security / Finance / HR"><input class="form-control mb-2" type="number" name="owner_user_id" placeholder="Owner user ID"><input class="form-control mb-3" type="date" name="due_date"><button class="btn btn-brand w-100">Create Checklist</button></form><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="item"><h2 class="h5 mb-3">Add Item</h2><select class="form-select mb-2" name="checklist_id"><?php foreach($checklists as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo esc($c['checklist_number'].' · '.$c['checklist_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="item_title" placeholder="Review admin users"><textarea class="form-control mb-2" name="item_description" rows="3"></textarea><select class="form-select mb-3" name="require_evidence"><option value="0">No evidence required</option><option value="1">Evidence required</option></select><button class="btn btn-outline-primary w-100">Add Item</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Checklist</th><th>Item</th><th>Evidence</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($items as $i): ?><tr><td><strong><?php echo esc($i['checklist_number']); ?></strong><div class="small text-secondary"><?php echo esc($i['checklist_name']); ?></div></td><td><?php echo esc($i['item_title']); ?><div class="small text-secondary"><?php echo esc($i['item_description']); ?></div></td><td><?php echo $i['require_evidence']?'Required':'Not required'; ?></td><td><span class="badge bg-<?php echo esc(statusTone($i['status'])); ?>"><?php echo esc($i['status']); ?></span></td><td><?php if($i['status']!=='completed'): ?><form method="post"><input type="hidden" name="action" value="complete"><input type="hidden" name="id" value="<?php echo (int)$i['id']; ?>"><button class="btn btn-sm btn-success">Complete</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>