<?php
$pageTitle='Customer Statement';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('accounting');
$pdo=getDB();
$id=(int)($_GET['id']??0);
$stmt=$pdo->prepare('SELECT * FROM ' . table('customers') . ' WHERE id=? LIMIT 1');$stmt->execute([$id]);$customer=$stmt->fetch();
if(!$customer){flash('error','Customer not found.');redirect(ADMIN_URL.'/erp/ar-customer-ledger.php');}
$entries=[];
$stmt=$pdo->prepare('SELECT id,invoice_number doc_number,total amount,COALESCE(due_date,DATE(created_at)) doc_date,status FROM ' . table('invoices') . ' WHERE customer_id=? AND status<>"cancelled"');$stmt->execute([$id]);foreach($stmt->fetchAll() as $row){$entries[]=['date'=>$row['doc_date'],'type'=>'Invoice','doc'=>$row['doc_number'],'debit'=>(float)$row['amount'],'credit'=>0,'link'=>ADMIN_URL.'/erp/view-invoice.php?id='.(int)$row['id'],'status'=>$row['status']];}
$stmt=$pdo->prepare('SELECT id,payment_number doc_number,amount,DATE(COALESCE(paid_at,created_at)) doc_date,status FROM ' . table('payments') . ' WHERE customer_id=? AND status="received"');$stmt->execute([$id]);foreach($stmt->fetchAll() as $row){$entries[]=['date'=>$row['doc_date'],'type'=>'Payment','doc'=>$row['doc_number'],'debit'=>0,'credit'=>(float)$row['amount'],'link'=>ADMIN_URL.'/erp/finance.php','status'=>$row['status']];}
$stmt=$pdo->prepare('SELECT id,credit_note_number doc_number,total,issue_date doc_date,status FROM ' . table('credit_notes') . ' WHERE customer_id=? AND status="approved"');$stmt->execute([$id]);foreach($stmt->fetchAll() as $row){$entries[]=['date'=>$row['doc_date'],'type'=>'Credit Note','doc'=>$row['doc_number'],'debit'=>0,'credit'=>(float)$row['total'],'link'=>ADMIN_URL.'/erp/view-credit-note.php?id='.(int)$row['id'],'status'=>$row['status']];}
usort($entries,fn($a,$b)=>strcmp((string)$a['date'].'-'.$a['type'],(string)$b['date'].'-'.$b['type']));
$running=0;$debits=0;$credits=0;foreach($entries as &$entry){$debits+=$entry['debit'];$credits+=$entry['credit'];$running+=$entry['debit']-$entry['credit'];$entry['balance']=$running;}unset($entry);
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><div class="erp-kicker">Customer Statement</div><h2 class="h4 mb-1"><?php echo esc($customer['customer_code'].' · '.($customer['company_name'] ?: $customer['contact_name'])); ?></h2><p class="text-secondary mb-0"><?php echo esc($customer['email'].' · '.$customer['phone']); ?></p></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-dark" href="<?php echo esc(ADMIN_URL); ?>/erp/ar-customer-ledger.php">Back to AR Ledger</a><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/create-credit-note.php?customer_id=<?php echo (int)$customer['id']; ?>">Create Credit Note</a></div></div>
<div class="row g-4 mb-4"><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Invoices</div><div class="metric-sm"><?php echo money($debits); ?></div></div></div><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Payments + Credits</div><div class="metric-sm"><?php echo money($credits); ?></div></div></div><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Closing AR</div><div class="metric-sm <?php echo $running>0?'money-negative':'money-positive'; ?>"><?php echo money($running); ?></div></div></div></div>
<div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Date</th><th>Type</th><th>Document</th><th>Debit</th><th>Credit</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach($entries as $entry): ?><tr><td><?php echo esc($entry['date']); ?></td><td><?php echo esc($entry['type']); ?></td><td><a href="<?php echo esc($entry['link']); ?>"><?php echo esc($entry['doc']); ?></a></td><td><?php echo money($entry['debit']); ?></td><td><?php echo money($entry['credit']); ?></td><td><?php echo money($entry['balance']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($entry['status'])); ?>"><?php echo esc($entry['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$entries): ?><tr><td colspan="7" class="text-secondary">No customer statement entries found.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>