<?php
$pageTitle='Customer Price Rules';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('customer_price_rules');
$pdo=getDB();$customers=$pdo->query('SELECT id,customer_code,company_name,contact_name,customer_type FROM '.table('customers').' ORDER BY created_at DESC LIMIT 500')->fetchAll();$products=$pdo->query('SELECT id,sku,name,price FROM '.table('products').' WHERE active=1 ORDER BY name LIMIT 500')->fetchAll();$categories=$pdo->query('SELECT id,name FROM '.table('categories').' ORDER BY name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){try{ecom33CreateCustomerPriceRule($pdo,$_POST);flash('success','Customer price rule created.');}catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'customer-price-rules']);flash('error',$e->getMessage());}redirect(ADMIN_URL.'/erp/customer-price-rules.php');}
$rows=$pdo->query('SELECT r.*,c.customer_code,c.company_name,p.name product_name,cat.name category_name FROM '.table('customer_price_rules').' r LEFT JOIN '.table('customers').' c ON c.id=r.customer_id LEFT JOIN '.table('products').' p ON p.id=r.product_id LEFT JOIN '.table('categories').' cat ON cat.id=r.category_id ORDER BY r.priority DESC,r.created_at DESC LIMIT 300')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Personalized Commerce Pricing</div><h2 class="h4 mb-1">Customer Price Rules</h2><p class="text-secondary mb-0">Create customer, customer-type, product or category-specific discounts and fixed-price rules.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Create Rule</h2><select class="form-select mb-2" name="customer_id"><option value="">Any customer</option><?php foreach($customers as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo esc($c['customer_code'].' · '.($c['company_name']?:$c['contact_name'])); ?></option><?php endforeach; ?></select><select class="form-select mb-2" name="customer_type"><option value="">Any type</option><option>b2b</option><option>b2c</option><option>dealer</option><option>reseller</option></select><input class="form-control mb-2" name="customer_group" placeholder="Group optional"><select class="form-select mb-2" name="product_id"><option value="">Any product</option><?php foreach($products as $p): ?><option value="<?php echo (int)$p['id']; ?>"><?php echo esc($p['sku'].' · '.$p['name']); ?></option><?php endforeach; ?></select><select class="form-select mb-2" name="category_id"><option value="">Any category</option><?php foreach($categories as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo esc($c['name']); ?></option><?php endforeach; ?></select><select class="form-select mb-2" name="rule_type"><option>percent_discount</option><option>amount_discount</option><option>fixed_price</option></select><input class="form-control mb-2" type="number" step="0.01" name="rule_value" placeholder="Value"><input class="form-control mb-2" type="number" step="0.01" name="min_quantity" value="1"><input class="form-control mb-2" type="number" name="priority" value="50"><div class="row g-2"><div class="col-6"><input class="form-control" type="date" name="valid_from"></div><div class="col-6"><input class="form-control" type="date" name="valid_to"></div></div><select class="form-select my-2" name="status"><option>active</option><option>inactive</option></select><textarea class="form-control mb-3" name="notes" rows="3"></textarea><button class="btn btn-brand w-100">Create Rule</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><table class="table"><thead><tr><th>Rule</th><th>Customer</th><th>Product/Category</th><th>Type</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?php echo esc($r['rule_number']); ?></strong><div class="small text-secondary">Priority <?php echo (int)$r['priority']; ?> · Min qty <?php echo esc($r['min_quantity']); ?></div></td><td><?php echo esc($r['customer_code']?:$r['customer_type']?:'Any'); ?><div class="small text-secondary"><?php echo esc($r['company_name']?:$r['customer_group']); ?></div></td><td><?php echo esc($r['product_name']?:$r['category_name']?:'Any'); ?></td><td><?php echo esc($r['rule_type']); ?> · <?php echo esc($r['rule_value']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>