<?php
$pageTitle='Decision Engine 2.0';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('decision_engine_2');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'resolve');
    if($action==='recommend'){$id=createAiDecisionRecommendation($pdo,trim((string)$_POST['source_type']),(int)($_POST['source_id']??0)?:null,trim((string)$_POST['module']),trim((string)$_POST['recommendation_title']),trim((string)$_POST['recommendation_text']),max(0,(float)$_POST['confidence_score']),max(0,(float)$_POST['impact_score']),max(0,(float)$_POST['effort_score']),trim((string)$_POST['priority']));flash('success','Recommendation created #'.$id);}
    else{$pdo->prepare('UPDATE '.table('ai_decision_recommendations').' SET status=?,closed_at=CASE WHEN ? IN ("accepted","rejected","done") THEN NOW() ELSE closed_at END WHERE id=?')->execute([trim((string)$_POST['status']),trim((string)$_POST['status']),(int)$_POST['id']]);flash('success','Recommendation updated.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'decision-engine-2']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/decision-engine-2.php');
}
$rows=$pdo->query('SELECT * FROM '.table('ai_decision_recommendations').' ORDER BY FIELD(status,"open","accepted","done","rejected"),priority DESC,confidence_score DESC,created_at DESC LIMIT 200')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Decision Intelligence</div><h2 class="h4 mb-1">Decision Engine 2.0</h2><p class="text-secondary mb-0">Prioritize AI recommendations by confidence, impact, effort, and operational module.</p></div><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/ai-automation-dashboard.php">Run Engine</a></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="recommend"><h2 class="h5 mb-3">Manual Recommendation</h2><input class="form-control mb-2" name="source_type" placeholder="invoice / product / lead"><input class="form-control mb-2" type="number" name="source_id" placeholder="Source ID"><input class="form-control mb-2" name="module" placeholder="Finance / Sales / Inventory"><input class="form-control mb-2" name="recommendation_title" placeholder="Title"><textarea class="form-control mb-2" name="recommendation_text" rows="4" placeholder="Recommendation"></textarea><div class="row g-2"><div class="col-4"><input class="form-control" type="number" step="0.01" name="confidence_score" placeholder="Conf"></div><div class="col-4"><input class="form-control" type="number" step="0.01" name="impact_score" placeholder="Impact"></div><div class="col-4"><input class="form-control" type="number" step="0.01" name="effort_score" placeholder="Effort"></div></div><select class="form-select my-3" name="priority"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select><button class="btn btn-brand w-100">Create</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Recommendation</th><th>Module</th><th>Score</th><th>Priority</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?php echo esc($r['recommendation_number']); ?></strong><div><?php echo esc($r['recommendation_title']); ?></div><div class="small text-secondary"><?php echo esc($r['recommendation_text']); ?></div></td><td><?php echo esc($r['module']); ?></td><td><div class="small">Confidence <?php echo number_format((float)$r['confidence_score'],0); ?></div><div class="small">Impact <?php echo number_format((float)$r['impact_score'],0); ?> / Effort <?php echo number_format((float)$r['effort_score'],0); ?></div></td><td><span class="badge bg-<?php echo esc(statusTone($r['priority'])); ?>"><?php echo esc($r['priority']); ?></span></td><td><form method="post" class="d-flex gap-1"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><select class="form-select form-select-sm" name="status"><option <?php echo $r['status']==='open'?'selected':''; ?>>open</option><option <?php echo $r['status']==='accepted'?'selected':''; ?>>accepted</option><option <?php echo $r['status']==='done'?'selected':''; ?>>done</option><option <?php echo $r['status']==='rejected'?'selected':''; ?>>rejected</option></select><button class="btn btn-sm btn-outline-primary">Save</button></form></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>