<?php
$pageTitle='Delivery Notes';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('delivery_notes');
$pdo=getDB();
$scopeOptions=scopeSelectOptions($pdo);
$filters=requestScopeFilters();
$status=trim((string)($_GET['status']??''));

$params=[];$where='';
if($status!==''){$where=' WHERE dn.status=?';$params[]=$status;}
$condition=selectedScopeCondition('dn',$params,$filters,['company_id','branch_id','warehouse_id']);$condition.=scopeQueryCondition($pdo,'dn',$params,false);
if($where===''){$where=$condition!==''?' WHERE '.substr($condition,5):'';}else{$where.=$condition;}
$stmt=$pdo->prepare('SELECT dn.*,so.sales_order_number,i.invoice_number,u1.email dispatched_email,u2.email delivered_email FROM '.table('delivery_notes').' dn LEFT JOIN '.table('sales_orders').' so ON so.id=dn.sales_order_id LEFT JOIN '.table('invoices').' i ON i.id=dn.invoice_id LEFT JOIN '.table('users').' u1 ON u1.id=dn.dispatched_by LEFT JOIN '.table('users').' u2 ON u2.id=dn.delivered_by'.$where.' ORDER BY dn.created_at DESC,dn.id DESC LIMIT 250');
$stmt->execute($params);$rows=$stmt->fetchAll();
$summary=['draft'=>0,'dispatched'=>0,'delivered'=>0,'cancelled'=>0];foreach($rows as $row){$k=(string)($row['status']??'');if(isset($summary[$k])){$summary[$k]++;}}
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Fulfillment Control</div><h2 class="h4 mb-1">Delivery Notes</h2><p class="text-secondary mb-0">Track dispatch and completion of approved sales order deliveries.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/sales-orders.php"><?php echo t('Sales Orders', 'أوامر البيع'); ?></a></div>
<div class="row g-4 mb-4"><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Draft</div><div class="metric-sm"><?php echo (int)$summary['draft']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Dispatched</div><div class="metric-sm"><?php echo (int)$summary['dispatched']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Delivered</div><div class="metric-sm money-positive"><?php echo (int)$summary['delivered']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Cancelled</div><div class="metric-sm money-negative"><?php echo (int)$summary['cancelled']; ?></div></div></div></div>
<div class="card-admin p-3 mb-4"><form class="d-flex flex-wrap gap-2 align-items-end"><div><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option><?php foreach(['draft','dispatched','delivered','cancelled'] as $filter): ?><option value="<?php echo esc($filter); ?>" <?php echo $status===$filter?'selected':''; ?>><?php echo esc(ucfirst($filter)); ?></option><?php endforeach; ?></select></div><div><label class="form-label">Company</label><select class="form-select" name="company_id"><option value="0">All</option><?php foreach($scopeOptions['companies'] as $company): ?><option value="<?php echo (int)$company['id']; ?>" <?php echo (int)$filters['company_id']===(int)$company['id']?'selected':''; ?>><?php echo esc($company['company_code'].' · '.$company['company_name']); ?></option><?php endforeach; ?></select></div><div><label class="form-label">Branch</label><select class="form-select" name="branch_id"><option value="0">All</option><?php foreach($scopeOptions['branches'] as $branch): ?><option value="<?php echo (int)$branch['id']; ?>" <?php echo (int)$filters['branch_id']===(int)$branch['id']?'selected':''; ?>><?php echo esc($branch['branch_code'].' · '.$branch['branch_name']); ?></option><?php endforeach; ?></select></div><button class="btn btn-brand">Apply</button></form></div>
<div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Fulfillment Register</div><h2 class="h5 mb-0">Delivery Note Pipeline</h2></div></div><table class="table align-middle"><thead><tr><th>Delivery</th><th>Sales Order</th><th>Invoice</th><th>Customer</th><th>Date</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?php echo esc($row['delivery_number']); ?></strong></td><td><?php echo esc($row['sales_order_number']?:'—'); ?></td><td><?php echo esc($row['invoice_number']?:'—'); ?></td><td><?php echo esc($row['customer_name']?:'—'); ?></td><td><?php echo esc($row['delivery_date']?:'—'); ?></td><td><span class="badge bg-<?php echo esc(statusTone($row['status'])); ?>"><?php echo esc(ucfirst($row['status'])); ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/view-delivery-note.php?id=<?php echo (int)$row['id']; ?>">Open</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="7" class="text-secondary">No delivery notes found.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>