<?php
$pageTitle='Employee Self-Service Admin';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('employee_self_service_admin');
$pdo=getDB();
$leave=$pdo->query('SELECT l.*,CONCAT(e.first_name," ",e.last_name) employee_name,e.employee_code FROM '.table('leave_requests').' l LEFT JOIN '.table('employees').' e ON e.id=l.employee_id ORDER BY l.created_at DESC LIMIT 20')->fetchAll();
$expenses=$pdo->query('SELECT c.*,CONCAT(e.first_name," ",e.last_name) employee_name,e.employee_code FROM '.table('employee_expense_claims').' c LEFT JOIN '.table('employees').' e ON e.id=c.employee_id ORDER BY c.created_at DESC LIMIT 20')->fetchAll();
$docs=$pdo->query('SELECT d.*,CONCAT(e.first_name," ",e.last_name) employee_name,e.employee_code FROM '.table('employee_documents').' d LEFT JOIN '.table('employees').' e ON e.id=d.employee_id ORDER BY d.created_at DESC LIMIT 20')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Employee Portal Control</div><h2 class="h4 mb-1">Employee Self-Service Admin</h2><p class="text-secondary mb-0">Review employee leave, expense, document and payslip activity from one screen.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Leave Requests</h2><table class="table"><tbody><?php foreach($leave as $r): ?><tr><td><strong><?php echo esc($r['employee_code'].' · '.$r['employee_name']); ?></strong><div class="small text-secondary"><?php echo esc($r['leave_type'].' '.$r['start_date'].' → '.$r['end_date']); ?></div><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-4"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Expense Claims</h2><table class="table"><tbody><?php foreach($expenses as $r): ?><tr><td><strong><?php echo esc($r['claim_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['employee_code'].' · '.$r['employee_name']); ?></div><?php echo money($r['total_amount']); ?> <span class="badge bg-<?php echo esc(statusTone($r['approval_status'])); ?>"><?php echo esc($r['approval_status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-4"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Documents</h2><table class="table"><tbody><?php foreach($docs as $d): ?><tr><td><strong><?php echo esc($d['document_type']); ?></strong><div class="small text-secondary"><?php echo esc($d['employee_code'].' · '.$d['employee_name']); ?></div><?php echo esc($d['file_name']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>