<?php
$pageTitle='Goods Receipt Notes';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('goods_receipts');
$pdo=getDB();
$scopeOptions=scopeSelectOptions($pdo);
$filters=requestScopeFilters();
$params=[];$condition=selectedScopeCondition('gr',$params,$filters,['company_id','branch_id','warehouse_id']);$condition.=scopeQueryCondition($pdo,'gr',$params,false);$where=$condition!==''?' WHERE '.substr($condition,5):'';
$stmt=$pdo->prepare('SELECT gr.*,po.po_number,s.supplier_code,u.email received_by_email FROM '.table('goods_receipts').' gr LEFT JOIN '.table('purchase_orders').' po ON po.id=gr.purchase_order_id LEFT JOIN '.table('suppliers').' s ON s.id=gr.supplier_id LEFT JOIN '.table('users').' u ON u.id=gr.received_by'.$where.' ORDER BY gr.created_at DESC,gr.id DESC LIMIT 250');
$stmt->execute($params);$rows=$stmt->fetchAll();
$totalValue=0.0;foreach($rows as $row){$totalValue+=(float)$row['total_value'];}
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Procurement Receiving</div><h2 class="h4 mb-1">Goods Receipt Notes</h2><p class="text-secondary mb-0">Track accepted and rejected supplier deliveries linked to approved purchase orders.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/purchase-orders.php">Open Purchase Orders</a></div>
<div class="row g-4 mb-4"><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Visible GRNs</div><div class="metric-sm"><?php echo count($rows); ?></div></div></div><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Accepted Receipt Value</div><div class="metric-sm"><?php echo money($totalValue); ?></div></div></div></div>
<div class="card-admin p-3 mb-4"><form class="d-flex flex-wrap gap-2 align-items-end"><div><label class="form-label">Company</label><select class="form-select" name="company_id"><option value="0">All</option><?php foreach($scopeOptions['companies'] as $company): ?><option value="<?php echo (int)$company['id']; ?>" <?php echo (int)$filters['company_id']===(int)$company['id']?'selected':''; ?>><?php echo esc($company['company_code'].' · '.$company['company_name']); ?></option><?php endforeach; ?></select></div><div><label class="form-label">Branch</label><select class="form-select" name="branch_id"><option value="0">All</option><?php foreach($scopeOptions['branches'] as $branch): ?><option value="<?php echo (int)$branch['id']; ?>" <?php echo (int)$filters['branch_id']===(int)$branch['id']?'selected':''; ?>><?php echo esc($branch['branch_code'].' · '.$branch['branch_name']); ?></option><?php endforeach; ?></select></div><button class="btn btn-brand">Apply</button></form></div>
<div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Receipt Register</div><h2 class="h5 mb-0">GRN Audit Trail</h2></div></div><table class="table align-middle"><thead><tr><th>GRN</th><th>PO</th><th>Supplier</th><th>Date</th><th>Value</th><th>Received By</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?php echo esc($row['grn_number']); ?></strong></td><td><?php echo esc($row['po_number']?:'—'); ?></td><td><?php echo esc(($row['supplier_code']? $row['supplier_code'].' · ' : '').($row['supplier_name']?:'—')); ?></td><td><?php echo esc($row['receipt_date']); ?></td><td><?php echo money($row['total_value']); ?></td><td><?php echo esc($row['received_by_email']?:'System'); ?></td><td><span class="badge bg-<?php echo esc(statusTone($row['status'])); ?>"><?php echo esc(ucfirst($row['status'])); ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/view-goods-receipt.php?id=<?php echo (int)$row['id']; ?>">Open</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="8" class="text-secondary">No goods receipt notes found.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>