<?php
$pageTitle='Job Cards / Workshop Orders';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('job_cards');
$pdo=getDB();
$scopeOptions=scopeSelectOptions($pdo);
$filters=requestScopeFilters();
$status=trim((string)($_GET['status']??''));
$params=[];$where='';
if($status!==''){$where=' WHERE jc.status=?';$params[]=$status;}
$condition=selectedScopeCondition('jc',$params,$filters,['company_id','branch_id','warehouse_id']);$condition.=scopeQueryCondition($pdo,'jc',$params,false);
if($where===''){$where=$condition!==''?' WHERE '.substr($condition,5):'';}else{$where.=$condition;}
$stmt=$pdo->prepare('SELECT jc.*,c.customer_code,u.email technician_email,i.invoice_number FROM '.table('job_cards').' jc LEFT JOIN '.table('customers').' c ON c.id=jc.customer_id LEFT JOIN '.table('users').' u ON u.id=jc.technician_user_id LEFT JOIN '.table('invoices').' i ON i.id=jc.invoice_id'.$where.' ORDER BY jc.created_at DESC,jc.id DESC LIMIT 250');
$stmt->execute($params);$rows=$stmt->fetchAll();
$summary=['draft'=>0,'diagnosis'=>0,'in_progress'=>0,'completed'=>0,'invoiced'=>0,'value'=>0.0,'cost'=>0.0];foreach($rows as $row){$k=(string)$row['status'];if(isset($summary[$k])){$summary[$k]++;}$summary['value']+=(float)$row['estimated_total'];$summary['cost']+=(float)$row['actual_cost'];}
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker"><?php echo t('Service Operations', 'عمليات الخدمة'); ?></div><h2 class="h4 mb-1">Job Cards / Workshop Orders</h2><p class="text-secondary mb-0">Manage diagnosis, labor, parts consumption, technician assignment, costing, and invoice conversion.</p></div><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/create-job-card.php">Create Job Card</a></div>
<div class="row g-4 mb-4"><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Open Job Cards</div><div class="metric-sm"><?php echo (int)($summary['draft']+$summary['diagnosis']+$summary['in_progress']); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Completed</div><div class="metric-sm money-positive"><?php echo (int)$summary['completed']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Service Revenue</div><div class="metric-sm"><?php echo money($summary['value']); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Service Cost</div><div class="metric-sm"><?php echo money($summary['cost']); ?></div></div></div></div>
<div class="card-admin p-3 mb-4"><form class="d-flex flex-wrap gap-2 align-items-end"><div><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option><?php foreach(['draft','diagnosis','in_progress','waiting_parts','completed','invoiced','cancelled'] as $filter): ?><option value="<?php echo esc($filter); ?>" <?php echo $status===$filter?'selected':''; ?>><?php echo esc(str_replace('_',' ',ucwords($filter,'_'))); ?></option><?php endforeach; ?></select></div><div><label class="form-label">Company</label><select class="form-select" name="company_id"><option value="0">All</option><?php foreach($scopeOptions['companies'] as $company): ?><option value="<?php echo (int)$company['id']; ?>" <?php echo (int)$filters['company_id']===(int)$company['id']?'selected':''; ?>><?php echo esc($company['company_code'].' · '.$company['company_name']); ?></option><?php endforeach; ?></select></div><button class="btn btn-brand">Apply</button></form></div>
<div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Workshop Register</div><h2 class="h5 mb-0">Job Card Pipeline</h2></div></div><table class="table align-middle"><thead><tr><th>Job Card</th><th>Customer / Vehicle</th><th>Technician</th><th>Total</th><th>Cost</th><th>Status</th><th>Invoice</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?php echo esc($row['job_card_number']); ?></strong><div class="small text-secondary"><?php echo esc($row['priority']); ?></div></td><td><?php echo esc(($row['customer_code']? $row['customer_code'].' · ' : '').($row['customer_name']?:'—')); ?><div class="small text-secondary"><?php echo esc(trim(($row['vehicle_make']?:'').' '.($row['vehicle_model']?:'').' '.($row['plate_number']?:''))); ?></div></td><td><?php echo esc($row['technician_email']?:'Unassigned'); ?></td><td><?php echo money($row['estimated_total']); ?></td><td><?php echo money($row['actual_cost']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($row['status'])); ?>"><?php echo esc(str_replace('_',' ',ucwords($row['status'],'_'))); ?></span></td><td><?php echo esc($row['invoice_number']?:'—'); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/view-job-card.php?id=<?php echo (int)$row['id']; ?>">Open</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="8" class="text-secondary">No job cards found.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>