<?php
$pageTitle='KPI Alerts';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('kpi_alerts');
$pdo=getDB();$kpis=$pdo->query('SELECT * FROM '.table('report_kpis').' WHERE active=1 ORDER BY kpi_name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'rule');
    if($action==='run'){$count=runBiKpiAlertRules($pdo);flash('success','KPI alert run completed. '.$count.' event(s) created.');}
    elseif($action==='close'){$pdo->prepare('UPDATE '.table('bi_kpi_alert_events').' SET status="closed",closed_at=NOW() WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Alert event closed.');}
    else{$number=nextScopedDocumentNumber($pdo,'kpi_alert_rule',setting('kpi_alert_rule_prefix','KAL'),operationalScope($pdo));$user=currentUser();$pdo->prepare('INSERT INTO '.table('bi_kpi_alert_rules').' (rule_number,report_kpi_id,condition_type,threshold_value,severity,notify_roles,status,created_by) VALUES (?,?,?,?,?,?,"active",?)')->execute([$number,(int)$_POST['report_kpi_id'],trim((string)$_POST['condition_type']),max(0,(float)$_POST['threshold_value']),trim((string)$_POST['severity']),trim((string)$_POST['notify_roles']),(int)($user['id']??0)?:null]);flash('success','KPI alert rule created.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'kpi-alerts']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/kpi-alerts.php');
}
$rules=$pdo->query('SELECT r.*,k.kpi_code,k.kpi_name,k.metric_source FROM '.table('bi_kpi_alert_rules').' r LEFT JOIN '.table('report_kpis').' k ON k.id=r.report_kpi_id ORDER BY r.created_at DESC LIMIT 100')->fetchAll();
$events=$pdo->query('SELECT e.*,r.rule_number,k.kpi_name FROM '.table('bi_kpi_alert_events').' e LEFT JOIN '.table('bi_kpi_alert_rules').' r ON r.id=e.bi_kpi_alert_rule_id LEFT JOIN '.table('report_kpis').' k ON k.id=r.report_kpi_id ORDER BY e.created_at DESC LIMIT 150')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">KPI Monitoring</div><h2 class="h4 mb-1">KPI Alert Rules</h2><p class="text-secondary mb-0">Create threshold rules and run KPI monitoring against current metric values.</p></div><form method="post"><input type="hidden" name="action" value="run"><button class="btn btn-brand">Run Alert Check</button></form></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Create Alert Rule</h2><select class="form-select mb-2" name="report_kpi_id"><?php foreach($kpis as $k): ?><option value="<?php echo (int)$k['id']; ?>"><?php echo esc($k['kpi_code'].' · '.$k['kpi_name']); ?></option><?php endforeach; ?></select><select class="form-select mb-2" name="condition_type"><option value="below_target">Below Target</option><option value="above_limit">Above Limit</option><option value="equals">Equals</option></select><input class="form-control mb-2" type="number" step="0.01" name="threshold_value" placeholder="Threshold"><select class="form-select mb-2" name="severity"><option>warning</option><option>danger</option><option>critical</option></select><input class="form-control mb-3" name="notify_roles" placeholder="admin,manager,finance"><button class="btn btn-outline-primary w-100">Create Rule</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Rules</h2><table class="table"><thead><tr><th>Rule</th><th>KPI</th><th>Condition</th><th>Threshold</th><th>Status</th></tr></thead><tbody><?php foreach($rules as $r): ?><tr><td><strong><?php echo esc($r['rule_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['severity']); ?></div></td><td><?php echo esc($r['kpi_code'].' · '.$r['kpi_name']); ?></td><td><?php echo esc($r['condition_type']); ?></td><td><?php echo number_format((float)$r['threshold_value'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Alert Events</h2><table class="table"><thead><tr><th>Event</th><th>Value</th><th>Threshold</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($events as $e): ?><tr><td><strong><?php echo esc($e['rule_number'].' · '.$e['kpi_name']); ?></strong><div class="small text-secondary"><?php echo esc($e['event_message']); ?></div></td><td><?php echo number_format((float)$e['metric_value'],2); ?></td><td><?php echo number_format((float)$e['threshold_value'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($e['status'])); ?>"><?php echo esc($e['status']); ?></span></td><td><?php if($e['status']!=='closed'): ?><form method="post"><input type="hidden" name="action" value="close"><input type="hidden" name="id" value="<?php echo (int)$e['id']; ?>"><button class="btn btn-sm btn-success">Close</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>