<?php
$pageTitle='License Center';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('license_center');
$pdo=getDB();

if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'');
    if($action==='create_license'){
      $plain='ECOM-'.strtoupper(bin2hex(random_bytes(4))).'-'.strtoupper(bin2hex(random_bytes(4))).'-'.strtoupper(bin2hex(random_bytes(4)));
      $hash=password_hash($plain,PASSWORD_DEFAULT);
      $stmt=$pdo->prepare('INSERT INTO '.table('license_keys').' (license_key_hash,license_prefix,license_name,company_id,subscription_plan_id,status,issued_to,issued_email,domain_name,max_users,max_branches,modules_json,issued_at,expires_at,notes) VALUES (?,?,?,?,?,"active",?,?,?,?,?,?,NOW(),?,?)');
      $stmt->execute([$hash,substr($plain,0,14),trim((string)$_POST['license_name']),(int)($_POST['company_id']??0)?:null,(int)($_POST['subscription_plan_id']??0)?:null,trim((string)$_POST['issued_to']),trim((string)$_POST['issued_email']),trim((string)$_POST['domain_name']),max(0,(int)$_POST['max_users']),max(0,(int)$_POST['max_branches']),json_encode($_POST['modules']??[]),trim((string)$_POST['expires_at'])?:null,'Plain license generated: '.$plain]);
      flash('success','License created. Copy this one-time key now: '.$plain);
    }elseif($action==='toggle_module'){
      $id=(int)$_POST['id'];$pdo->prepare('UPDATE '.table('module_entitlements').' SET is_enabled=CASE WHEN is_enabled=1 THEN 0 ELSE 1 END WHERE id=?')->execute([$id]);flash('success','Module entitlement updated.');
    }elseif($action==='validate'){
      $companyId=(int)($_POST['company_id']??0);$result=licenseStatus($pdo,$companyId);flash($result['status']==='active'?'success':'error',$result['message']);
    }
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'license-center']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/license-center.php');
}
$companies=$pdo->query('SELECT id,company_code,company_name FROM '.table('companies').' ORDER BY company_name')->fetchAll();
$plans=$pdo->query('SELECT id,plan_code,plan_name FROM '.table('subscription_plans').' WHERE status="active" ORDER BY monthly_price')->fetchAll();
$licenses=$pdo->query('SELECT lk.*,c.company_name,sp.plan_code FROM '.table('license_keys').' lk LEFT JOIN '.table('companies').' c ON c.id=lk.company_id LEFT JOIN '.table('subscription_plans').' sp ON sp.id=lk.subscription_plan_id ORDER BY lk.created_at DESC')->fetchAll();
$modules=$pdo->query('SELECT me.*,c.company_name FROM '.table('module_entitlements').' me LEFT JOIN '.table('companies').' c ON c.id=me.company_id ORDER BY me.company_id,me.module_key')->fetchAll();
$logs=$pdo->query('SELECT lvl.*,lk.license_prefix FROM '.table('license_validation_logs').' lvl LEFT JOIN '.table('license_keys').' lk ON lk.id=lvl.license_key_id ORDER BY lvl.created_at DESC LIMIT 50')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">License Governance</div><h2 class="h4 mb-1">License Center</h2><p class="text-secondary mb-0">Generate license keys, validate local license status, and control module entitlements.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/update-center.php"><?php echo t('Update Center', 'مركز التحديث'); ?></a></div>
<div class="row g-4">
  <div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="create_license"><div class="erp-kicker">Issue License</div><h2 class="h5 mb-3">Create New License Key</h2><label class="form-label">License Name</label><input class="form-control mb-2" name="license_name" value="Customer License"><label class="form-label">Company</label><select class="form-select mb-2" name="company_id"><option value="0">Global / any company</option><?php foreach($companies as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo esc($c['company_code'].' · '.$c['company_name']); ?></option><?php endforeach; ?></select><label class="form-label">Plan</label><select class="form-select mb-2" name="subscription_plan_id"><option value="0">No plan</option><?php foreach($plans as $p): ?><option value="<?php echo (int)$p['id']; ?>"><?php echo esc($p['plan_code'].' · '.$p['plan_name']); ?></option><?php endforeach; ?></select><label class="form-label">Issued To</label><input class="form-control mb-2" name="issued_to"><label class="form-label">Email</label><input class="form-control mb-2" type="email" name="issued_email"><label class="form-label">Domain</label><input class="form-control mb-2" name="domain_name" placeholder="example.com"><div class="row g-2"><div class="col-6"><label class="form-label">Max Users</label><input class="form-control" type="number" name="max_users" value="25"></div><div class="col-6"><label class="form-label">Max Branches</label><input class="form-control" type="number" name="max_branches" value="5"></div></div><label class="form-label mt-2">Expiry</label><input class="form-control mb-3" type="datetime-local" name="expires_at"><button class="btn btn-brand w-100">Generate License</button></form></div>
  <div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><div class="table-toolbar"><div><div class="erp-kicker">License Register</div><h2 class="h5 mb-0">Issued Licenses</h2></div><form method="post" class="d-flex gap-2"><input type="hidden" name="action" value="validate"><select class="form-select form-select-sm" name="company_id"><?php foreach($companies as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo esc($c['company_code']); ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-outline-primary">Validate</button></form></div><table class="table align-middle"><thead><tr><th>License</th><th>Company / Plan</th><th>Limits</th><th>Status</th><th>Expiry</th></tr></thead><tbody><?php foreach($licenses as $l): ?><tr><td><strong><?php echo esc($l['license_prefix']); ?>...</strong><div class="small text-secondary"><?php echo esc($l['license_name']); ?></div></td><td><?php echo esc($l['company_name']?:'Global'); ?><div class="small text-secondary"><?php echo esc($l['plan_code']?:'No plan'); ?></div></td><td><?php echo (int)$l['max_users']; ?> users · <?php echo (int)$l['max_branches']; ?> branches</td><td><span class="badge bg-<?php echo esc(statusTone($l['status'])); ?>"><?php echo esc($l['status']); ?></span></td><td><?php echo esc($l['expires_at']?:'Never'); ?></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Module Entitlements</h2><table class="table"><tbody><?php foreach($modules as $m): ?><tr><td><strong><?php echo esc($m['module_key']); ?></strong><div class="small text-secondary"><?php echo esc(($m['company_name']?:'Global').' · '.$m['module_name']); ?></div></td><td><span class="badge bg-<?php echo (int)$m['is_enabled']===1?'success':'secondary'; ?>"><?php echo (int)$m['is_enabled']===1?'Enabled':'Disabled'; ?></span></td><td class="text-end"><form method="post"><input type="hidden" name="action" value="toggle_module"><input type="hidden" name="id" value="<?php echo (int)$m['id']; ?>"><button class="btn btn-sm btn-outline-primary">Toggle</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
</div>
<div class="table-wrap table-responsive mt-4"><h2 class="h5 mb-3">Validation Logs</h2><table class="table"><thead><tr><th>Date</th><th>License</th><th>Status</th><th>Domain</th><th>Message</th></tr></thead><tbody><?php foreach($logs as $log): ?><tr><td><?php echo esc($log['created_at']); ?></td><td><?php echo esc($log['license_prefix']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($log['status'])); ?>"><?php echo esc($log['status']); ?></span></td><td><?php echo esc($log['domain_name']); ?></td><td><?php echo esc($log['message']); ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>