<?php
$pageTitle='Manufacturing Work Orders';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('work_orders');
$pdo=getDB();
$boms=$pdo->query('SELECT b.*,p.name product_name FROM '.table('bill_of_materials').' b LEFT JOIN '.table('products').' p ON p.id=b.finished_product_id WHERE b.status IN ("approved","released") ORDER BY b.created_at DESC')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'');
    if($action==='create'){createManufacturingWorkOrder($pdo,(int)$_POST['bom_id'],max(0.0001,(float)$_POST['planned_quantity']),trim((string)$_POST['planned_start']),trim((string)$_POST['planned_finish']));flash('success','Work order created.');}
    elseif($action==='start'){$pdo->prepare('UPDATE '.table('manufacturing_work_orders').' SET status="in_progress",actual_start=COALESCE(actual_start,NOW()) WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Work order started.');}
    elseif($action==='release'){$pdo->prepare('UPDATE '.table('manufacturing_work_orders').' SET status="released" WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Work order released.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'manufacturing-work-orders']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/manufacturing-work-orders.php');
}
$orders=$pdo->query('SELECT wo.*,b.bom_number,p.name product_name FROM '.table('manufacturing_work_orders').' wo LEFT JOIN '.table('bill_of_materials').' b ON b.id=wo.bill_of_material_id LEFT JOIN '.table('products').' p ON p.id=wo.finished_product_id ORDER BY wo.created_at DESC LIMIT 150')->fetchAll();
$materials=$pdo->query('SELECT wm.*,wo.work_order_number,p.sku,p.name FROM '.table('work_order_materials').' wm LEFT JOIN '.table('manufacturing_work_orders').' wo ON wo.id=wm.manufacturing_work_order_id LEFT JOIN '.table('products').' p ON p.id=wm.component_product_id ORDER BY wm.created_at DESC LIMIT 100')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Shop Floor Control</div><h2 class="h4 mb-1">Manufacturing Work Orders</h2><p class="text-secondary mb-0">Create, release, start, and monitor production work orders.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/material-issue.php">Issue Materials</a></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="create"><h2 class="h5 mb-3">Create Work Order</h2><label class="form-label">Approved BOM</label><select class="form-select mb-2" name="bom_id"><?php foreach($boms as $b): ?><option value="<?php echo (int)$b['id']; ?>"><?php echo esc($b['bom_number'].' · '.$b['product_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" type="number" step="0.0001" name="planned_quantity" value="1"><div class="row g-2"><div class="col-6"><label class="form-label">Start</label><input class="form-control" type="date" name="planned_start"></div><div class="col-6"><label class="form-label">Finish</label><input class="form-control" type="date" name="planned_finish"></div></div><button class="btn btn-brand w-100 mt-3">Create Work Order</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Work Orders</h2><table class="table align-middle"><thead><tr><th>WO</th><th>Product</th><th>Qty</th><th>Completed</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($orders as $wo): ?><tr><td><strong><?php echo esc($wo['work_order_number']); ?></strong><div class="small text-secondary"><?php echo esc($wo['bom_number']); ?></div></td><td><?php echo esc($wo['product_name']); ?></td><td><?php echo number_format((float)$wo['planned_quantity'],2); ?></td><td><?php echo number_format((float)$wo['completed_quantity'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($wo['status'])); ?>"><?php echo esc($wo['status']); ?></span></td><td><form method="post" class="d-inline"><input type="hidden" name="id" value="<?php echo (int)$wo['id']; ?>"><input type="hidden" name="action" value="release"><button class="btn btn-sm btn-outline-primary">Release</button></form> <form method="post" class="d-inline"><input type="hidden" name="id" value="<?php echo (int)$wo['id']; ?>"><input type="hidden" name="action" value="start"><button class="btn btn-sm btn-success">Start</button></form></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Required Materials</h2><table class="table"><thead><tr><th>WO</th><th>Component</th><th>Required</th><th>Issued</th><th>Status</th></tr></thead><tbody><?php foreach($materials as $m): ?><tr><td><?php echo esc($m['work_order_number']); ?></td><td><?php echo esc($m['sku'].' · '.$m['name']); ?></td><td><?php echo number_format((float)$m['required_quantity'],4); ?></td><td><?php echo number_format((float)$m['issued_quantity'],4); ?></td><td><span class="badge bg-<?php echo esc(statusTone($m['status'])); ?>"><?php echo esc($m['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>