<?php
$pageTitle='Mobile Quick Actions 2.0';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('mobile_quick_actions_2');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'quick');
    if($action==='shortcut'){$pdo->prepare('INSERT INTO '.table('pwa_app_shortcuts').' (shortcut_key,shortcut_name,shortcut_url,icon_url,description,sort_order,is_enabled,created_by) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE shortcut_name=VALUES(shortcut_name),shortcut_url=VALUES(shortcut_url),icon_url=VALUES(icon_url),description=VALUES(description),sort_order=VALUES(sort_order),is_enabled=VALUES(is_enabled)')->execute([trim((string)$_POST['shortcut_key']),trim((string)$_POST['shortcut_name']),trim((string)$_POST['shortcut_url']),trim((string)$_POST['icon_url']),trim((string)$_POST['description']),(int)$_POST['sort_order'],(int)($_POST['is_enabled']??1),(int)(currentUser()['id']??0)?:null]);flash('success','PWA shortcut saved.');}
    else{$pdo->prepare('INSERT INTO '.table('mobile_quick_actions').' (role_slug,action_key,title,target_url,icon_class,sort_order,is_enabled) VALUES (?,?,?,?,?,?,?)')->execute([trim((string)$_POST['role_slug']),trim((string)$_POST['action_key']),trim((string)$_POST['title']),trim((string)$_POST['target_url']),trim((string)$_POST['icon_class']),(int)$_POST['sort_order'],(int)($_POST['is_enabled']??1)]);flash('success','Mobile quick action created.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'mobile-quick-actions-2']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/mobile-quick-actions-2.php');
}
$actions=$pdo->query('SELECT * FROM '.table('mobile_quick_actions').' ORDER BY role_slug,sort_order,title LIMIT 200')->fetchAll();
$shortcuts=$pdo->query('SELECT * FROM '.table('pwa_app_shortcuts').' ORDER BY sort_order,shortcut_name LIMIT 100')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Mobile Navigation</div><h2 class="h4 mb-1">Mobile Quick Actions 2.0</h2><p class="text-secondary mb-0">Control role-based mobile actions and installable app shortcuts.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4 mb-4"><h2 class="h5 mb-3">Quick Action</h2><input class="form-control mb-2" name="role_slug" placeholder="admin / technician / customer"><input class="form-control mb-2" name="action_key" placeholder="open_jobs"><input class="form-control mb-2" name="title" placeholder="Open Jobs"><input class="form-control mb-2" name="target_url" placeholder="/admin/erp/job-cards.php"><input class="form-control mb-2" name="icon_class" value="bi-lightning-charge"><input class="form-control mb-2" type="number" name="sort_order" value="10"><select class="form-select mb-3" name="is_enabled"><option value="1">Enabled</option><option value="0">Disabled</option></select><button class="btn btn-brand w-100">Create Action</button></form><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="shortcut"><h2 class="h5 mb-3">PWA Shortcut</h2><input class="form-control mb-2" name="shortcut_key" placeholder="technician"><input class="form-control mb-2" name="shortcut_name" placeholder="Technician"><input class="form-control mb-2" name="shortcut_url" placeholder="/mobile/technician.php"><input class="form-control mb-2" name="icon_url" placeholder="/assets/img/icon-192.png"><textarea class="form-control mb-2" name="description" rows="2"></textarea><input class="form-control mb-2" type="number" name="sort_order" value="1"><select class="form-select mb-3" name="is_enabled"><option value="1">Enabled</option><option value="0">Disabled</option></select><button class="btn btn-outline-primary w-100">Save Shortcut</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Mobile Actions</h2><table class="table"><thead><tr><th>Role</th><th>Action</th><th>URL</th><th>Enabled</th></tr></thead><tbody><?php foreach($actions as $a): ?><tr><td><?php echo esc($a['role_slug']?:'All'); ?></td><td><strong><?php echo esc($a['title']); ?></strong><div class="small text-secondary"><?php echo esc($a['action_key'].' · '.$a['icon_class']); ?></div></td><td><?php echo esc($a['target_url']); ?></td><td><?php echo $a['is_enabled']?'Yes':'No'; ?></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">PWA Shortcuts</h2><table class="table"><thead><tr><th>Shortcut</th><th>URL</th><th>Order</th><th>Enabled</th></tr></thead><tbody><?php foreach($shortcuts as $s): ?><tr><td><strong><?php echo esc($s['shortcut_name']); ?></strong><div class="small text-secondary"><?php echo esc($s['shortcut_key']); ?></div></td><td><?php echo esc($s['shortcut_url']); ?></td><td><?php echo (int)$s['sort_order']; ?></td><td><?php echo $s['is_enabled']?'Yes':'No'; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>