<?php
$pageTitle='Offline Sync Center';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('mobile_offline_sync');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'queue');
    if($action==='queue'){queueMobileOfflineSync($pdo,(int)($_POST['user_id']??0)?:null,trim((string)$_POST['device_id']),trim((string)$_POST['entity_type']),(int)($_POST['entity_id']??0)?:null,trim((string)$_POST['operation']),json_decode((string)$_POST['payload_json'],true) ?: []);flash('success','Offline sync item queued.');}
    elseif($action==='process'){processMobileOfflineSync($pdo,(int)$_POST['id']);flash('success','Offline sync item processed.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'offline-sync-center']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/offline-sync-center.php');
}
$queue=$pdo->query('SELECT q.*,u.email FROM '.table('mobile_offline_sync_queue').' q LEFT JOIN '.table('users').' u ON u.id=q.user_id ORDER BY FIELD(q.sync_status,"pending","failed","synced"),q.created_at DESC LIMIT 200')->fetchAll();
$logs=$pdo->query('SELECT l.*,q.sync_number FROM '.table('mobile_offline_sync_logs').' l LEFT JOIN '.table('mobile_offline_sync_queue').' q ON q.id=l.mobile_offline_sync_queue_id ORDER BY l.created_at DESC LIMIT 150')->fetchAll();
$drafts=$pdo->query('SELECT d.*,u.email FROM '.table('offline_job_card_drafts').' d LEFT JOIN '.table('users').' u ON u.id=d.user_id ORDER BY d.created_at DESC LIMIT 100')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Offline Mobile Data</div><h2 class="h4 mb-1">Offline Sync Center</h2><p class="text-secondary mb-0">Review offline queue, sync logs and offline job-card drafts from mobile devices.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Queue Offline Payload</h2><input class="form-control mb-2" type="number" name="user_id" placeholder="User ID optional"><input class="form-control mb-2" name="device_id" placeholder="device-id"><select class="form-select mb-2" name="entity_type"><option>job_card_draft</option><option>customer_note</option><option>parts_usage</option><option>time_entry</option></select><input class="form-control mb-2" type="number" name="entity_id" placeholder="Entity ID optional"><select class="form-select mb-2" name="operation"><option>upsert</option><option>create</option><option>update</option></select><textarea class="form-control mb-3" name="payload_json" rows="5">{"notes":"Offline mobile draft"}</textarea><button class="btn btn-brand w-100">Queue</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Sync Queue</h2><table class="table"><thead><tr><th>Sync</th><th>Device/User</th><th>Entity</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($queue as $q): ?><tr><td><strong><?php echo esc($q['sync_number']); ?></strong><div class="small text-secondary"><?php echo esc($q['operation'].' · '.$q['created_at']); ?></div></td><td><?php echo esc(($q['email']?:'Guest').' · '.$q['device_id']); ?></td><td><?php echo esc($q['entity_type'].' #'.$q['entity_id']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($q['sync_status'])); ?>"><?php echo esc($q['sync_status']); ?></span></td><td><?php if($q['sync_status']==='pending'): ?><form method="post"><input type="hidden" name="action" value="process"><input type="hidden" name="id" value="<?php echo (int)$q['id']; ?>"><button class="btn btn-sm btn-success">Process</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Offline Drafts</h2><table class="table"><tbody><?php foreach($drafts as $d): ?><tr><td><strong><?php echo esc($d['draft_number']); ?></strong><div class="small text-secondary"><?php echo esc(($d['email']?:'Guest').' · '.$d['device_id'].' · '.$d['sync_status']); ?></div></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Sync Logs</h2><table class="table"><tbody><?php foreach($logs as $l): ?><tr><td><strong><?php echo esc($l['sync_number']); ?></strong><div class="small text-secondary"><?php echo esc($l['message']); ?></div></td><td><?php echo esc($l['sync_status']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>