<?php
$pageTitle='Payroll Dashboard';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('payroll');
$pdo=getDB();
$kpi=[
 'employees'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('employees').' WHERE status="active"')->fetchColumn(),
 'open_periods'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('payroll_periods').' WHERE status="open"')->fetchColumn(),
 'draft_runs'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('payroll_runs').' WHERE status="draft"')->fetchColumn(),
 'net_total'=>(float)$pdo->query('SELECT COALESCE(SUM(net_total),0) FROM '.table('payroll_runs').' WHERE status IN ("draft","approved","posted")')->fetchColumn(),
];
$runs=$pdo->query('SELECT pr.*,pp.period_name,pp.start_date,pp.end_date FROM '.table('payroll_runs').' pr LEFT JOIN '.table('payroll_periods').' pp ON pp.id=pr.payroll_period_id ORDER BY pr.created_at DESC LIMIT 8')->fetchAll();
$claims=$pdo->query('SELECT c.*,e.employee_code,e.first_name,e.last_name FROM '.table('employee_expense_claims').' c LEFT JOIN '.table('employees').' e ON e.id=c.employee_id ORDER BY c.created_at DESC LIMIT 8')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">People Cost Control</div><h2 class="h4 mb-1">Payroll Dashboard</h2><p class="text-secondary mb-0">Payroll, attendance, reimbursements, commissions, and performance control center.</p></div><div class="d-flex gap-2"><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/payroll-runs.php"><?php echo t('Payroll Runs', 'تشغيل الرواتب'); ?></a><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/attendance.php"><?php echo t('Attendance', 'الحضور والانصراف'); ?></a></div></div>
<div class="row g-4 mb-4"><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Active Employees</div><div class="metric-sm"><?php echo $kpi['employees']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Open Periods</div><div class="metric-sm"><?php echo $kpi['open_periods']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Draft Runs</div><div class="metric-sm"><?php echo $kpi['draft_runs']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Payroll Exposure</div><div class="metric-sm"><?php echo money($kpi['net_total']); ?></div></div></div></div>
<div class="row g-4"><div class="col-xl-7"><div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Recent Payroll</div><h2 class="h5 mb-0">Payroll Runs</h2></div></div><table class="table align-middle"><thead><tr><th>Run</th><th>Period</th><th>Gross</th><th>Net</th><th>Status</th></tr></thead><tbody><?php foreach($runs as $run): ?><tr><td><strong><?php echo esc($run['payroll_number']); ?></strong></td><td><?php echo esc($run['period_name']); ?><div class="small text-secondary"><?php echo esc($run['start_date'].' → '.$run['end_date']); ?></div></td><td><?php echo money($run['gross_total']); ?></td><td><?php echo money($run['net_total']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($run['status'])); ?>"><?php echo esc($run['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$runs): ?><tr><td colspan="5" class="text-secondary">No payroll runs yet.</td></tr><?php endif; ?></tbody></table></div></div><div class="col-xl-5"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Recent Expense Claims</h2><table class="table"><tbody><?php foreach($claims as $claim): ?><tr><td><strong><?php echo esc($claim['claim_number']); ?></strong><div class="small text-secondary"><?php echo esc(($claim['employee_code']?:'').' '.$claim['first_name'].' '.$claim['last_name']); ?></div></td><td><?php echo money($claim['total_amount']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($claim['status'])); ?>"><?php echo esc($claim['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$claims): ?><tr><td class="text-secondary">No expense claims yet.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>