<?php
$pageTitle='Plan Module Matrix';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('plan_module_matrix');
$pdo=getDB();$plans=$pdo->query('SELECT * FROM '.table('subscription_plans').' ORDER BY monthly_price ASC')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'install');
    if($action==='install'){$created=installSaasModuleCatalog($pdo);$matrix=installPlanModuleMatrix($pdo,(int)($_POST['plan_id']??0));flash('success','Catalog created '.$created.', matrix rows '.$matrix.'.');}
    elseif($action==='toggle'){$pdo->prepare('UPDATE '.table('saas_plan_modules').' SET is_enabled=CASE WHEN is_enabled=1 THEN 0 ELSE 1 END WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Module status changed.');}
    elseif($action==='catalog'){$pdo->prepare('INSERT INTO '.table('saas_module_catalog').' (module_key,module_name,module_group,description,default_enabled,status) VALUES (?,?,?,?,?,"active") ON DUPLICATE KEY UPDATE module_name=VALUES(module_name),module_group=VALUES(module_group),description=VALUES(description),default_enabled=VALUES(default_enabled)')->execute([trim((string)$_POST['module_key']),trim((string)$_POST['module_name']),trim((string)$_POST['module_group']),trim((string)$_POST['description']),(int)($_POST['default_enabled']??1)]);flash('success','Module catalog saved.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'plan-module-matrix']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/plan-module-matrix.php');
}
$catalog=$pdo->query('SELECT * FROM '.table('saas_module_catalog').' ORDER BY module_group,module_name')->fetchAll();
$matrix=$pdo->query('SELECT pm.*,sp.plan_code,sp.plan_name FROM '.table('saas_plan_modules').' pm LEFT JOIN '.table('subscription_plans').' sp ON sp.id=pm.subscription_plan_id ORDER BY sp.monthly_price,pm.module_key')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Plan Entitlement Matrix</div><h2 class="h4 mb-1">Plan Module Matrix</h2><p class="text-secondary mb-0">Control which ERP modules are included in each SaaS subscription plan.</p></div><form method="post"><input type="hidden" name="action" value="install"><button class="btn btn-brand">Install Matrix</button></form></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="catalog"><h2 class="h5 mb-3">Add Module</h2><input class="form-control mb-2" name="module_key" placeholder="module_key"><input class="form-control mb-2" name="module_name" placeholder="Module name"><input class="form-control mb-2" name="module_group" placeholder="Group"><textarea class="form-control mb-2" name="description" rows="3"></textarea><select class="form-select mb-3" name="default_enabled"><option value="1">Default enabled</option><option value="0">Default disabled</option></select><button class="btn btn-outline-primary w-100">Save Module</button></form><div class="table-wrap table-responsive mt-4"><h2 class="h6 mb-3">Catalog</h2><table class="table table-sm"><tbody><?php foreach($catalog as $c): ?><tr><td><strong><?php echo esc($c['module_key']); ?></strong><div class="small text-secondary"><?php echo esc($c['module_name']); ?></div></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-8"><div class="table-wrap table-responsive"><table class="table"><thead><tr><th>Plan</th><th>Module</th><th>Limit</th><th>Overage</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($matrix as $m): ?><tr><td><?php echo esc($m['plan_code'].' · '.$m['plan_name']); ?></td><td><strong><?php echo esc($m['module_key']); ?></strong><div class="small text-secondary"><?php echo esc($m['module_name']); ?></div></td><td><?php echo esc($m['included_limit']); ?></td><td><?php echo money($m['overage_price']); ?></td><td><span class="badge bg-<?php echo $m['is_enabled']?'success':'secondary'; ?>"><?php echo $m['is_enabled']?'enabled':'disabled'; ?></span></td><td><form method="post"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?php echo (int)$m['id']; ?>"><button class="btn btn-sm btn-outline-primary">Toggle</button></form></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>