<?php
$pageTitle='Predictive Alerts';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('predictive_alerts');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$action=(string)($_POST['action']??'');if($action==='generate'){$r=generatePredictiveAlerts($pdo);flash('success','Generated '.$r['created'].' predictive alerts.');}elseif($action==='resolve'){$pdo->prepare('UPDATE '.table('predictive_alerts').' SET status="resolved",resolved_at=NOW() WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Alert resolved.');}}catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'predictive-alerts']);flash('error',$e->getMessage());}redirect(ADMIN_URL.'/erp/predictive-alerts.php');}
$alerts=$pdo->query('SELECT * FROM '.table('predictive_alerts').' ORDER BY FIELD(status,"open","resolved"),FIELD(severity,"high","medium","low"),score DESC,created_at DESC LIMIT 300')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Risk Forecast</div><h2 class="h4 mb-1">Predictive Alerts</h2><p class="text-secondary mb-0">Generate early warnings for low stock, receivables, delayed service jobs, and operational risks.</p></div><form method="post"><input type="hidden" name="action" value="generate"><button class="btn btn-brand">Generate Alerts</button></form></div><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Alert</th><th>Module</th><th>Score</th><th>Message</th><th>Recommended Action</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($alerts as $a): ?><tr><td><strong><?php echo esc($a['alert_number']); ?></strong><div class="small text-secondary"><?php echo esc($a['title']); ?></div><span class="badge bg-<?php echo esc(statusTone($a['severity'])); ?>"><?php echo esc($a['severity']); ?></span></td><td><?php echo esc($a['source_module']); ?></td><td><?php echo number_format((float)$a['score'],1); ?></td><td><?php echo esc($a['message']); ?></td><td><?php echo esc($a['recommended_action']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($a['status'])); ?>"><?php echo esc($a['status']); ?></span></td><td><?php if($a['status']==='open'): ?><form method="post"><input type="hidden" name="action" value="resolve"><input type="hidden" name="id" value="<?php echo (int)$a['id']; ?>"><button class="btn btn-sm btn-outline-success">Resolve</button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$alerts): ?><tr><td colspan="7" class="text-secondary">No predictive alerts yet. Click Generate Alerts.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>