<?php
$pageTitle='Projects & Costing';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('projects');
$pdo=getDB();
$status=trim((string)($_GET['status']??''));
$params=[];$where='';
if($status!==''){$where=' WHERE p.status=?';$params[]=$status;}
$condition=scopeQueryCondition($pdo,'p',$params,false);if($where===''){$where=$condition!==''?' WHERE '.substr($condition,5):'';}else{$where.=$condition;}
$stmt=$pdo->prepare('SELECT p.*,c.customer_code,cc.cost_center_code,u.email manager_email FROM '.table('projects').' p LEFT JOIN '.table('customers').' c ON c.id=p.customer_id LEFT JOIN '.table('cost_centers').' cc ON cc.id=p.cost_center_id LEFT JOIN '.table('users').' u ON u.id=p.project_manager_user_id'.$where.' ORDER BY p.created_at DESC LIMIT 250');
$stmt->execute($params);$rows=$stmt->fetchAll();
$budget=0;$revenue=0;$cost=0;$margin=0;foreach($rows as $r){$budget+=(float)$r['budget_amount'];$revenue+=(float)$r['revenue_amount'];$cost+=(float)$r['cost_amount'];$margin+=(float)$r['margin_amount'];}
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Project Profitability</div><h2 class="h4 mb-1">Projects & Costing</h2><p class="text-secondary mb-0">Track project budgets, revenue, labor/material costs, and margin.</p></div><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/create-project.php">Create Project</a></div>
<div class="row g-4 mb-4"><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Budget</div><div class="metric-sm"><?php echo money($budget); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Revenue</div><div class="metric-sm"><?php echo money($revenue); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Cost</div><div class="metric-sm"><?php echo money($cost); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Margin</div><div class="metric-sm <?php echo $margin>=0?'money-positive':'money-negative'; ?>"><?php echo money($margin); ?></div></div></div></div>
<div class="card-admin p-3 mb-4"><form class="d-flex gap-2 align-items-end"><div><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option><?php foreach(['planning','pending_approval','active','on_hold','completed','cancelled'] as $filter): ?><option value="<?php echo esc($filter); ?>" <?php echo $status===$filter?'selected':''; ?>><?php echo esc(str_replace('_',' ',ucwords($filter,'_'))); ?></option><?php endforeach; ?></select></div><button class="btn btn-brand">Apply</button></form></div>
<div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Project Register</div><h2 class="h5 mb-0">Projects</h2></div></div><table class="table align-middle"><thead><tr><th>Project</th><th>Customer</th><th>Manager</th><th>Budget</th><th>Revenue</th><th>Cost</th><th>Margin</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?php echo esc($row['project_number']); ?></strong><div class="small text-secondary"><?php echo esc($row['project_name'].' · '.$row['cost_center_code']); ?></div></td><td><?php echo esc($row['customer_code']?:$row['customer_name']?:'—'); ?></td><td><?php echo esc($row['manager_email']?:'—'); ?></td><td><?php echo money($row['budget_amount']); ?></td><td><?php echo money($row['revenue_amount']); ?></td><td><?php echo money($row['cost_amount']); ?></td><td class="<?php echo (float)$row['margin_amount']>=0?'money-positive':'money-negative'; ?>"><?php echo money($row['margin_amount']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($row['status'])); ?>"><?php echo esc(str_replace('_',' ',ucwords($row['status'],'_'))); ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/view-project.php?id=<?php echo (int)$row['id']; ?>">Open</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>