<?php
$pageTitle='Recommendations';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('recommendations');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$action=(string)($_POST['action']??'');if($action==='generate'){$r=generateRecommendations($pdo);flash('success','Generated '.$r['created'].' recommendations.');}elseif($action==='close'){$pdo->prepare('UPDATE '.table('recommendation_results').' SET status="closed",closed_at=NOW() WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Recommendation closed.');}elseif($action==='rule'){$code=preg_replace('/[^A-Z0-9_\\-]/','',strtoupper((string)$_POST['rule_code']));$pdo->prepare('INSERT INTO '.table('recommendation_rules').' (rule_code,rule_name,module,trigger_metric,condition_json,recommendation_template,priority,status) VALUES (?,?,?,?,?,?,?,"active")')->execute([$code,trim((string)$_POST['rule_name']),trim((string)$_POST['module']),trim((string)$_POST['trigger_metric']),trim((string)$_POST['condition_json'])?:'{}',trim((string)$_POST['recommendation_template']),(int)$_POST['priority']]);flash('success','Recommendation rule created.');}}catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'recommendations']);flash('error',$e->getMessage());}redirect(ADMIN_URL.'/erp/recommendations.php');}
$rules=$pdo->query('SELECT * FROM '.table('recommendation_rules').' ORDER BY priority,id')->fetchAll();$results=$pdo->query('SELECT rr.*,r.rule_code,r.module FROM '.table('recommendation_results').' rr LEFT JOIN '.table('recommendation_rules').' r ON r.id=rr.recommendation_rule_id ORDER BY FIELD(rr.status,"open","closed"),rr.impact_score DESC,rr.created_at DESC LIMIT 250')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Action Engine</div><h2 class="h4 mb-1">Auto Recommendations</h2><p class="text-secondary mb-0">Generate operational recommendations from configured business rules.</p></div><form method="post"><input type="hidden" name="action" value="generate"><button class="btn btn-brand">Generate Recommendations</button></form></div><div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="rule"><h2 class="h5 mb-3">Create Rule</h2><input class="form-control mb-2" name="rule_code" placeholder="RULE-CODE"><input class="form-control mb-2" name="rule_name" placeholder="Rule name"><input class="form-control mb-2" name="module" placeholder="Sales / Finance / Inventory"><input class="form-control mb-2" name="trigger_metric" placeholder="metric_key"><textarea class="form-control mb-2" name="condition_json" rows="2">{}</textarea><textarea class="form-control mb-2" name="recommendation_template" rows="4" placeholder="Recommended action..."></textarea><input class="form-control mb-3" type="number" name="priority" value="100"><button class="btn btn-outline-primary w-100">Create Rule</button></form><div class="table-wrap table-responsive mt-4"><h2 class="h5 mb-3">Rules</h2><table class="table"><tbody><?php foreach($rules as $r): ?><tr><td><strong><?php echo esc($r['rule_code']); ?></strong><div class="small text-secondary"><?php echo esc($r['rule_name'].' · '.$r['module']); ?></div></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-8"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Recommendations</h2><table class="table align-middle"><thead><tr><th>Recommendation</th><th>Impact</th><th>Effort</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($results as $r): ?><tr><td><strong><?php echo esc($r['recommendation_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['title']); ?></div><p class="mb-0"><?php echo esc($r['recommendation_text']); ?></p></td><td><?php echo number_format((float)$r['impact_score'],1); ?></td><td><?php echo number_format((float)$r['effort_score'],1); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td><td><?php if($r['status']==='open'): ?><form method="post"><input type="hidden" name="action" value="close"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn btn-sm btn-outline-success">Close</button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$results): ?><tr><td colspan="5" class="text-secondary">No recommendations yet.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>