<?php
$pageTitle='Report Drilldowns';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('report_drilldowns');
$pdo=getDB();$types=reportTypeOptions();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{$number=nextScopedDocumentNumber($pdo,'report_drilldown',setting('report_drilldown_prefix','RDD'),operationalScope($pdo));$user=currentUser();$pdo->prepare('INSERT INTO '.table('bi_report_drilldowns').' (drilldown_number,source_type,source_id,drilldown_type,title,query_type,config_json,status,created_by) VALUES (?,?,?,?,?,?,?,"active",?)')->execute([$number,trim((string)$_POST['source_type']),(int)($_POST['source_id']??0)?:null,trim((string)$_POST['drilldown_type']),trim((string)$_POST['title']),trim((string)$_POST['query_type']),trim((string)$_POST['config_json'])?:'{}',(int)($user['id']??0)?:null]);flash('success','Drilldown created.');}
  catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'report-drilldowns']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/report-drilldowns.php');
}
$rows=$pdo->query('SELECT * FROM '.table('bi_report_drilldowns').' ORDER BY created_at DESC LIMIT 150')->fetchAll();
$previewType=(string)($_GET['preview']??'sales_pipeline');$preview=reportRows($pdo,$previewType,['limit'=>20]);
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Analytics Drilldown</div><h2 class="h4 mb-1">Report Drilldowns</h2><p class="text-secondary mb-0">Create drilldown definitions and preview source datasets.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Create Drilldown</h2><input class="form-control mb-2" name="title" placeholder="Drilldown title"><select class="form-select mb-2" name="source_type"><option>kpi</option><option>dashboard</option><option>report</option><option>module</option></select><input class="form-control mb-2" type="number" name="source_id" placeholder="Source ID"><select class="form-select mb-2" name="drilldown_type"><option>table</option><option>chart</option><option>timeline</option><option>detail</option></select><select class="form-select mb-2" name="query_type"><?php foreach($types as $k=>$v): ?><option value="<?php echo esc($k); ?>"><?php echo esc($v); ?></option><?php endforeach; ?></select><textarea class="form-control mb-3" name="config_json" rows="4">{}</textarea><button class="btn btn-brand w-100">Create</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Definitions</h2><table class="table"><thead><tr><th>Drilldown</th><th>Source</th><th>Type</th><th>Query</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?php echo esc($r['drilldown_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['title']); ?></div></td><td><?php echo esc($r['source_type'].' #'.$r['source_id']); ?></td><td><?php echo esc($r['drilldown_type']); ?></td><td><?php echo esc($r['query_type']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Preview: <?php echo esc($previewType); ?></h2><table class="table table-sm"><?php if($preview): ?><thead><tr><?php foreach(array_keys($preview[0]) as $h): ?><th><?php echo esc($h); ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach($preview as $row): ?><tr><?php foreach($row as $v): ?><td><?php echo esc((string)$v); ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody><?php else: ?><tbody><tr><td class="text-secondary">No rows.</td></tr></tbody><?php endif; ?></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>