<?php
$pageTitle='Report Storyboards';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('report_storyboards');
$pdo=getDB();$reports=$pdo->query('SELECT * FROM '.table('saved_reports').' WHERE active=1 ORDER BY report_name LIMIT 200')->fetchAll();$kpis=$pdo->query('SELECT * FROM '.table('report_kpis').' WHERE active=1 ORDER BY kpi_name LIMIT 200')->fetchAll();$boards=$pdo->query('SELECT * FROM '.table('report_storyboards').' ORDER BY created_at DESC LIMIT 100')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{$action=(string)($_POST['action']??'board');if($action==='slide'){$pdo->prepare('INSERT INTO '.table('report_storyboard_slides').' (report_storyboard_id,slide_title,slide_type,reference_type,reference_id,sort_order,notes) VALUES (?,?,?,?,?,?,?)')->execute([(int)$_POST['report_storyboard_id'],trim((string)$_POST['slide_title']),trim((string)$_POST['slide_type']),trim((string)$_POST['reference_type']),(int)$_POST['reference_id']?:null,(int)$_POST['sort_order'],trim((string)$_POST['notes'])]);flash('success','Storyboard slide added.');}else{$number=nextScopedDocumentNumber($pdo,'report_storyboard',setting('report_storyboard_prefix','STORY'),operationalScope($pdo));$user=currentUser();$pdo->prepare('INSERT INTO '.table('report_storyboards').' (storyboard_number,storyboard_title,audience,status,created_by) VALUES (?,?,?,"draft",?)')->execute([$number,trim((string)$_POST['storyboard_title']),trim((string)$_POST['audience']),(int)($user['id']??0)?:null]);flash('success','Storyboard created.');}}
  catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'report-storyboards']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/report-storyboards.php');
}
$slides=$pdo->query('SELECT s.*,b.storyboard_number FROM '.table('report_storyboard_slides').' s LEFT JOIN '.table('report_storyboards').' b ON b.id=s.report_storyboard_id ORDER BY b.created_at DESC,s.sort_order ASC LIMIT 200')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Management Presentation Pack</div><h2 class="h4 mb-1">Report Storyboards</h2><p class="text-secondary mb-0">Build board-meeting style storyboards from reports, KPIs, dashboards, and commentary.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4 mb-4"><h2 class="h5 mb-3">Create Storyboard</h2><input class="form-control mb-2" name="storyboard_title" placeholder="Monthly Executive Pack"><select class="form-select mb-3" name="audience"><option>management</option><option>finance</option><option>sales</option><option>operations</option><option>board</option></select><button class="btn btn-brand w-100">Create</button></form><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="slide"><h2 class="h5 mb-3">Add Slide</h2><select class="form-select mb-2" name="report_storyboard_id"><?php foreach($boards as $b): ?><option value="<?php echo (int)$b['id']; ?>"><?php echo esc($b['storyboard_number'].' · '.$b['storyboard_title']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="slide_title" placeholder="Slide title"><select class="form-select mb-2" name="slide_type"><option>kpi</option><option>report</option><option>dashboard</option><option>commentary</option></select><select class="form-select mb-2" name="reference_type"><option>report</option><option>kpi</option><option>dashboard</option><option>manual</option></select><input class="form-control mb-2" type="number" name="reference_id" placeholder="Reference ID"><input class="form-control mb-2" type="number" name="sort_order" value="1"><textarea class="form-control mb-3" name="notes" rows="3"></textarea><button class="btn btn-outline-primary w-100">Add Slide</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Storyboards</h2><table class="table"><thead><tr><th>Storyboard</th><th>Audience</th><th>Status</th></tr></thead><tbody><?php foreach($boards as $b): ?><tr><td><strong><?php echo esc($b['storyboard_number']); ?></strong><div class="small text-secondary"><?php echo esc($b['storyboard_title']); ?></div></td><td><?php echo esc($b['audience']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($b['status'])); ?>"><?php echo esc($b['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Slides</h2><table class="table"><thead><tr><th>Storyboard</th><th>Slide</th><th>Type</th><th>Reference</th><th>Order</th></tr></thead><tbody><?php foreach($slides as $s): ?><tr><td><?php echo esc($s['storyboard_number']); ?></td><td><strong><?php echo esc($s['slide_title']); ?></strong><div class="small text-secondary"><?php echo esc($s['notes']); ?></div></td><td><?php echo esc($s['slide_type']); ?></td><td><?php echo esc($s['reference_type'].' #'.$s['reference_id']); ?></td><td><?php echo (int)$s['sort_order']; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>