<?php
$pageTitle='Returns & RMA';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('returns_rma');
$pdo=getDB();
$scopeOptions=scopeSelectOptions($pdo);
$filters=requestScopeFilters();
$status=trim((string)($_GET['status']??''));

$params=[];$where='';
if($status!==''){$where=' WHERE r.status=?';$params[]=$status;}
$condition=selectedScopeCondition('r',$params,$filters,['company_id','branch_id','warehouse_id']);$condition.=scopeQueryCondition($pdo,'r',$params,false);
if($where===''){$where=$condition!==''?' WHERE '.substr($condition,5):'';}else{$where.=$condition;}
$stmt=$pdo->prepare('SELECT r.*,c.customer_code,i.invoice_number,so.sales_order_number,dn.delivery_number FROM '.table('returns_rma').' r LEFT JOIN '.table('customers').' c ON c.id=r.customer_id LEFT JOIN '.table('invoices').' i ON i.id=r.invoice_id LEFT JOIN '.table('sales_orders').' so ON so.id=r.sales_order_id LEFT JOIN '.table('delivery_notes').' dn ON dn.id=r.delivery_note_id'.$where.' ORDER BY r.created_at DESC,r.id DESC LIMIT 250');
$stmt->execute($params);$rows=$stmt->fetchAll();
$summary=['draft'=>0,'pending_approval'=>0,'approved'=>0,'received'=>0,'rejected'=>0,'value'=>0.0];foreach($rows as $row){$k=(string)($row['status']??'');if(isset($summary[$k])){$summary[$k]++;}$summary['value']+=(float)$row['total_value'];}
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Customer Returns</div><h2 class="h4 mb-1">Returns & RMA</h2><p class="text-secondary mb-0">Control return authorization, approvals, stock restocking, and follow-up credit note preparation.</p></div><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/create-return-rma.php">Create RMA</a></div>
<div class="row g-4 mb-4"><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Return Value</div><div class="metric-sm"><?php echo money($summary['value']); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Pending Approval</div><div class="metric-sm"><?php echo (int)$summary['pending_approval']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Approved</div><div class="metric-sm money-positive"><?php echo (int)$summary['approved']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Received</div><div class="metric-sm"><?php echo (int)$summary['received']; ?></div></div></div></div>
<div class="card-admin p-3 mb-4"><form class="d-flex flex-wrap gap-2 align-items-end"><div><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option><?php foreach(['draft','pending_approval','approved','received','credited','rejected','cancelled'] as $filter): ?><option value="<?php echo esc($filter); ?>" <?php echo $status===$filter?'selected':''; ?>><?php echo esc(str_replace('_',' ',ucwords($filter,'_'))); ?></option><?php endforeach; ?></select></div><div><label class="form-label">Company</label><select class="form-select" name="company_id"><option value="0">All</option><?php foreach($scopeOptions['companies'] as $company): ?><option value="<?php echo (int)$company['id']; ?>" <?php echo (int)$filters['company_id']===(int)$company['id']?'selected':''; ?>><?php echo esc($company['company_code'].' · '.$company['company_name']); ?></option><?php endforeach; ?></select></div><div><label class="form-label">Branch</label><select class="form-select" name="branch_id"><option value="0">All</option><?php foreach($scopeOptions['branches'] as $branch): ?><option value="<?php echo (int)$branch['id']; ?>" <?php echo (int)$filters['branch_id']===(int)$branch['id']?'selected':''; ?>><?php echo esc($branch['branch_code'].' · '.$branch['branch_name']); ?></option><?php endforeach; ?></select></div><button class="btn btn-brand">Apply</button></form></div>
<div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">RMA Register</div><h2 class="h5 mb-0">Returns Workflow</h2></div></div><table class="table align-middle"><thead><tr><th>RMA</th><th>Customer</th><th>Source</th><th>Value</th><th>Status</th><th>Approval</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?php echo esc($row['rma_number']); ?></strong><div class="small text-secondary"><?php echo esc($row['return_date']?:substr((string)$row['created_at'],0,10)); ?></div></td><td><?php echo esc(($row['customer_code']? $row['customer_code'].' · ' : '').'Customer'); ?></td><td><div>Invoice <?php echo esc($row['invoice_number']?:'—'); ?></div><div class="small text-secondary">SO <?php echo esc($row['sales_order_number']?:'—'); ?> · DN <?php echo esc($row['delivery_number']?:'—'); ?></div></td><td><?php echo money($row['total_value']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($row['status'])); ?>"><?php echo esc(str_replace('_',' ',ucwords($row['status'],'_'))); ?></span></td><td><span class="badge bg-<?php echo esc(statusTone($row['approval_status'])); ?>"><?php echo esc(str_replace('_',' ',ucwords($row['approval_status'],'_'))); ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/view-return-rma.php?id=<?php echo (int)$row['id']; ?>">Open</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="7" class="text-secondary">No RMAs found.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>