<?php
$pageTitle='Sales Pipeline';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('sales_pipeline');
$pdo=getDB();
$scope=operationalScope($pdo);$scopeOptions=scopeSelectOptions($pdo);
$stages=$pdo->query('SELECT * FROM '.table('sales_pipeline_stages').' WHERE status="active" ORDER BY sort_order')->fetchAll();
$leads=$pdo->query('SELECT id,name,company,estimated_value,probability FROM '.table('crm_leads').' WHERE converted_customer_id IS NULL ORDER BY created_at DESC LIMIT 300')->fetchAll();
$customers=$pdo->query('SELECT id,customer_code,company_name,contact_name FROM '.table('customers').' WHERE status="active" ORDER BY company_name,contact_name LIMIT 300')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'');
    if($action==='create'){
      $scope=['company_id'=>(int)($_POST['company_id']??$scope['company_id']),'branch_id'=>(int)($_POST['branch_id']??$scope['branch_id']),'warehouse_id'=>(int)setting('default_warehouse_id','0'),'location_id'=>(int)setting('default_location_id','0')];
      $number=nextScopedDocumentNumber($pdo,'sales_opportunity',setting('sales_opportunity_prefix','OPP'),$scope);
      $value=max(0,(float)($_POST['value_amount']??0));$prob=max(0,min(100,(int)($_POST['probability']??0)));$weighted=round($value*$prob/100,2);
      $stmt=$pdo->prepare('INSERT INTO '.table('sales_opportunities').' (company_id,branch_id,opportunity_number,lead_id,customer_id,stage_id,owner_user_id,title,source,value_amount,probability,weighted_value,expected_close_date,status,next_follow_up,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,"open",?,?)');
      $user=currentUser();
      $stmt->execute([$scope['company_id']?:null,$scope['branch_id']?:null,$number,(int)($_POST['lead_id']??0)?:null,(int)($_POST['customer_id']??0)?:null,(int)($_POST['stage_id']??0)?:null,(int)($user['id']??0)?:null,trim((string)$_POST['title']),trim((string)$_POST['source']),$value,$prob,$weighted,trim((string)($_POST['expected_close_date']??''))?:null,trim((string)($_POST['next_follow_up']??''))?:null,trim((string)($_POST['notes']??''))]);
      flash('success','Opportunity created.');
    }elseif($action==='move'){
      $id=(int)$_POST['id'];$stageId=(int)$_POST['stage_id'];
      $stage=$pdo->prepare('SELECT * FROM '.table('sales_pipeline_stages').' WHERE id=? LIMIT 1');$stage->execute([$stageId]);$stageRow=$stage->fetch();
      if(!$stageRow){throw new RuntimeException('Stage not found.');}
      $status=!empty($stageRow['is_won'])?'won':(!empty($stageRow['is_lost'])?'lost':'open');
      $pdo->prepare('UPDATE '.table('sales_opportunities').' SET stage_id=?,probability=?,weighted_value=ROUND(value_amount*?/100,2),status=?,last_activity_at=NOW() WHERE id=?')->execute([$stageId,(int)$stageRow['probability'],(int)$stageRow['probability'],$status,$id]);
      flash('success','Opportunity stage updated.');
    }
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'sales-pipeline']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/sales-pipeline.php');
}
$opps=$pdo->query('SELECT o.*,s.stage_name,l.name lead_name,c.customer_code,c.company_name,c.contact_name FROM '.table('sales_opportunities').' o LEFT JOIN '.table('sales_pipeline_stages').' s ON s.id=o.stage_id LEFT JOIN '.table('crm_leads').' l ON l.id=o.lead_id LEFT JOIN '.table('customers').' c ON c.id=o.customer_id ORDER BY o.created_at DESC LIMIT 250')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Opportunity Management</div><h2 class="h4 mb-1">Sales Pipeline</h2><p class="text-secondary mb-0">Create, move, and forecast sales opportunities from leads and customers.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/advanced-crm.php"><?php echo t('Advanced CRM', 'CRM متقدم'); ?></a></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="create"><h2 class="h5 mb-3">Create Opportunity</h2><label class="form-label">Company</label><select class="form-select mb-2" name="company_id"><?php foreach($scopeOptions['companies'] as $company): ?><option value="<?php echo (int)$company['id']; ?>" <?php echo (int)$scope['company_id']===(int)$company['id']?'selected':''; ?>><?php echo esc($company['company_code'].' · '.$company['company_name']); ?></option><?php endforeach; ?></select><label class="form-label">Branch</label><select class="form-select mb-2" name="branch_id"><?php foreach($scopeOptions['branches'] as $branch): ?><option value="<?php echo (int)$branch['id']; ?>" <?php echo (int)$scope['branch_id']===(int)$branch['id']?'selected':''; ?>><?php echo esc($branch['branch_code'].' · '.$branch['branch_name']); ?></option><?php endforeach; ?></select><label class="form-label">Title</label><input class="form-control mb-2" name="title" required><label class="form-label">Lead</label><select class="form-select mb-2" name="lead_id"><option value="0">No lead</option><?php foreach($leads as $lead): ?><option value="<?php echo (int)$lead['id']; ?>"><?php echo esc($lead['name'].' · '.$lead['company']); ?></option><?php endforeach; ?></select><label class="form-label">Customer</label><select class="form-select mb-2" name="customer_id"><option value="0">No customer</option><?php foreach($customers as $customer): ?><option value="<?php echo (int)$customer['id']; ?>"><?php echo esc($customer['customer_code'].' · '.trim(($customer['company_name']?:'').' '.$customer['contact_name'])); ?></option><?php endforeach; ?></select><label class="form-label">Stage</label><select class="form-select mb-2" name="stage_id"><?php foreach($stages as $stage): ?><option value="<?php echo (int)$stage['id']; ?>"><?php echo esc($stage['stage_name']); ?></option><?php endforeach; ?></select><div class="row g-2"><div class="col-6"><label class="form-label">Value</label><input class="form-control" type="number" step="0.01" name="value_amount" value="0"></div><div class="col-6"><label class="form-label">Probability %</label><input class="form-control" type="number" min="0" max="100" name="probability" value="30"></div></div><label class="form-label mt-2">Expected Close</label><input class="form-control mb-2" type="date" name="expected_close_date"><label class="form-label">Next Follow-up</label><input class="form-control mb-2" type="date" name="next_follow_up"><label class="form-label">Source</label><input class="form-control mb-2" name="source"><label class="form-label">Notes</label><textarea class="form-control mb-3" name="notes" rows="3"></textarea><button class="btn btn-brand w-100">Create Opportunity</button></form></div>
<div class="col-xl-8"><div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Pipeline Register</div><h2 class="h5 mb-0">Opportunities</h2></div></div><table class="table align-middle"><thead><tr><th>Opportunity</th><th>Account</th><th>Stage</th><th>Value</th><th>Weighted</th><th>Move</th></tr></thead><tbody><?php foreach($opps as $opp): ?><tr><td><strong><?php echo esc($opp['opportunity_number']); ?></strong><div class="small text-secondary"><?php echo esc($opp['title']); ?></div></td><td><?php echo esc($opp['lead_name'] ?: trim(($opp['customer_code']?:'').' '.($opp['company_name']?:$opp['contact_name']))); ?></td><td><span class="badge bg-<?php echo esc(statusTone($opp['status'])); ?>"><?php echo esc($opp['stage_name']?:$opp['status']); ?></span></td><td><?php echo money($opp['value_amount']); ?></td><td><?php echo money($opp['weighted_value']); ?></td><td><form method="post" class="d-flex gap-2"><input type="hidden" name="action" value="move"><input type="hidden" name="id" value="<?php echo (int)$opp['id']; ?>"><select class="form-select form-select-sm" name="stage_id"><?php foreach($stages as $stage): ?><option value="<?php echo (int)$stage['id']; ?>" <?php echo (int)$opp['stage_id']===(int)$stage['id']?'selected':''; ?>><?php echo esc($stage['stage_name']); ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-outline-primary">Move</button></form></td></tr><?php endforeach; ?><?php if(!$opps): ?><tr><td colspan="6" class="text-secondary">No opportunities yet.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>