<?php
$pageTitle='Security Policies';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('security_policy_center');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'ip');
    if($action==='ip'){$number=nextScopedDocumentNumber($pdo,'ip_rule',setting('ip_rule_prefix','IPR'),operationalScope($pdo));$user=currentUser();$pdo->prepare('INSERT INTO '.table('ip_access_rules').' (rule_number,rule_type,ip_address,cidr_range,description,status,created_by) VALUES (?,?,?,?,?,?,?)')->execute([$number,trim((string)$_POST['rule_type']),trim((string)$_POST['ip_address']),trim((string)$_POST['cidr_range']),trim((string)$_POST['description']),trim((string)$_POST['status']),(int)($user['id']??0)?:null]);flash('success','IP access rule created.');}
    elseif($action==='2fa'){$pdo->prepare('INSERT INTO '.table('two_factor_auth_secrets').' (user_id,secret_label,secret_hash,enabled) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE secret_label=VALUES(secret_label),enabled=VALUES(enabled)')->execute([(int)$_POST['user_id'],trim((string)$_POST['secret_label']),hash('sha256',trim((string)$_POST['secret_hash'])),(int)($_POST['enabled']??0)]);flash('success','2FA foundation record saved.');}
    else{$pdo->prepare('INSERT INTO '.table('password_policy_rules').' (rule_key,rule_name,rule_value,enabled,description,updated_by,updated_at) VALUES (?,?,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE rule_name=VALUES(rule_name),rule_value=VALUES(rule_value),enabled=VALUES(enabled),description=VALUES(description),updated_by=VALUES(updated_by),updated_at=NOW()')->execute([trim((string)$_POST['rule_key']),trim((string)$_POST['rule_name']),trim((string)$_POST['rule_value']),(int)($_POST['enabled']??1),trim((string)$_POST['description']),(int)(currentUser()['id']??0)?:null]);flash('success','Password policy rule saved.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'security-policies']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/security-policies.php');
}
$ip=$pdo->query('SELECT * FROM '.table('ip_access_rules').' ORDER BY created_at DESC LIMIT 150')->fetchAll();
$policies=$pdo->query('SELECT * FROM '.table('password_policy_rules').' ORDER BY rule_key LIMIT 100')->fetchAll();
$twofa=$pdo->query('SELECT t.*,u.email FROM '.table('two_factor_auth_secrets').' t LEFT JOIN '.table('users').' u ON u.id=t.user_id ORDER BY t.created_at DESC LIMIT 100')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Security Control Panel</div><h2 class="h4 mb-1">Security Policies</h2><p class="text-secondary mb-0">Manage password policy records, IP access rules, and two-factor authentication foundation.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4 mb-4"><input type="hidden" name="action" value="ip"><h2 class="h5 mb-3">IP Access Rule</h2><select class="form-select mb-2" name="rule_type"><option>allow</option><option>block</option></select><input class="form-control mb-2" name="ip_address" placeholder="IP address"><input class="form-control mb-2" name="cidr_range" placeholder="CIDR range"><textarea class="form-control mb-2" name="description" rows="2"></textarea><select class="form-select mb-3" name="status"><option>active</option><option>inactive</option></select><button class="btn btn-brand w-100">Add IP Rule</button></form><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="policy"><h2 class="h5 mb-3">Password Policy Rule</h2><input class="form-control mb-2" name="rule_key" placeholder="min_length"><input class="form-control mb-2" name="rule_name" placeholder="Minimum length"><input class="form-control mb-2" name="rule_value" placeholder="10"><select class="form-select mb-2" name="enabled"><option value="1">enabled</option><option value="0">disabled</option></select><textarea class="form-control mb-3" name="description" rows="2"></textarea><button class="btn btn-outline-primary w-100">Save Policy</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">IP Rules</h2><table class="table"><thead><tr><th>Rule</th><th>Type</th><th>IP/CIDR</th><th>Status</th></tr></thead><tbody><?php foreach($ip as $r): ?><tr><td><strong><?php echo esc($r['rule_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['description']); ?></div></td><td><?php echo esc($r['rule_type']); ?></td><td><?php echo esc($r['ip_address'].' '.$r['cidr_range']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Password Policies</h2><table class="table"><thead><tr><th>Rule</th><th>Value</th><th>Status</th></tr></thead><tbody><?php foreach($policies as $p): ?><tr><td><strong><?php echo esc($p['rule_key']); ?></strong><div class="small text-secondary"><?php echo esc($p['description']); ?></div></td><td><?php echo esc($p['rule_value']); ?></td><td><span class="badge bg-<?php echo $p['enabled']?'success':'secondary'; ?>"><?php echo $p['enabled']?'enabled':'disabled'; ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>