<?php
$pageTitle='Sensitive Action Approvals';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('sensitive_action_approvals');
$pdo=getDB();$user=currentUser();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'create');
    if($action==='decision'){$status=trim((string)$_POST['status']);$pdo->prepare('UPDATE '.table('sensitive_action_approvals').' SET status=?,approved_by=?,approved_at=CASE WHEN ?="approved" THEN NOW() ELSE approved_at END,rejected_at=CASE WHEN ?="rejected" THEN NOW() ELSE rejected_at END,notes=? WHERE id=?')->execute([$status,(int)($user['id']??0)?:null,$status,$status,trim((string)$_POST['notes']),(int)$_POST['id']]);flash('success','Sensitive approval updated.');}
    else{createSensitiveActionApproval($pdo,trim((string)$_POST['action_key']),trim((string)$_POST['module']),trim((string)$_POST['reference_type']),(int)($_POST['reference_id']??0)?:null,trim((string)$_POST['reason']),trim((string)$_POST['risk_level']));flash('success','Sensitive action approval requested.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'sensitive-action-approvals']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/sensitive-action-approvals.php');
}
$rows=$pdo->query('SELECT s.*,r.email requester,a.email approver FROM '.table('sensitive_action_approvals').' s LEFT JOIN '.table('users').' r ON r.id=s.requested_by LEFT JOIN '.table('users').' a ON a.id=s.approved_by ORDER BY FIELD(s.status,"pending","approved","rejected"),s.created_at DESC LIMIT 250')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">High-Risk Operation Control</div><h2 class="h4 mb-1">Sensitive Action Approvals</h2><p class="text-secondary mb-0">Maker-checker foundation for risky actions like delete, export, role changes and finance override.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Request Approval</h2><input class="form-control mb-2" name="action_key" placeholder="delete_invoice / export_customers"><input class="form-control mb-2" name="module" placeholder="Finance / Users / Reports"><input class="form-control mb-2" name="reference_type" placeholder="invoice / user / report"><input class="form-control mb-2" type="number" name="reference_id" placeholder="Reference ID"><select class="form-select mb-2" name="risk_level"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select><textarea class="form-control mb-3" name="reason" rows="4" placeholder="Reason"></textarea><button class="btn btn-brand w-100">Request</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Approval</th><th>Action</th><th>Risk</th><th>Status</th><th>Decision</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?php echo esc($r['approval_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['requester'].' · '.$r['requested_at']); ?></div></td><td><?php echo esc($r['module'].' · '.$r['action_key']); ?><div class="small text-secondary"><?php echo esc($r['reason']); ?></div></td><td><span class="badge bg-<?php echo esc(statusTone($r['risk_level'])); ?>"><?php echo esc($r['risk_level']); ?></span></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td><td><?php if($r['status']==='pending'): ?><form method="post" class="d-flex gap-1"><input type="hidden" name="action" value="decision"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><select class="form-select form-select-sm" name="status"><option>approved</option><option>rejected</option></select><input class="form-control form-control-sm" name="notes" placeholder="Notes"><button class="btn btn-sm btn-outline-primary">Save</button></form><?php else: ?><?php echo esc($r['approver']); ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>