<?php
$pageTitle='Service Contracts / AMC';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('service_contracts');
$pdo=getDB();
$scope=operationalScope($pdo);
$customers=$pdo->query('SELECT id,customer_code,company_name,contact_name FROM '.table('customers').' WHERE status="active" ORDER BY company_name,contact_name LIMIT 400')->fetchAll();
$costCenters=$pdo->query('SELECT id,cost_center_code,cost_center_name FROM '.table('cost_centers').' WHERE status="active" ORDER BY cost_center_code')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $number=nextScopedDocumentNumber($pdo,'service_contract','AMC',$scope);
    $customerId=(int)($_POST['customer_id']??0)?:null;$customerName=trim((string)($_POST['customer_name']??''));
    if($customerId){$s=$pdo->prepare('SELECT company_name,contact_name FROM '.table('customers').' WHERE id=?');$s->execute([$customerId]);$c=$s->fetch();if($c){$customerName=trim(($c['company_name']?:'').' '.($c['contact_name']?:''));}}
    $stmt=$pdo->prepare('INSERT INTO '.table('service_contracts').' (company_id,branch_id,cost_center_id,contract_number,customer_id,customer_name,contract_type,start_date,end_date,contract_value,billing_frequency,next_billing_date,visits_included,response_sla_hours,status,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,"active",?)');
    $stmt->execute([(int)$scope['company_id']?:null,(int)$scope['branch_id']?:null,(int)($_POST['cost_center_id']??0)?:null,$number,$customerId,$customerName,trim((string)($_POST['contract_type']??'AMC')),trim((string)($_POST['start_date']??date('Y-m-d'))),trim((string)($_POST['end_date']??''))?:null,max(0,(float)($_POST['contract_value']??0)),trim((string)($_POST['billing_frequency']??'monthly')),trim((string)($_POST['next_billing_date']??''))?:null,max(0,(int)($_POST['visits_included']??0)),max(1,(int)($_POST['response_sla_hours']??24)),trim((string)($_POST['notes']??''))]);
    logActivity($pdo,'Contracts','service_contract_created','Service contract '.$number.' created.','service_contract',(int)$pdo->lastInsertId());
    flash('success','Service contract created.');
  }catch(Throwable $e){flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/service-contracts.php');
}
$rows=$pdo->query('SELECT sc.*,cc.cost_center_code FROM '.table('service_contracts').' sc LEFT JOIN '.table('cost_centers').' cc ON cc.id=sc.cost_center_id ORDER BY sc.status DESC,sc.created_at DESC LIMIT 300')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Recurring Service</div><h2 class="h4 mb-1">Service Contracts / AMC</h2><p class="text-secondary mb-0">Track annual maintenance contracts, SLA, included visits, billing cycle, and next billing date.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5">Create Contract</h2><label class="form-label">Customer</label><select class="form-select mb-2" name="customer_id"><option value="0">Manual</option><?php foreach($customers as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo esc($c['customer_code'].' · '.trim(($c['company_name']?:'').' '.($c['contact_name']?:''))); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="customer_name" placeholder="Manual customer name"><select class="form-select mb-2" name="cost_center_id"><option value="0">Cost center</option><?php foreach($costCenters as $cc): ?><option value="<?php echo (int)$cc['id']; ?>"><?php echo esc($cc['cost_center_code'].' · '.$cc['cost_center_name']); ?></option><?php endforeach; ?></select><div class="row g-2"><div class="col-6"><label class="form-label">Type</label><input class="form-control" name="contract_type" value="AMC"></div><div class="col-6"><label class="form-label">Value</label><input class="form-control" type="number" step="0.01" name="contract_value"></div><div class="col-6"><label class="form-label">Start</label><input class="form-control" type="date" name="start_date" value="<?php echo esc(date('Y-m-d')); ?>"></div><div class="col-6"><label class="form-label">End</label><input class="form-control" type="date" name="end_date"></div><div class="col-6"><label class="form-label">Visits</label><input class="form-control" type="number" name="visits_included" value="4"></div><div class="col-6"><label class="form-label">SLA Hours</label><input class="form-control" type="number" name="response_sla_hours" value="24"></div></div><textarea class="form-control my-2" name="notes" rows="3" placeholder="Scope and exclusions"></textarea><button class="btn btn-brand w-100">Create Contract</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Contract Register</div><h2 class="h5 mb-0">AMC / Recurring Services</h2></div></div><table class="table align-middle"><thead><tr><th>Contract</th><th>Customer</th><th>Period</th><th>Visits</th><th>Value</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?php echo esc($row['contract_number']); ?></strong><div class="small text-secondary"><?php echo esc($row['contract_type'].' · '.$row['cost_center_code']); ?></div></td><td><?php echo esc($row['customer_name']); ?></td><td><?php echo esc($row['start_date'].' → '.($row['end_date']?:'Open')); ?></td><td><?php echo (int)$row['visits_used']; ?> / <?php echo (int)$row['visits_included']; ?></td><td><?php echo money($row['contract_value']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($row['status'])); ?>"><?php echo esc($row['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>