<?php
$pageTitle='Supplier Statement';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('accounting');
$pdo=getDB();
$id=(int)($_GET['id']??0);
$stmt=$pdo->prepare('SELECT * FROM ' . table('suppliers') . ' WHERE id=? LIMIT 1');$stmt->execute([$id]);$supplier=$stmt->fetch();
if(!$supplier){flash('error','Supplier not found.');redirect(ADMIN_URL.'/erp/ap-supplier-ledger.php');}
$entries=[];
$stmt=$pdo->prepare('SELECT id,expense_number doc_number,total,amount_paid,expense_date doc_date,payment_status status FROM ' . table('expenses') . ' WHERE supplier_id=?');$stmt->execute([$id]);foreach($stmt->fetchAll() as $row){$entries[]=['date'=>$row['doc_date'],'type'=>'Expense / Payable','doc'=>$row['doc_number'],'debit'=>0,'credit'=>(float)$row['total'],'link'=>ADMIN_URL.'/erp/finance.php','status'=>$row['status']];if((float)$row['amount_paid']>0){$entries[]=['date'=>$row['doc_date'],'type'=>'Expense Paid','doc'=>$row['doc_number'],'debit'=>(float)$row['amount_paid'],'credit'=>0,'link'=>ADMIN_URL.'/erp/finance.php','status'=>'paid'];}}
$stmt=$pdo->prepare('SELECT id,debit_note_number doc_number,total,issue_date doc_date,status FROM ' . table('debit_notes') . ' WHERE supplier_id=? AND status="approved"');$stmt->execute([$id]);foreach($stmt->fetchAll() as $row){$entries[]=['date'=>$row['doc_date'],'type'=>'Debit Note','doc'=>$row['doc_number'],'debit'=>(float)$row['total'],'credit'=>0,'link'=>ADMIN_URL.'/erp/view-debit-note.php?id='.(int)$row['id'],'status'=>$row['status']];}
usort($entries,fn($a,$b)=>strcmp((string)$a['date'].'-'.$a['type'],(string)$b['date'].'-'.$b['type']));
$running=0;$debits=0;$credits=0;foreach($entries as &$entry){$debits+=$entry['debit'];$credits+=$entry['credit'];$running+=$entry['credit']-$entry['debit'];$entry['balance']=$running;}unset($entry);
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><div class="erp-kicker">Supplier Statement</div><h2 class="h4 mb-1"><?php echo esc($supplier['supplier_code'].' · '.$supplier['company_name']); ?></h2><p class="text-secondary mb-0"><?php echo esc($supplier['email'].' · '.$supplier['phone']); ?></p></div><div class="d-flex gap-2 flex-wrap"><a class="btn btn-outline-dark" href="<?php echo esc(ADMIN_URL); ?>/erp/ap-supplier-ledger.php">Back to AP Ledger</a><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/create-debit-note.php?supplier_id=<?php echo (int)$supplier['id']; ?>">Create Debit Note</a></div></div>
<div class="row g-4 mb-4"><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Credits / Payables</div><div class="metric-sm"><?php echo money($credits); ?></div></div></div><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Paid + Debit Notes</div><div class="metric-sm"><?php echo money($debits); ?></div></div></div><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Closing AP</div><div class="metric-sm <?php echo $running>0?'money-negative':'money-positive'; ?>"><?php echo money($running); ?></div></div></div></div>
<div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Date</th><th>Type</th><th>Document</th><th>Debit</th><th>Credit</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach($entries as $entry): ?><tr><td><?php echo esc($entry['date']); ?></td><td><?php echo esc($entry['type']); ?></td><td><a href="<?php echo esc($entry['link']); ?>"><?php echo esc($entry['doc']); ?></a></td><td><?php echo money($entry['debit']); ?></td><td><?php echo money($entry['credit']); ?></td><td><?php echo money($entry['balance']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($entry['status'])); ?>"><?php echo esc($entry['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$entries): ?><tr><td colspan="7" class="text-secondary">No supplier statement entries found.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>