<?php
$pageTitle='Supplier Onboarding';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('supplier_onboarding');
$pdo=getDB();$suppliers=$pdo->query('SELECT id,supplier_code,company_name FROM '.table('suppliers').' ORDER BY company_name LIMIT 300')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    if(($_POST['action']??'')==='approve'){$user=currentUser();$pdo->prepare('UPDATE '.table('supplier_onboarding_requests').' SET status="approved",approved_by=?,approved_at=NOW() WHERE id=?')->execute([(int)($user['id']??0)?:null,(int)$_POST['id']]);flash('success','Supplier onboarding approved.');}
    else{createSupplierOnboarding($pdo,$_POST);flash('success','Supplier onboarding request created.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'supplier-onboarding']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/supplier-onboarding.php');
}
$rows=$pdo->query('SELECT o.*,s.company_name existing_supplier FROM '.table('supplier_onboarding_requests').' o LEFT JOIN '.table('suppliers').' s ON s.id=o.supplier_id ORDER BY o.created_at DESC LIMIT 150')->fetchAll();
$steps=$pdo->query('SELECT st.*,o.onboarding_number FROM '.table('supplier_onboarding_steps').' st LEFT JOIN '.table('supplier_onboarding_requests').' o ON o.id=st.supplier_onboarding_request_id ORDER BY st.created_at DESC LIMIT 150')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Supplier Qualification</div><h2 class="h4 mb-1">Supplier Onboarding</h2><p class="text-secondary mb-0">Create onboarding requests, risk category, required checklist steps, and approval record.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Create Onboarding</h2><select class="form-select mb-2" name="supplier_id"><option value="0">New supplier / not linked</option><?php foreach($suppliers as $s): ?><option value="<?php echo (int)$s['id']; ?>"><?php echo esc($s['supplier_code'].' · '.$s['company_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="company_name" placeholder="Company name"><input class="form-control mb-2" name="contact_name" placeholder="Contact name"><input class="form-control mb-2" type="email" name="email" placeholder="Email"><input class="form-control mb-2" name="phone" placeholder="Phone"><input class="form-control mb-2" name="tax_number" placeholder="Tax number"><input class="form-control mb-2" name="category" placeholder="Category"><select class="form-select mb-2" name="risk_level"><option value="low">Low Risk</option><option value="medium" selected>Medium Risk</option><option value="high">High Risk</option></select><textarea class="form-control mb-3" name="notes" rows="3"></textarea><button class="btn btn-brand w-100">Create Request</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Onboarding Requests</h2><table class="table align-middle"><thead><tr><th>Request</th><th>Company</th><th>Risk</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?php echo esc($r['onboarding_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['category']); ?></div></td><td><?php echo esc($r['company_name']?:$r['existing_supplier']); ?><div class="small text-secondary"><?php echo esc($r['email']); ?></div></td><td><?php echo esc($r['risk_level']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td><td><?php if($r['status']!=='approved'): ?><form method="post"><input type="hidden" name="action" value="approve"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><button class="btn btn-sm btn-success">Approve</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Checklist Steps</h2><table class="table"><thead><tr><th>Onboarding</th><th>Step</th><th>Status</th></tr></thead><tbody><?php foreach($steps as $s): ?><tr><td><?php echo esc($s['onboarding_number']); ?></td><td><?php echo esc($s['step_name']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($s['status'])); ?>"><?php echo esc($s['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>