<?php
$pageTitle='Supplier Scorecards';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('supplier_scorecards');
$pdo=getDB();$suppliers=$pdo->query('SELECT id,supplier_code,company_name FROM '.table('suppliers').' WHERE status="active" ORDER BY company_name LIMIT 400')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){try{createSupplierScorecard($pdo,(int)$_POST['supplier_id'],trim((string)$_POST['period_label']),max(0,(float)$_POST['quality_score']),max(0,(float)$_POST['delivery_score']),max(0,(float)$_POST['price_score']),max(0,(float)$_POST['response_score']),max(0,(float)$_POST['compliance_score']),trim((string)$_POST['notes']));flash('success','Supplier scorecard published.');}catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'supplier-scorecards']);flash('error',$e->getMessage());}redirect(ADMIN_URL.'/erp/supplier-scorecards.php');}
$rows=$pdo->query('SELECT sc.*,s.company_name,s.supplier_code FROM '.table('supplier_scorecards').' sc LEFT JOIN '.table('suppliers').' s ON s.id=sc.supplier_id ORDER BY sc.created_at DESC LIMIT 150')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Vendor Performance</div><h2 class="h4 mb-1">Supplier Scorecards</h2><p class="text-secondary mb-0">Rate quality, delivery, price competitiveness, response, and compliance.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><h2 class="h5 mb-3">Create Scorecard</h2><select class="form-select mb-2" name="supplier_id"><?php foreach($suppliers as $s): ?><option value="<?php echo (int)$s['id']; ?>"><?php echo esc($s['supplier_code'].' · '.$s['company_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="period_label" value="<?php echo esc(date('Y-m')); ?>"><input class="form-control mb-2" type="number" step="0.01" name="quality_score" placeholder="Quality score"><input class="form-control mb-2" type="number" step="0.01" name="delivery_score" placeholder="Delivery score"><input class="form-control mb-2" type="number" step="0.01" name="price_score" placeholder="Price score"><input class="form-control mb-2" type="number" step="0.01" name="response_score" placeholder="Response score"><input class="form-control mb-2" type="number" step="0.01" name="compliance_score" placeholder="Compliance score"><textarea class="form-control mb-3" name="notes" rows="3"></textarea><button class="btn btn-brand w-100">Publish Scorecard</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Scorecard</th><th>Supplier</th><th>Total</th><th>Rating</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?php echo esc($r['scorecard_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['period_label']); ?></div></td><td><?php echo esc($r['supplier_code'].' · '.$r['company_name']); ?></td><td><?php echo number_format((float)$r['total_score'],2); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['rating']==='D'?'danger':'published')); ?>"><?php echo esc($r['rating']); ?></span></td><td><?php echo esc($r['status']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>