<?php
$pageTitle='Supplier Invoices & 3-Way Match';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('supplier_invoices');
$pdo=getDB();
$scopeOptions=scopeSelectOptions($pdo);
$filters=requestScopeFilters();
$status=trim((string)($_GET['status']??''));

$params=[];$where='';
if($status!==''){$where=' WHERE si.status=?';$params[]=$status;}
$condition=selectedScopeCondition('si',$params,$filters,['company_id','branch_id','warehouse_id']);$condition.=scopeQueryCondition($pdo,'si',$params,false);
if($where===''){$where=$condition!==''?' WHERE '.substr($condition,5):'';}else{$where.=$condition;}
$stmt=$pdo->prepare('SELECT si.*,po.po_number,gr.grn_number,s.supplier_code FROM '.table('supplier_invoices').' si LEFT JOIN '.table('purchase_orders').' po ON po.id=si.purchase_order_id LEFT JOIN '.table('goods_receipts').' gr ON gr.id=si.goods_receipt_id LEFT JOIN '.table('suppliers').' s ON s.id=si.supplier_id'.$where.' ORDER BY si.created_at DESC,si.id DESC LIMIT 250');
$stmt->execute($params);$rows=$stmt->fetchAll();
$summary=['total'=>0,'matched'=>0,'variance'=>0,'pending'=>0,'posted'=>0,'value'=>0.0,'variance_value'=>0.0];
foreach($rows as $row){$summary['total']++;$summary['value']+=(float)$row['total'];if(($row['match_status']??'')==='matched'){$summary['matched']++;}if(($row['match_status']??'')==='variance'){$summary['variance']++;$summary['variance_value']+=(float)$row['difference_amount'];}if(($row['status']??'')==='pending_approval'){$summary['pending']++;}if(($row['status']??'')==='posted'){$summary['posted']++;}}
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Accounts Payable Control</div><h2 class="h4 mb-1">Supplier Invoices & Three-Way Matching</h2><p class="text-secondary mb-0">Compare purchase order, goods receipt, and supplier invoice values before posting AP journals.</p></div><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/create-supplier-invoice.php">Create Supplier Invoice</a></div>
<div class="row g-4 mb-4"><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Invoices</div><div class="metric-sm"><?php echo (int)$summary['total']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Matched</div><div class="metric-sm money-positive"><?php echo (int)$summary['matched']; ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">Variance</div><div class="metric-sm money-negative"><?php echo (int)$summary['variance']; ?></div><div class="small text-secondary"><?php echo money($summary['variance_value']); ?></div></div></div><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker">AP Value</div><div class="metric-sm"><?php echo money($summary['value']); ?></div></div></div></div>
<div class="card-admin p-3 mb-4"><form class="d-flex flex-wrap gap-2 align-items-end"><div><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option><?php foreach(['draft','matched','variance','pending_approval','approved','posted','rejected'] as $filter): ?><option value="<?php echo esc($filter); ?>" <?php echo $status===$filter?'selected':''; ?>><?php echo esc(str_replace('_',' ',ucwords($filter,'_'))); ?></option><?php endforeach; ?></select></div><div><label class="form-label">Company</label><select class="form-select" name="company_id"><option value="0">All</option><?php foreach($scopeOptions['companies'] as $company): ?><option value="<?php echo (int)$company['id']; ?>" <?php echo (int)$filters['company_id']===(int)$company['id']?'selected':''; ?>><?php echo esc($company['company_code'].' · '.$company['company_name']); ?></option><?php endforeach; ?></select></div><div><label class="form-label">Branch</label><select class="form-select" name="branch_id"><option value="0">All</option><?php foreach($scopeOptions['branches'] as $branch): ?><option value="<?php echo (int)$branch['id']; ?>" <?php echo (int)$filters['branch_id']===(int)$branch['id']?'selected':''; ?>><?php echo esc($branch['branch_code'].' · '.$branch['branch_name']); ?></option><?php endforeach; ?></select></div><button class="btn btn-brand">Apply</button></form></div>
<div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">AP Matching Register</div><h2 class="h5 mb-0">Supplier Invoice Review</h2></div></div><table class="table align-middle"><thead><tr><th>Invoice</th><th>Supplier</th><th>PO / GRN</th><th>Total</th><th>Match</th><th>Approval</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?php echo esc($row['internal_number']); ?></strong><div class="small text-secondary">Vendor: <?php echo esc($row['supplier_invoice_number']?:'—'); ?></div></td><td><?php echo esc(($row['supplier_code']? $row['supplier_code'].' · ' : '').($row['supplier_name']?:'—')); ?></td><td><?php echo esc($row['po_number']?:'—'); ?><div class="small text-secondary"><?php echo esc($row['grn_number']?:'No linked GRN'); ?></div></td><td><?php echo money($row['total']); ?><div class="small text-secondary">Variance <?php echo money($row['difference_amount']); ?></div></td><td><span class="badge bg-<?php echo esc(statusTone($row['match_status'])); ?>"><?php echo esc(str_replace('_',' ',ucwords($row['match_status'],'_'))); ?></span></td><td><span class="badge bg-<?php echo esc(statusTone($row['approval_status'])); ?>"><?php echo esc(str_replace('_',' ',ucwords($row['approval_status'],'_'))); ?></span></td><td><span class="badge bg-<?php echo esc(statusTone($row['status'])); ?>"><?php echo esc(str_replace('_',' ',ucwords($row['status'],'_'))); ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/view-supplier-invoice.php?id=<?php echo (int)$row['id']; ?>">Open</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="8" class="text-secondary">No supplier invoices found.</td></tr><?php endif; ?></tbody></table></div>
<?php include dirname(__DIR__).'/footer.php'; ?>