<?php
$pageTitle='Tax Filing';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('tax_filing');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'');
    if($action==='create_return'){createTaxReturn($pdo,trim((string)$_POST['period_name']),trim((string)$_POST['date_from']),trim((string)$_POST['date_to']),trim((string)$_POST['notes']));flash('success','Tax return created.');}
    elseif($action==='file_return'){$pdo->prepare('UPDATE '.table('tax_returns').' SET status="filed",filed_at=NOW(),filing_reference=? WHERE id=?')->execute([trim((string)$_POST['filing_reference']),(int)$_POST['id']]);flash('success','Tax return marked filed.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'tax-filing']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/tax-filing.php');
}
$from=trim((string)($_GET['from']??date('Y-m-01')));$to=trim((string)($_GET['to']??date('Y-m-t')));$summary=taxReturnSummary($pdo,$from,$to);
$returns=$pdo->query('SELECT * FROM '.table('tax_returns').' ORDER BY created_at DESC LIMIT 100')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Tax Compliance</div><h2 class="h4 mb-1">Tax Filing</h2><p class="text-secondary mb-0">Prepare VAT/tax returns from invoice output tax and approved expense input tax.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/vat-report.php"><?php echo t('VAT Report', 'تقرير ضريبة القيمة المضافة'); ?></a></div>
<div class="row g-4 mb-4"><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Output Tax</div><div class="metric-sm"><?php echo money($summary['output_tax']); ?></div></div></div><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Input Tax</div><div class="metric-sm"><?php echo money($summary['input_tax']); ?></div></div></div><div class="col-md-4"><div class="card-admin p-4"><div class="erp-kicker">Net Tax</div><div class="metric-sm <?php echo $summary['net_tax']>=0?'money-negative':'money-positive'; ?>"><?php echo money($summary['net_tax']); ?></div></div></div></div>
<div class="row g-4"><div class="col-xl-4"><form class="card-admin p-4 mb-4"><h2 class="h5 mb-3">Preview Period</h2><div class="row g-2"><div class="col-6"><label class="form-label">From</label><input class="form-control" type="date" name="from" value="<?php echo esc($from); ?>"></div><div class="col-6"><label class="form-label">To</label><input class="form-control" type="date" name="to" value="<?php echo esc($to); ?>"></div></div><button class="btn btn-outline-primary w-100 mt-3">Preview</button></form><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="create_return"><h2 class="h5 mb-3">Create Tax Return</h2><input class="form-control mb-2" name="period_name" value="<?php echo esc(date('F Y',strtotime($from))); ?>"><input type="hidden" name="date_from" value="<?php echo esc($from); ?>"><input type="hidden" name="date_to" value="<?php echo esc($to); ?>"><textarea class="form-control mb-3" name="notes" rows="3" placeholder="Filing notes"></textarea><button class="btn btn-brand w-100">Create Return from Preview</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><div class="table-toolbar"><div><div class="erp-kicker">Tax Return Register</div><h2 class="h5 mb-0">Returns</h2></div></div><table class="table align-middle"><thead><tr><th>Return</th><th>Period</th><th>Output</th><th>Input</th><th>Net</th><th>Status</th><th>File</th></tr></thead><tbody><?php foreach($returns as $r): ?><tr><td><strong><?php echo esc($r['return_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['period_name']); ?></div></td><td><?php echo esc($r['date_from'].' → '.$r['date_to']); ?></td><td><?php echo money($r['output_tax']); ?></td><td><?php echo money($r['input_tax']); ?></td><td><?php echo money($r['net_tax']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td><td><?php if($r['status']!=='filed'): ?><form method="post" class="d-flex gap-1"><input type="hidden" name="action" value="file_return"><input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>"><input class="form-control form-control-sm" name="filing_reference" placeholder="Reference"><button class="btn btn-sm btn-outline-success">File</button></form><?php else: ?><?php echo esc($r['filing_reference']); ?><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$returns): ?><tr><td colspan="7" class="text-secondary">No tax returns yet.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>