<?php
$pageTitle='Tenant Billing';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('tenant_billing');
$pdo=getDB();$subs=$pdo->query('SELECT ts.*,c.company_name,sp.plan_name FROM '.table('tenant_subscriptions').' ts LEFT JOIN '.table('companies').' c ON c.id=ts.company_id LEFT JOIN '.table('subscription_plans').' sp ON sp.id=ts.subscription_plan_id ORDER BY c.company_name')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'invoice');
    if($action==='invoice'){createSaasSubscriptionInvoice($pdo,(int)$_POST['tenant_subscription_id']);flash('success','Subscription invoice generated.');}
    elseif($action==='payment'){recordSaasSubscriptionPayment($pdo,(int)$_POST['invoice_id'],max(0,(float)$_POST['amount']),trim((string)$_POST['payment_method']),trim((string)$_POST['payment_reference']),trim((string)$_POST['notes']));flash('success','Subscription payment recorded.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'tenant-billing']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/tenant-billing.php');
}
$invoices=$pdo->query('SELECT si.*,c.company_name,sp.plan_name FROM '.table('saas_subscription_invoices').' si LEFT JOIN '.table('companies').' c ON c.id=si.company_id LEFT JOIN '.table('subscription_plans').' sp ON sp.id=si.subscription_plan_id ORDER BY si.created_at DESC LIMIT 200')->fetchAll();
$payments=$pdo->query('SELECT p.*,i.invoice_number,c.company_name FROM '.table('saas_subscription_payments').' p LEFT JOIN '.table('saas_subscription_invoices').' i ON i.id=p.saas_subscription_invoice_id LEFT JOIN '.table('companies').' c ON c.id=p.company_id ORDER BY p.created_at DESC LIMIT 100')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Subscription Billing</div><h2 class="h4 mb-1">Tenant Billing</h2><p class="text-secondary mb-0">Generate SaaS subscription invoices and record tenant payments.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4 mb-4"><input type="hidden" name="action" value="invoice"><h2 class="h5 mb-3">Generate Invoice</h2><select class="form-select mb-3" name="tenant_subscription_id"><?php foreach($subs as $s): ?><option value="<?php echo (int)$s['id']; ?>"><?php echo esc($s['company_name'].' · '.$s['subscription_number'].' · '.$s['plan_name']); ?></option><?php endforeach; ?></select><button class="btn btn-brand w-100">Generate</button></form><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="payment"><h2 class="h5 mb-3">Record Payment</h2><select class="form-select mb-2" name="invoice_id"><?php foreach($invoices as $i): ?><option value="<?php echo (int)$i['id']; ?>"><?php echo esc($i['invoice_number'].' · '.$i['company_name'].' · '.money($i['balance_due'])); ?></option><?php endforeach; ?></select><input class="form-control mb-2" type="number" step="0.01" name="amount" placeholder="Amount"><input class="form-control mb-2" name="payment_method" placeholder="Bank / card / cash"><input class="form-control mb-2" name="payment_reference" placeholder="Reference"><textarea class="form-control mb-3" name="notes" rows="2"></textarea><button class="btn btn-outline-primary w-100">Record</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Subscription Invoices</h2><table class="table"><thead><tr><th>Invoice</th><th>Tenant</th><th>Period</th><th>Total</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach($invoices as $i): ?><tr><td><strong><?php echo esc($i['invoice_number']); ?></strong><div class="small text-secondary"><?php echo esc($i['invoice_date']); ?></div></td><td><?php echo esc($i['company_name']); ?></td><td><?php echo esc($i['billing_period_start'].' → '.$i['billing_period_end']); ?></td><td><?php echo money($i['total']); ?></td><td><?php echo money($i['balance_due']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($i['status'])); ?>"><?php echo esc($i['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Payments</h2><table class="table"><thead><tr><th>Payment</th><th>Invoice</th><th>Tenant</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach($payments as $p): ?><tr><td><strong><?php echo esc($p['payment_number']); ?></strong><div class="small text-secondary"><?php echo esc($p['payment_date']); ?></div></td><td><?php echo esc($p['invoice_number']); ?></td><td><?php echo esc($p['company_name']); ?></td><td><?php echo money($p['amount']); ?></td><td><?php echo esc($p['status']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>