<?php
$pageTitle='Trial Accounts';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('trial_accounts');
$pdo=getDB();$companies=$pdo->query('SELECT id,company_code,company_name FROM '.table('companies').' ORDER BY company_name')->fetchAll();$plans=$pdo->query('SELECT id,plan_code,plan_name FROM '.table('subscription_plans').' WHERE status="active" ORDER BY monthly_price')->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'trial');
    if($action==='trial'){createSaasTrialAccount($pdo,(int)$_POST['company_id'],(int)($_POST['subscription_plan_id']??0)?:null,trim((string)$_POST['contact_name']),trim((string)$_POST['contact_email']),trim((string)$_POST['contact_phone']),trim((string)$_POST['notes']));flash('success','Trial account created.');}
    elseif($action==='convert'){$trialId=(int)$_POST['trial_id'];$subId=createTenantSubscription2($pdo,(int)$_POST['company_id'],(int)$_POST['subscription_plan_id'],'active','monthly','','','Converted from trial.');$pdo->prepare('UPDATE '.table('saas_trial_accounts').' SET status="converted",converted_subscription_id=? WHERE id=?')->execute([$subId,$trialId]);flash('success','Trial converted to paid subscription.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'trial-accounts']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/trial-accounts.php');
}
$trials=$pdo->query('SELECT t.*,c.company_name,sp.plan_name FROM '.table('saas_trial_accounts').' t LEFT JOIN '.table('companies').' c ON c.id=t.company_id LEFT JOIN '.table('subscription_plans').' sp ON sp.id=t.subscription_plan_id ORDER BY t.created_at DESC LIMIT 200')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Trial Pipeline</div><h2 class="h4 mb-1">Trial Accounts</h2><p class="text-secondary mb-0">Create trials, monitor expiry and convert trial tenants into paid subscriptions.</p></div></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="trial"><h2 class="h5 mb-3">Create Trial</h2><select class="form-select mb-2" name="company_id"><?php foreach($companies as $c): ?><option value="<?php echo (int)$c['id']; ?>"><?php echo esc($c['company_name']); ?></option><?php endforeach; ?></select><select class="form-select mb-2" name="subscription_plan_id"><option value="">No plan</option><?php foreach($plans as $p): ?><option value="<?php echo (int)$p['id']; ?>"><?php echo esc($p['plan_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-2" name="contact_name" placeholder="Contact name"><input class="form-control mb-2" name="contact_email" placeholder="Contact email"><input class="form-control mb-2" name="contact_phone" placeholder="Contact phone"><textarea class="form-control mb-3" name="notes" rows="3"></textarea><button class="btn btn-brand w-100">Create Trial</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive"><table class="table align-middle"><thead><tr><th>Trial</th><th>Tenant</th><th>Contact</th><th>Dates</th><th>Status</th><th>Convert</th></tr></thead><tbody><?php foreach($trials as $t): ?><tr><td><strong><?php echo esc($t['trial_number']); ?></strong><div class="small text-secondary"><?php echo esc($t['plan_name']); ?></div></td><td><?php echo esc($t['company_name']); ?></td><td><?php echo esc($t['contact_name']); ?><div class="small text-secondary"><?php echo esc($t['contact_email']); ?></div></td><td><?php echo esc($t['trial_start'].' → '.$t['trial_end']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($t['status'])); ?>"><?php echo esc($t['status']); ?></span></td><td><?php if($t['status']==='active'): ?><form method="post" class="d-flex gap-1"><input type="hidden" name="action" value="convert"><input type="hidden" name="trial_id" value="<?php echo (int)$t['id']; ?>"><input type="hidden" name="company_id" value="<?php echo (int)$t['company_id']; ?>"><select class="form-select form-select-sm" name="subscription_plan_id"><?php foreach($plans as $p): ?><option value="<?php echo (int)$p['id']; ?>"><?php echo esc($p['plan_name']); ?></option><?php endforeach; ?></select><button class="btn btn-sm btn-success">Convert</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>