<?php
$pageTitle='Warehouse Dashboard';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('warehouse_dashboard');
$pdo=getDB();
$stats=['bins'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('warehouse_bins'))->fetchColumn(),'lots'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('inventory_lots').' WHERE status="active"')->fetchColumn(),'serials'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('inventory_serial_numbers').' WHERE status="available"')->fetchColumn(),'pick_open'=>(int)$pdo->query('SELECT COUNT(*) FROM '.table('picking_lists').' WHERE status IN ("draft","pending","partial")')->fetchColumn()];
$low=$pdo->query('SELECT p.sku,p.name,ws.quantity,ws.reorder_level,w.warehouse_name FROM '.table('warehouse_stock').' ws LEFT JOIN '.table('products').' p ON p.id=ws.product_id LEFT JOIN '.table('warehouses').' w ON w.id=ws.warehouse_id WHERE ws.quantity<=ws.reorder_level ORDER BY ws.quantity ASC LIMIT 20')->fetchAll();
$dispatch=$pdo->query('SELECT d.*,w.warehouse_name FROM '.table('warehouse_dispatches').' d LEFT JOIN '.table('warehouses').' w ON w.id=d.warehouse_id ORDER BY d.created_at DESC LIMIT 12')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Warehouse Operations</div><h2 class="h4 mb-1">Advanced Warehouse Dashboard</h2><p class="text-secondary mb-0">Bins, lots, serials, stock counts, adjustments, picking, packing, dispatch, and replenishment.</p></div><a class="btn btn-brand" href="<?php echo esc(ADMIN_URL); ?>/erp/stock-counts.php">Start Stock Count</a></div>
<div class="row g-4 mb-4"><?php foreach($stats as $k=>$v): ?><div class="col-md-3"><div class="card-admin p-4"><div class="erp-kicker"><?php echo esc(ucwords(str_replace('_',' ',$k))); ?></div><div class="metric-sm"><?php echo (int)$v; ?></div></div></div><?php endforeach; ?></div>
<div class="row g-4"><div class="col-xl-6"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Low Stock by Warehouse</h2><table class="table"><thead><tr><th>Product</th><th>Warehouse</th><th>Qty</th><th>Reorder</th></tr></thead><tbody><?php foreach($low as $r): ?><tr><td><strong><?php echo esc($r['sku']); ?></strong><div class="small text-secondary"><?php echo esc($r['name']); ?></div></td><td><?php echo esc($r['warehouse_name']); ?></td><td><?php echo number_format((float)$r['quantity'],2); ?></td><td><?php echo number_format((float)$r['reorder_level'],2); ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-6"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Recent Dispatches</h2><table class="table"><thead><tr><th>Dispatch</th><th>Warehouse</th><th>Carrier</th><th>Status</th></tr></thead><tbody><?php foreach($dispatch as $d): ?><tr><td><strong><?php echo esc($d['dispatch_number']); ?></strong><div class="small text-secondary"><?php echo esc($d['tracking_number']); ?></div></td><td><?php echo esc($d['warehouse_name']); ?></td><td><?php echo esc($d['carrier']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($d['status'])); ?>"><?php echo esc($d['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>