<?php
$pageTitle='Webhook Builder 2.0';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('webhook_builder_2');
$pdo=getDB();
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $action=(string)($_POST['action']??'template');
    if($action==='template'){createWebhookEventTemplate($pdo,trim((string)$_POST['event_type']),trim((string)$_POST['template_name']),trim((string)$_POST['payload_schema']),trim((string)$_POST['sample_payload']));flash('success','Webhook event template created.');}
    elseif($action==='retry'){$id=queueWebhookRetry($pdo,(int)$_POST['webhook_event_id'],(int)($_POST['webhook_subscription_id']??0)?:null,'Manual retry queued.');flash('success','Webhook retry queued #'.$id);}
    elseif($action==='deliver'){$result=deliverWebhookEvent($pdo,(int)$_POST['webhook_event_id']);flash('success','Delivery simulated: '.$result['delivered'].' delivered, '.$result['failed'].' failed.');}
  }catch(Throwable $e){recordSystemError($pdo,$e,['page'=>'webhook-builder-2']);flash('error',$e->getMessage());}
  redirect(ADMIN_URL.'/erp/webhook-builder-2.php');
}
$templates=$pdo->query('SELECT * FROM '.table('webhook_event_templates').' ORDER BY created_at DESC LIMIT 100')->fetchAll();
$events=$pdo->query('SELECT * FROM '.table('webhook_events').' ORDER BY created_at DESC LIMIT 150')->fetchAll();
$retries=$pdo->query('SELECT r.*,e.event_number,s.subscription_code FROM '.table('webhook_retry_queue').' r LEFT JOIN '.table('webhook_events').' e ON e.id=r.webhook_event_id LEFT JOIN '.table('webhook_subscriptions').' s ON s.id=r.webhook_subscription_id ORDER BY r.created_at DESC LIMIT 100')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Event Delivery 2.0</div><h2 class="h4 mb-1">Webhook Builder 2.0</h2><p class="text-secondary mb-0">Design event templates, queue test events, deliver events and manage retry queue.</p></div><a class="btn btn-outline-primary" href="<?php echo esc(ADMIN_URL); ?>/erp/webhooks.php">Legacy Webhooks</a></div>
<div class="row g-4"><div class="col-xl-4"><form method="post" class="card-admin p-4"><input type="hidden" name="action" value="template"><h2 class="h5 mb-3">Create Event Template</h2><input class="form-control mb-2" name="event_type" placeholder="invoice.paid"><input class="form-control mb-2" name="template_name" placeholder="Invoice Paid Event"><textarea class="form-control mb-2" name="payload_schema" rows="4">{}</textarea><textarea class="form-control mb-3" name="sample_payload" rows="4">{"event":"invoice.paid"}</textarea><button class="btn btn-brand w-100">Create Template</button></form></div><div class="col-xl-8"><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Templates</h2><table class="table"><thead><tr><th>Template</th><th>Event</th><th>Status</th></tr></thead><tbody><?php foreach($templates as $t): ?><tr><td><strong><?php echo esc($t['template_code']); ?></strong><div class="small text-secondary"><?php echo esc($t['template_name']); ?></div></td><td><?php echo esc($t['event_type']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($t['status'])); ?>"><?php echo esc($t['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive mb-4"><h2 class="h5 mb-3">Webhook Events</h2><table class="table"><thead><tr><th>Event</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($events as $e): ?><tr><td><strong><?php echo esc($e['event_number']); ?></strong><div class="small text-secondary"><?php echo esc($e['created_at']); ?></div></td><td><?php echo esc($e['event_type']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($e['status'])); ?>"><?php echo esc($e['status']); ?></span></td><td><form method="post" class="d-flex gap-1"><input type="hidden" name="webhook_event_id" value="<?php echo (int)$e['id']; ?>"><button class="btn btn-sm btn-outline-primary" name="action" value="deliver">Deliver</button><button class="btn btn-sm btn-outline-secondary" name="action" value="retry">Retry</button></form></td></tr><?php endforeach; ?></tbody></table></div><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Retry Queue</h2><table class="table"><thead><tr><th>Retry</th><th>Event</th><th>Next</th><th>Status</th></tr></thead><tbody><?php foreach($retries as $r): ?><tr><td><strong><?php echo esc($r['retry_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['last_error']); ?></div></td><td><?php echo esc($r['event_number'].' · '.$r['subscription_code']); ?></td><td><?php echo esc($r['next_retry_at']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>