<?php
$pageTitle='Workflow Run History 2.0';
require_once dirname(__DIR__,2) . '/includes/functions.php';
erpGuard('workflow_run_history_2');
$pdo=getDB();
$runs=$pdo->query('SELECT wr.*,r.rule_name old_rule,br.rule_name builder_rule FROM '.table('workflow_automation_runs').' wr LEFT JOIN '.table('workflow_automation_rules').' r ON r.id=wr.workflow_automation_rule_id LEFT JOIN '.table('workflow_builder_run_steps').' s ON s.workflow_automation_run_id=wr.id LEFT JOIN '.table('workflow_builder_rules').' br ON br.id=s.workflow_builder_rule_id GROUP BY wr.id ORDER BY wr.created_at DESC LIMIT 200')->fetchAll();
$steps=$pdo->query('SELECT s.*,br.rule_number,br.rule_name,a.action_label FROM '.table('workflow_builder_run_steps').' s LEFT JOIN '.table('workflow_builder_rules').' br ON br.id=s.workflow_builder_rule_id LEFT JOIN '.table('workflow_builder_actions').' a ON a.id=s.workflow_builder_action_id ORDER BY s.created_at DESC LIMIT 300')->fetchAll();
$logs=$pdo->query('SELECT l.*,br.rule_number,br.rule_name FROM '.table('workflow_builder_action_logs').' l LEFT JOIN '.table('workflow_builder_rules').' br ON br.id=l.workflow_builder_rule_id ORDER BY l.created_at DESC LIMIT 200')->fetchAll();
include dirname(__DIR__).'/header.php';
?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><div class="erp-kicker">Automation Observability</div><h2 class="h4 mb-1">Workflow Run History 2.0</h2><p class="text-secondary mb-0">Audit workflow runs, steps, action logs, matched records and execution status.</p></div></div>
<div class="row g-4"><div class="col-xl-6"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Runs</h2><table class="table"><thead><tr><th>Run</th><th>Rule</th><th>Checked</th><th>Actions</th><th>Status</th></tr></thead><tbody><?php foreach($runs as $r): ?><tr><td><strong><?php echo esc($r['run_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['created_at']); ?></div></td><td><?php echo esc($r['builder_rule']?:$r['old_rule']); ?></td><td><?php echo (int)$r['records_checked']; ?></td><td><?php echo (int)$r['actions_created']; ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-xl-6"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Recent Steps</h2><table class="table"><thead><tr><th>Rule</th><th>Step</th><th>Reference</th><th>Status</th></tr></thead><tbody><?php foreach($steps as $s): ?><tr><td><?php echo esc($s['rule_number'].' · '.$s['rule_name']); ?></td><td><?php echo esc($s['step_type']); ?><div class="small text-secondary"><?php echo esc($s['message']); ?></div></td><td><?php echo esc($s['reference_type'].' #'.$s['reference_id']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($s['step_status'])); ?>"><?php echo esc($s['step_status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-12"><div class="table-wrap table-responsive"><h2 class="h5 mb-3">Action Logs</h2><table class="table"><thead><tr><th>Log</th><th>Rule</th><th>Action</th><th>Reference</th><th>Message</th></tr></thead><tbody><?php foreach($logs as $l): ?><tr><td><strong><?php echo esc($l['log_number']); ?></strong><div class="small text-secondary"><?php echo esc($l['created_at']); ?></div></td><td><?php echo esc($l['rule_number'].' · '.$l['rule_name']); ?></td><td><?php echo esc($l['action_type']); ?></td><td><?php echo esc($l['reference_type'].' #'.$l['reference_id']); ?></td><td><?php echo esc($l['message']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php include dirname(__DIR__).'/footer.php'; ?>