<?php
require_once dirname(__DIR__) . '/includes/functions.php';
userGuard();$user=currentUser();$pdo=getDB();
websitePermissionGuard('customer_service_requests');
$stmt=$pdo->prepare('SELECT id FROM '.table('customers').' WHERE email=? LIMIT 1');$stmt->execute([$user['email']]);$customerId=(int)($stmt->fetchColumn()?:0);
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(($_POST['action']??'asset')==='document'){
    try{$upload=uploadAdminDocument('asset_file','customer-asset-documents');if(!$upload){throw new RuntimeException('Choose a file.');}$pdo->prepare('INSERT INTO '.table('customer_asset_documents').' (customer_asset_id,user_id,document_type,file_name,stored_path,mime_type,file_size,notes) VALUES (?,?,?,?,?,?,?,?)')->execute([(int)$_POST['customer_asset_id'],$user['id'],trim((string)$_POST['document_type']),$upload['file_name'],$upload['stored_path'],$upload['mime_type'],$upload['file_size'],trim((string)$_POST['notes'])]);flash('success','Asset document uploaded.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect(SITE_URL.'/user/assets.php');
  }
  $stmt=$pdo->prepare('INSERT INTO '.table('customer_assets').' (user_id,customer_id,asset_type,asset_name,make,model,year,vin,plate_number,serial_number,odometer,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)');
  $stmt->execute([$user['id'],$customerId?:null,trim($_POST['asset_type']??'vehicle'),trim($_POST['asset_name']??''),trim($_POST['make']??''),trim($_POST['model']??''),trim($_POST['year']??''),trim($_POST['vin']??''),trim($_POST['plate_number']??''),trim($_POST['serial_number']??''),trim($_POST['odometer']??''),trim($_POST['notes']??'')]);
  flash('success','Asset saved.');redirect(SITE_URL.'/user/assets.php');
}
$stmt=$pdo->prepare('SELECT * FROM '.table('customer_assets').' WHERE user_id=? OR customer_id=? ORDER BY created_at DESC');$stmt->execute([$user['id'],$customerId]);$assets=$stmt->fetchAll();
$docs=$pdo->prepare('SELECT ad.*,ca.asset_name FROM '.table('customer_asset_documents').' ad LEFT JOIN '.table('customer_assets').' ca ON ca.id=ad.customer_asset_id WHERE ad.user_id=? ORDER BY ad.created_at DESC LIMIT 100');$docs->execute([$user['id']]);$assetDocs=$docs->fetchAll();
siteHeader('My Assets', 'login');
?>
<h1 class="mb-4">My Assets / Vehicles</h1><div class="row g-4"><div class="col-lg-5"><form method="post" class="form-card"><h2 class="h4">Add Asset</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Type</label><select class="form-select" name="asset_type"><option value="vehicle">Vehicle</option><option value="tool">Tool</option><option value="machine">Machine</option></select></div><div class="col-md-6"><label class="form-label">Asset Name</label><input class="form-control" name="asset_name" required></div><div class="col-md-6"><label class="form-label">Make</label><input class="form-control" name="make"></div><div class="col-md-6"><label class="form-label">Model</label><input class="form-control" name="model"></div><div class="col-md-6"><label class="form-label">Year</label><input class="form-control" name="year"></div><div class="col-md-6"><label class="form-label">Plate Number</label><input class="form-control" name="plate_number"></div><div class="col-md-6"><label class="form-label">VIN</label><input class="form-control" name="vin"></div><div class="col-md-6"><label class="form-label">Serial Number</label><input class="form-control" name="serial_number"></div><div class="col-md-6"><label class="form-label">Odometer</label><input class="form-control" name="odometer"></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="3"></textarea></div></div><button class="btn btn-brand mt-3">Save Asset</button></form></div><div class="col-lg-7"><div class="table-card table-responsive"><table class="table align-middle"><thead><tr><th>Asset</th><th>Details</th><th>Status</th></tr></thead><tbody><?php foreach($assets as $asset): ?><tr><td><strong><?php echo esc($asset['asset_name']); ?></strong><div class="small text-secondary"><?php echo esc($asset['asset_type']); ?></div></td><td><?php echo esc(trim(($asset['make']?:'').' '.($asset['model']?:'').' '.($asset['year']?:''))); ?><div class="small text-secondary">Plate <?php echo esc($asset['plate_number']?:'—'); ?> · VIN <?php echo esc($asset['vin']?:'—'); ?></div></td><td><span class="badge bg-<?php echo esc(statusTone($asset['status'])); ?>"><?php echo esc($asset['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$assets): ?><tr><td colspan="3" class="text-secondary">No assets added yet.</td></tr><?php endif; ?></tbody></table></div></div></div>
<div class="row g-4 mt-2"><div class="col-lg-5"><form method="post" enctype="multipart/form-data" class="form-card"><input type="hidden" name="action" value="document"><h2 class="h4">Upload Asset Document</h2><select class="form-select mb-3" name="customer_asset_id"><?php foreach($assets as $a): ?><option value="<?php echo (int)$a['id']; ?>"><?php echo esc($a['asset_name']); ?></option><?php endforeach; ?></select><input class="form-control mb-3" name="document_type" placeholder="Registration, warranty, photo, inspection"><input class="form-control mb-3" type="file" name="asset_file" required><textarea class="form-control mb-3" name="notes" rows="3" placeholder="Notes"></textarea><button class="btn btn-outline-primary">Upload Document</button></form></div><div class="col-lg-7"><div class="table-card table-responsive"><h2 class="h4 mb-3">Asset Documents</h2><table class="table"><thead><tr><th>Asset</th><th>File</th><th>Type</th><th>Date</th></tr></thead><tbody><?php foreach($assetDocs as $d): ?><tr><td><?php echo esc($d['asset_name']); ?></td><td><?php echo esc($d['file_name']); ?></td><td><?php echo esc($d['document_type']); ?></td><td><?php echo esc($d['created_at']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php siteFooter(); ?>