<?php
require_once dirname(__DIR__) . '/includes/functions.php';
userGuard();
websitePermissionGuard('customer_dashboard');
$user=currentUser();$pdo=getDB();
$stmt=$pdo->prepare('SELECT id FROM '.table('customers').' WHERE email=? LIMIT 1');$stmt->execute([$user['email']]);$customerId=(int)($stmt->fetchColumn()?:0);
$orderCount=(int)$pdo->prepare('SELECT COUNT(*) FROM '.table('orders').' WHERE user_id=?')->execute([$user['id']]);
$stmt=$pdo->prepare('SELECT COUNT(*) FROM '.table('orders').' WHERE user_id=?');$stmt->execute([$user['id']]);$orderCount=(int)$stmt->fetchColumn();
$stmt=$pdo->prepare('SELECT COUNT(*) FROM '.table('customer_assets').' WHERE user_id=? OR customer_id=?');$stmt->execute([$user['id'],$customerId]);$assetCount=(int)$stmt->fetchColumn();
$stmt=$pdo->prepare('SELECT COUNT(*) FROM '.table('customer_service_requests').' WHERE user_id=? OR customer_id=?');$stmt->execute([$user['id'],$customerId]);$requestCount=(int)$stmt->fetchColumn();
$stmt=$pdo->prepare('SELECT COUNT(*) FROM '.table('invoices').' WHERE customer_email=?');$stmt->execute([$user['email']]);$invoiceCount=(int)$stmt->fetchColumn();
$requests=$pdo->prepare('SELECT * FROM '.table('customer_service_requests').' WHERE user_id=? OR customer_id=? ORDER BY created_at DESC LIMIT 5');$requests->execute([$user['id'],$customerId]);$recentRequests=$requests->fetchAll();
$notifCount=unreadCustomerPortalNotifications($pdo,(int)$user['id'],$customerId);
$showInvoiceDisputesButton = setting('customer_dashboard_invoice_disputes_enabled','0') === '1';
$showPaymentPromisesButton = setting('customer_dashboard_payment_promises_enabled','0') === '1';
$showCustomerOrdersPortal = websitePermissionAllowed('customer_orders');
$showCustomerInvoicesPortal = websitePermissionAllowed('customer_invoices');
$showCustomerDownloadsPortal = websitePermissionAllowed('customer_downloads');
$showCustomerDocumentsPortal = websitePermissionAllowed('customer_documents');
$showCustomerServicePortal = websitePermissionAllowed('customer_service_requests');
$announcements=$pdo->query('SELECT * FROM '.table('customer_portal_announcements').' WHERE status="published" AND (publish_from IS NULL OR publish_from<=NOW()) AND (publish_to IS NULL OR publish_to>=NOW()) ORDER BY created_at DESC LIMIT 3')->fetchAll();
siteHeader('Customer Portal', 'login');
?>
<section class="portal-hero rounded-5 p-4 p-lg-5 mb-4" style="background:linear-gradient(135deg,#111827,#1d4ed8);color:#fff"><div class="row align-items-center g-4"><div class="col-lg-8"><div class="small text-uppercase opacity-75 mb-2"><?php echo t('Customer Portal', 'بوابة العميل'); ?></div><h1 class="display-6 fw-bold mb-2">Welcome, <?php echo esc($user['first_name']?:'Customer'); ?></h1><p class="mb-0 opacity-75">Track orders, invoices, service requests, assets, documents, disputes, feedback and support in one mobile-friendly workspace.</p><?php if($notifCount>0): ?><div class="mt-3"><a class="btn btn-warning" href="<?php echo esc(SITE_URL); ?>/user/notifications.php"><?php echo (int)$notifCount; ?> unread notification(s)</a></div><?php endif; ?></div><div class="col-lg-4 text-lg-end"><a class="btn btn-light" href="<?php echo esc(SITE_URL); ?>/user/service-requests.php">Create Service Request</a></div></div></section>
<div class="row g-4 mb-4"><div class="col-6 col-lg-3"><div class="metric-card p-4 h-100"><div class="text-secondary">Orders</div><div class="display-6 fw-bold"><?php echo $orderCount; ?></div><a href="<?php echo esc(SITE_URL); ?>/user/orders.php">View</a></div></div><div class="col-6 col-lg-3"><div class="metric-card p-4 h-100"><div class="text-secondary">Invoices</div><div class="display-6 fw-bold"><?php echo $invoiceCount; ?></div><a href="<?php echo esc(SITE_URL); ?>/user/invoices.php">View</a></div></div><div class="col-6 col-lg-3"><div class="metric-card p-4 h-100"><div class="text-secondary">Assets</div><div class="display-6 fw-bold"><?php echo $assetCount; ?></div><a href="<?php echo esc(SITE_URL); ?>/user/assets.php">Manage</a></div></div><div class="col-6 col-lg-3"><div class="metric-card p-4 h-100"><div class="text-secondary">Requests</div><div class="display-6 fw-bold"><?php echo $requestCount; ?></div><a href="<?php echo esc(SITE_URL); ?>/user/service-requests.php">Open</a></div></div></div>
<?php if(!empty($announcements)): ?><div class="row g-3 mb-4"><?php foreach($announcements as $a): ?><div class="col-md-4"><div class="card-clean p-3 h-100"><strong><?php echo esc($a['title']); ?></strong><p class="small text-secondary mb-0"><?php echo esc($a['message']); ?></p></div></div><?php endforeach; ?></div><?php endif; ?><div class="row g-4"><div class="col-lg-8"><div class="table-card table-responsive"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h4 mb-0">Recent Service Requests</h2><a class="btn btn-sm btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/service-requests.php">All Requests</a></div><table class="table align-middle"><thead><tr><th>Request</th><th>Subject</th><th>Priority</th><th>Status</th></tr></thead><tbody><?php foreach($recentRequests as $r): ?><tr><td><strong><?php echo esc($r['request_number']); ?></strong><div class="small text-secondary"><?php echo esc(date('M d, Y',strtotime($r['created_at']))); ?></div></td><td><?php echo esc($r['subject']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['priority'])); ?>"><?php echo esc($r['priority']); ?></span></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$recentRequests): ?><tr><td colspan="4" class="text-secondary">No service requests yet.</td></tr><?php endif; ?></tbody></table></div></div><div class="col-lg-4"><div class="form-card h-100"><h2 class="h4">Quick Links</h2><div class="d-grid gap-2"><a class="btn btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/assets.php">My Assets / Vehicles</a><a class="btn btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/downloads.php">My Downloads</a><a class="btn btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/support.php">Support Tickets</a><a class="btn btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/documents.php">My Documents</a><a class="btn btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/notifications.php">Notifications</a><?php if($showInvoiceDisputesButton): ?><a class="btn btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/invoice-disputes.php">Invoice Disputes</a><?php endif; ?><?php if($showPaymentPromisesButton): ?><a class="btn btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/payment-promises.php">Payment Promises</a><?php endif; ?><a class="btn btn-outline-primary" href="<?php echo esc(SITE_URL); ?>/user/feedback.php">Feedback</a><a class="btn btn-outline-secondary" href="<?php echo esc(SITE_URL); ?>/user/profile.php">Profile Settings</a></div></div></div></div>
<?php siteFooter(); ?>