<?php
require_once dirname(__DIR__) . '/includes/functions.php';
userGuard();$user=currentUser();$pdo=getDB();$ctx=customerPortalContext($pdo,$user);
websitePermissionGuard('customer_documents');
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{if(setting('customer_portal_documents_enabled','1')!=='1'){throw new RuntimeException('Document uploads are disabled.');}$upload=uploadAdminDocument('customer_file','customer-documents');if(!$upload){throw new RuntimeException('Choose a file.');}$pdo->prepare('INSERT INTO '.table('customer_document_uploads').' (user_id,customer_id,reference_type,reference_id,document_type,file_name,stored_path,mime_type,file_size,status,notes) VALUES (?,?,?,?,?,?,?,?,?,"uploaded",?)')->execute([$ctx['user_id'],$ctx['customer_id']?:null,trim((string)$_POST['reference_type']),(int)($_POST['reference_id']??0)?:null,trim((string)$_POST['document_type']),$upload['file_name'],$upload['stored_path'],$upload['mime_type'],$upload['file_size'],trim((string)$_POST['notes'])]);flash('success','Document uploaded.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect(SITE_URL.'/user/documents.php');
}
$stmt=$pdo->prepare('SELECT * FROM '.table('customer_document_uploads').' WHERE user_id=? OR customer_id=? ORDER BY created_at DESC');$stmt->execute([$ctx['user_id'],$ctx['customer_id']]);$docs=$stmt->fetchAll();
siteHeader('My Documents','login');
?>
<h1 class="mb-4">My Documents</h1><div class="row g-4"><div class="col-lg-5"><form method="post" enctype="multipart/form-data" class="form-card"><h2 class="h4">Upload Document</h2><div class="mb-3"><label class="form-label">Document Type</label><input class="form-control" name="document_type" placeholder="Invoice proof, vehicle registration, warranty document"></div><div class="mb-3"><label class="form-label">Reference Type</label><select class="form-select" name="reference_type"><option value="general">General</option><option value="invoice">Invoice</option><option value="service_request">Service Request</option><option value="asset">Asset</option></select></div><div class="mb-3"><label class="form-label">Reference ID</label><input class="form-control" type="number" name="reference_id"></div><div class="mb-3"><label class="form-label">File</label><input class="form-control" type="file" name="customer_file" required></div><div class="mb-3"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="3"></textarea></div><button class="btn btn-brand">Upload</button></form></div><div class="col-lg-7"><div class="table-card table-responsive"><table class="table"><thead><tr><th>File</th><th>Type</th><th>Status</th><th>Date</th></tr></thead><tbody><?php foreach($docs as $d): ?><tr><td><strong><?php echo esc($d['file_name']); ?></strong><div class="small text-secondary"><?php echo esc($d['notes']); ?></div></td><td><?php echo esc($d['document_type']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($d['status'])); ?>"><?php echo esc($d['status']); ?></span></td><td><?php echo esc($d['created_at']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php siteFooter(); ?>