<?php
require_once dirname(__DIR__) . '/includes/functions.php';
userGuard();$user=currentUser();$pdo=getDB();$ctx=customerPortalContext($pdo,$user);
websitePermissionGuard('customer_feedback');
$requests=$pdo->prepare('SELECT * FROM '.table('customer_service_requests').' WHERE user_id=? OR customer_id=? ORDER BY created_at DESC LIMIT 100');$requests->execute([$ctx['user_id'],$ctx['customer_id']]);$requests=$requests->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$pdo->prepare('INSERT INTO '.table('customer_service_feedback').' (customer_service_request_id,user_id,rating,nps_score,feedback_text,status) VALUES (?,?,?,?,?,"submitted")')->execute([(int)$_POST['customer_service_request_id']?:null,$ctx['user_id'],max(0,min(5,(int)$_POST['rating'])),max(0,min(10,(int)$_POST['nps_score'])),trim((string)$_POST['feedback_text'])]);flash('success','Thank you for your feedback.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect(SITE_URL.'/user/feedback.php');}
$rows=$pdo->prepare('SELECT f.*,csr.request_number FROM '.table('customer_service_feedback').' f LEFT JOIN '.table('customer_service_requests').' csr ON csr.id=f.customer_service_request_id WHERE f.user_id=? ORDER BY f.created_at DESC');$rows->execute([$ctx['user_id']]);$rows=$rows->fetchAll();
siteHeader('Feedback','login');
?>
<h1 class="mb-4">Service Feedback</h1><div class="row g-4"><div class="col-lg-5"><form method="post" class="form-card"><h2 class="h4">Leave Feedback</h2><select class="form-select mb-3" name="customer_service_request_id"><option value="0">General feedback</option><?php foreach($requests as $r): ?><option value="<?php echo (int)$r['id']; ?>"><?php echo esc($r['request_number'].' · '.$r['subject']); ?></option><?php endforeach; ?></select><label class="form-label">Rating /5</label><input class="form-control mb-3" type="number" min="0" max="5" name="rating" value="5"><label class="form-label">NPS /10</label><input class="form-control mb-3" type="number" min="0" max="10" name="nps_score" value="10"><textarea class="form-control mb-3" name="feedback_text" rows="5" placeholder="Tell us about your experience"></textarea><button class="btn btn-brand">Submit Feedback</button></form></div><div class="col-lg-7"><div class="table-card table-responsive"><table class="table"><thead><tr><th>Reference</th><th>Rating</th><th>NPS</th><th>Feedback</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?php echo esc($r['request_number']?:'General'); ?></td><td><?php echo (int)$r['rating']; ?>/5</td><td><?php echo (int)$r['nps_score']; ?>/10</td><td><?php echo esc($r['feedback_text']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php siteFooter(); ?>