<?php
require_once dirname(__DIR__) . '/includes/functions.php';
userGuard();$user=currentUser();$pdo=getDB();$ctx=customerPortalContext($pdo,$user);
websitePermissionGuard('customer_payment_promises');
$invStmt=$pdo->prepare('SELECT * FROM '.table('invoices').' WHERE customer_email=? AND balance_due>0 ORDER BY created_at DESC');$invStmt->execute([$ctx['email']]);$invoices=$invStmt->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){try{createCustomerPaymentPromise($pdo,(int)$_POST['invoice_id'],$ctx['user_id'],$ctx['customer_id'],max(0,(float)$_POST['promised_amount']),trim((string)$_POST['promised_date']),trim((string)$_POST['notes']));flash('success','Payment promise submitted.');}catch(Throwable $e){flash('error',$e->getMessage());}redirect(SITE_URL.'/user/payment-promises.php');}
$stmt=$pdo->prepare('SELECT p.*,i.invoice_number FROM '.table('customer_payment_promises').' p LEFT JOIN '.table('invoices').' i ON i.id=p.invoice_id WHERE p.user_id=? OR p.customer_id=? ORDER BY p.created_at DESC');$stmt->execute([$ctx['user_id'],$ctx['customer_id']]);$rows=$stmt->fetchAll();
siteHeader('Payment Promises','login');
?>
<h1 class="mb-4">Payment Promises</h1><div class="row g-4"><div class="col-lg-5"><form method="post" class="form-card"><h2 class="h4">Promise to Pay</h2><select class="form-select mb-3" name="invoice_id"><?php foreach($invoices as $i): ?><option value="<?php echo (int)$i['id']; ?>"><?php echo esc($i['invoice_number'].' · Balance '.money($i['balance_due'])); ?></option><?php endforeach; ?></select><input class="form-control mb-3" type="number" step="0.01" name="promised_amount" placeholder="Amount" required><input class="form-control mb-3" type="date" name="promised_date" required><textarea class="form-control mb-3" name="notes" rows="4" placeholder="Notes"></textarea><button class="btn btn-brand">Submit Promise</button></form></div><div class="col-lg-7"><div class="table-card table-responsive"><table class="table"><thead><tr><th>Promise</th><th>Invoice</th><th>Amount</th><th>Date</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?php echo esc($r['promise_number']); ?></strong></td><td><?php echo esc($r['invoice_number']); ?></td><td><?php echo money($r['promised_amount']); ?></td><td><?php echo esc($r['promised_date']); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php siteFooter(); ?>