<?php
require_once dirname(__DIR__) . '/includes/functions.php';
userGuard();$user=currentUser();$pdo=getDB();
websitePermissionGuard('customer_service_requests');
$stmt=$pdo->prepare('SELECT id FROM '.table('customers').' WHERE email=? LIMIT 1');$stmt->execute([$user['email']]);$customerId=(int)($stmt->fetchColumn()?:0);
$assetsStmt=$pdo->prepare('SELECT * FROM '.table('customer_assets').' WHERE user_id=? OR customer_id=? ORDER BY asset_name');$assetsStmt->execute([$user['id'],$customerId]);$assets=$assetsStmt->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  $prefix=setting('portal_service_request_prefix','CSR');$number=$prefix.'-'.date('YmdHis').'-'.random_int(100,999);
  $stmt=$pdo->prepare('INSERT INTO '.table('customer_service_requests').' (request_number,user_id,customer_id,customer_asset_id,service_type,subject,description,preferred_date,preferred_time,priority,status) VALUES (?,?,?,?,?,?,?,?,?,?,"open")');
  $stmt->execute([$number,$user['id'],$customerId?:null,(int)($_POST['customer_asset_id']??0)?:null,trim($_POST['service_type']??''),trim($_POST['subject']??''),trim($_POST['description']??''),trim($_POST['preferred_date']??'')?:null,trim($_POST['preferred_time']??'')?:null,trim($_POST['priority']??'medium')]);
  $requestId=(int)$pdo->lastInsertId();
  $pdo->prepare('INSERT INTO '.table('customer_service_request_messages').' (customer_service_request_id,sender_user_id,sender_type,message) VALUES (?,?, "customer", ?)')->execute([$requestId,$user['id'],trim($_POST['description']??'')]);
  createCustomerPortalNotification($pdo,(int)$user['id'],$customerId?:null,'Service request created','Your service request '.$number.' has been submitted.','/user/service-requests.php');
  flash('success','Service request created: '.$number);redirect(SITE_URL.'/user/service-requests.php');
}
$stmt=$pdo->prepare('SELECT csr.*,ca.asset_name FROM '.table('customer_service_requests').' csr LEFT JOIN '.table('customer_assets').' ca ON ca.id=csr.customer_asset_id WHERE csr.user_id=? OR csr.customer_id=? ORDER BY csr.created_at DESC');$stmt->execute([$user['id'],$customerId]);$requests=$stmt->fetchAll();
siteHeader('Service Requests', 'login');
?>
<h1 class="mb-4">Service Requests</h1><div class="row g-4"><div class="col-lg-5"><form method="post" class="form-card"><h2 class="h4">Create Request</h2><label class="form-label">Asset</label><select class="form-select mb-3" name="customer_asset_id"><option value="0">General request</option><?php foreach($assets as $asset): ?><option value="<?php echo (int)$asset['id']; ?>"><?php echo esc($asset['asset_name'].' · '.$asset['plate_number']); ?></option><?php endforeach; ?></select><label class="form-label">Service Type</label><input class="form-control mb-3" name="service_type" placeholder="Diagnosis, installation, remote support..."><label class="form-label">Subject</label><input class="form-control mb-3" name="subject" required><label class="form-label">Priority</label><select class="form-select mb-3" name="priority"><option>low</option><option selected>medium</option><option>high</option><option>urgent</option></select><div class="row g-3"><div class="col-6"><label class="form-label">Preferred Date</label><input class="form-control" type="date" name="preferred_date"></div><div class="col-6"><label class="form-label">Time</label><input class="form-control" type="time" name="preferred_time"></div></div><label class="form-label mt-3">Description</label><textarea class="form-control" rows="5" name="description" required></textarea><button class="btn btn-brand mt-3">Submit Request</button></form></div><div class="col-lg-7"><div class="table-card table-responsive"><table class="table align-middle"><thead><tr><th>Request</th><th>Asset</th><th>Priority</th><th>Status</th></tr></thead><tbody><?php foreach($requests as $r): ?><tr><td><strong><?php echo esc($r['request_number']); ?></strong><div class="small text-secondary"><?php echo esc($r['subject']); ?></div></td><td><?php echo esc($r['asset_name']?:'General'); ?></td><td><span class="badge bg-<?php echo esc(statusTone($r['priority'])); ?>"><?php echo esc($r['priority']); ?></span></td><td><span class="badge bg-<?php echo esc(statusTone($r['status'])); ?>"><?php echo esc($r['status']); ?></span></td></tr><?php endforeach; ?><?php if(!$requests): ?><tr><td colspan="4" class="text-secondary">No requests yet.</td></tr><?php endif; ?></tbody></table></div></div></div>
<?php siteFooter(); ?>